-- =====================================================================
-- V10: evento historico de reasignacion agente -> broker (E1).
--
-- supervision_agente conserva la relacion VIGENTE y su periodo. Esta tabla
-- conserva el hecho inmutable que exige el contrato legado: broker anterior,
-- broker nuevo, administrador que autorizo, motivo y fecha-hora del cambio.
--
-- Es privada del tenant: organizacion_id participa en todas las FK para que
-- ninguna reasignacion pueda mezclar roles de organizaciones distintas.
-- =====================================================================

CREATE TABLE reasignacion_agente_broker (
    id_reasignacion              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id              BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    fecha_cambio                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    motivo                       TEXT        NOT NULL,
    id_rol_agente                BIGINT      NOT NULL REFERENCES detalle_agente (id_persona_rol),
    id_rol_broker_anterior       BIGINT      REFERENCES detalle_broker (id_persona_rol),
    id_rol_broker_nuevo          BIGINT      NOT NULL REFERENCES detalle_broker (id_persona_rol),
    id_rol_broker_administrador  BIGINT      NOT NULL REFERENCES detalle_broker (id_persona_rol),
    CONSTRAINT ck_reasignacion_agente_brokers CHECK (
        id_rol_broker_anterior IS NULL OR id_rol_broker_anterior <> id_rol_broker_nuevo),
    CONSTRAINT uq_reasignacion_agente_broker_org
        UNIQUE (organizacion_id, id_reasignacion),
    CONSTRAINT fk_reasignacion_agente_org
        FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol),
    CONSTRAINT fk_reasignacion_broker_anterior_org
        FOREIGN KEY (organizacion_id, id_rol_broker_anterior)
        REFERENCES detalle_broker (organizacion_id, id_persona_rol),
    CONSTRAINT fk_reasignacion_broker_nuevo_org
        FOREIGN KEY (organizacion_id, id_rol_broker_nuevo)
        REFERENCES detalle_broker (organizacion_id, id_persona_rol),
    CONSTRAINT fk_reasignacion_broker_admin_org
        FOREIGN KEY (organizacion_id, id_rol_broker_administrador)
        REFERENCES detalle_broker (organizacion_id, id_persona_rol)
);

CREATE INDEX ix_reasignacion_agente_fecha
    ON reasignacion_agente_broker (organizacion_id, id_rol_agente, fecha_cambio DESC);

CREATE INDEX ix_reasignacion_org_id
    ON reasignacion_agente_broker (organizacion_id, id_reasignacion DESC);
