-- =====================================================================
-- V15: EXPANSION del modelo economico y contractual.
--
-- Esta migracion solo agrega estructura. V16 hace el backfill con evidencia
-- y V17 aplica las restricciones finales y elimina las columnas sustituidas.
-- No se asignan monedas ni significados economicos por defecto.
-- =====================================================================

-- El registro fisico y su disponibilidad comercial son dimensiones distintas.
ALTER TABLE propiedad
    ADD COLUMN estado_registro VARCHAR(1),
    ADD COLUMN disponibilidad_comercial VARCHAR(1),
    ADD COLUMN interior_unidad VARCHAR(40),
    ADD COLUMN piso VARCHAR(30),
    ADD COLUMN referencia_interna VARCHAR(120),
    ADD COLUMN nombre_edificio_galeria VARCHAR(150);

-- El encargo y su cierre dejan de compartir una vigencia generica.
ALTER TABLE captacion
    ADD COLUMN fecha_inicio_encargo DATE,
    ADD COLUMN fecha_fin_encargo DATE,
    ADD COLUMN fecha_cierre DATE,
    ADD COLUMN motivo_cierre VARCHAR(1),
    ADD COLUMN detalle_motivo_cierre VARCHAR(300),
    ADD COLUMN id_condicion_economica BIGINT;

CREATE TABLE condicion_economica_captacion (
    id_condicion_economica BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT NOT NULL REFERENCES organizacion (id_organizacion),
    tipo_operacion VARCHAR(1) NOT NULL,
    importe_referencia NUMERIC(14,2) NOT NULL,
    moneda_referencia VARCHAR(3) NOT NULL,
    tipo_comision VARCHAR(1) NOT NULL,
    base_calculo VARCHAR(1) NOT NULL,
    valor_comision NUMERIC(12,4) NOT NULL,
    moneda_comision VARCHAR(3),
    tratamiento_igv VARCHAR(1) NOT NULL,
    motivo_sin_comision VARCHAR(300),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT uq_condicion_economica_org UNIQUE (organizacion_id, id_condicion_economica)
);

CREATE INDEX ix_condicion_economica_organizacion
    ON condicion_economica_captacion (organizacion_id, tipo_operacion);

ALTER TABLE captacion
    ADD CONSTRAINT fk_captacion_condicion_org
    FOREIGN KEY (organizacion_id, id_condicion_economica)
    REFERENCES condicion_economica_captacion (organizacion_id, id_condicion_economica);

CREATE UNIQUE INDEX uq_captacion_condicion_economica
    ON captacion (id_condicion_economica)
    WHERE id_condicion_economica IS NOT NULL;

-- Los datos cuyo significado no puede probarse quedan identificados y nunca
-- se convierten por rango o cercania con otro importe.
CREATE TABLE regularizacion_dato_economico (
    id_regularizacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT NOT NULL REFERENCES organizacion (id_organizacion),
    entidad_tipo VARCHAR(30) NOT NULL,
    entidad_id BIGINT NOT NULL,
    campo VARCHAR(60) NOT NULL,
    valor_origen VARCHAR(200),
    motivo VARCHAR(300) NOT NULL,
    estado VARCHAR(1) NOT NULL DEFAULT 'P',
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_resolucion TIMESTAMPTZ,
    usuario_resolucion BIGINT,
    CONSTRAINT uq_regularizacion_economica UNIQUE
        (organizacion_id, entidad_tipo, entidad_id, campo)
);

-- El contrato conserva su snapshot juridico y economico. La renovacion crea
-- un sucesor enlazado; nunca sobrescribe al anterior.
ALTER TABLE contrato_alquiler
    ADD COLUMN fecha_inicio_contrato DATE,
    ADD COLUMN fecha_fin_contrato DATE,
    ADD COLUMN renta_contractual NUMERIC(14,2),
    ADD COLUMN moneda VARCHAR(3),
    ADD COLUMN id_contrato_anterior BIGINT,
    ADD COLUMN fecha_efectiva_estado DATE;

ALTER TABLE contrato_alquiler
    ADD CONSTRAINT fk_contrato_anterior_org
    FOREIGN KEY (organizacion_id, id_contrato_anterior)
    REFERENCES contrato_alquiler (organizacion_id, id_contrato_alquiler);

CREATE UNIQUE INDEX uq_contrato_sucesor
    ON contrato_alquiler (id_contrato_anterior)
    WHERE id_contrato_anterior IS NOT NULL;

-- La liquidacion conserva el snapshot bruto y el reparto. Los pagos reales
-- se registran en movimientos; una marca de estado deja de ser evidencia.
ALTER TABLE comision_liquidacion
    ADD COLUMN monto_bruto NUMERIC(14,2),
    ADD COLUMN parte_empresa NUMERIC(14,2),
    ADD COLUMN parte_agente NUMERIC(14,2);

CREATE TABLE comision_movimiento (
    id_comision_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT NOT NULL REFERENCES organizacion (id_organizacion),
    id_comision_liquidacion BIGINT NOT NULL,
    tipo VARCHAR(1) NOT NULL,
    monto NUMERIC(14,2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    fecha DATE NOT NULL,
    forma_pago VARCHAR(20),
    id_usuario BIGINT,
    rol_usuario VARCHAR(20),
    observacion VARCHAR(300),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_comision_movimiento_org UNIQUE (organizacion_id, id_comision_movimiento),
    CONSTRAINT fk_movimiento_comision_org
        FOREIGN KEY (organizacion_id, id_comision_liquidacion)
        REFERENCES comision_liquidacion (organizacion_id, id_comision_liquidacion)
);

CREATE INDEX ix_comision_movimiento_liquidacion
    ON comision_movimiento (organizacion_id, id_comision_liquidacion, fecha, id_comision_movimiento);

-- Fecha efectiva de negocio, distinta del momento tecnico de registro.
ALTER TABLE historial_estado ADD COLUMN fecha_efectiva DATE;
