-- =====================================================================
-- ControlLocal BD v2 (PostgreSQL) - F0 Fundacion
-- V1: identidad Party-Role (Doc 5 §3) + supervision broker->agente.
--
-- Decisiones aplicadas:
--  * Party-Role REAL: persona (party) + persona_rol con vigencia; los
--    atributos por rol van en tablas de detalle con PK compartida.
--  * BROKER/AGENTE son roles DE LA PERSONA (no de usuario_interno);
--    el acceso al sistema es el rol USUARIO_INTERNO (credencial).
--  * Integridad rol<->detalle sin triggers (MEJ-11): cada detalle fija
--    su tipo_rol por CHECK y lo referencia con FK compuesta
--    (id_persona_rol, tipo_rol) -> persona_rol.
--  * Unicidad parcial NATIVA de Postgres (MEJ-21): reemplaza las
--    columnas GENERATED STORED de la v1 MySQL.
--  * Codigos de 1 caracter heredados del cable congelado (tipo_persona N/J,
--    tipo_documento D/R/C/P, estados A/I, estado_operativo D/L/N) en
--    VARCHAR(1): en Postgres CHAR es bpchar (con relleno) y rompe la
--    validacion de esquema JPA. Los enums legibles llegan tras el corte.
-- =====================================================================

CREATE TABLE persona (
    id_persona              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_persona            VARCHAR(1)      NOT NULL,
    tipo_documento          VARCHAR(1)      NOT NULL,
    numero_documento        VARCHAR(30)  NOT NULL,
    nombres_o_razon_social  VARCHAR(150) NOT NULL,
    telefono                VARCHAR(20),
    correo                  VARCHAR(150),
    estado                  VARCHAR(1)      NOT NULL DEFAULT 'A',
    consentimiento_uso_dato BOOLEAN,
    -- Clave opaca de la foto de perfil en el almacen (S3/disco); NULL si no subio foto.
    foto_clave              VARCHAR(200),
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_actualizacion     TIMESTAMPTZ,
    CONSTRAINT uq_persona_documento      UNIQUE (tipo_documento, numero_documento),
    CONSTRAINT uq_persona_correo         UNIQUE (correo),
    CONSTRAINT ck_persona_tipo_persona   CHECK (tipo_persona IN ('N', 'J')),
    CONSTRAINT ck_persona_tipo_documento CHECK (tipo_documento IN ('D', 'R', 'C', 'P')),
    CONSTRAINT ck_persona_estado         CHECK (estado IN ('A', 'I'))
);

CREATE TABLE persona_rol (
    id_persona_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona     BIGINT      NOT NULL REFERENCES persona (id_persona),
    tipo_rol       VARCHAR(20) NOT NULL,
    vigencia_desde DATE        NOT NULL DEFAULT CURRENT_DATE,
    vigencia_hasta DATE,
    CONSTRAINT ck_persona_rol_tipo CHECK (
        tipo_rol IN ('PROPIETARIO', 'CLIENTE', 'USUARIO_INTERNO', 'BROKER', 'AGENTE')
    ),
    CONSTRAINT ck_persona_rol_vigencia CHECK (vigencia_hasta IS NULL OR vigencia_hasta >= vigencia_desde),
    -- El par (id, tipo) es el destino de las FK compuestas de los detalles por rol.
    CONSTRAINT uq_persona_rol_id_tipo UNIQUE (id_persona_rol, tipo_rol)
);

-- Un solo rol VIGENTE de cada tipo por persona; los roles cerrados quedan como historico (RC-002).
CREATE UNIQUE INDEX uq_persona_rol_vigente ON persona_rol (id_persona, tipo_rol) WHERE vigencia_hasta IS NULL;
CREATE INDEX ix_persona_rol_persona ON persona_rol (id_persona);

-- ---------------------------------------------------------------------
-- Detalle del rol USUARIO_INTERNO: credenciales de acceso al sistema.
-- ---------------------------------------------------------------------
CREATE TABLE credencial_usuario (
    id_persona_rol        BIGINT       PRIMARY KEY,
    tipo_rol              VARCHAR(20)  NOT NULL DEFAULT 'USUARIO_INTERNO',
    nombre_usuario        VARCHAR(60)  NOT NULL UNIQUE,
    -- Formato pbkdf2$<iteraciones>$<salBase64>$<hashBase64> (compatible con la v1).
    contrasena_hash       VARCHAR(255) NOT NULL,
    estado_administrativo VARCHAR(1)      NOT NULL DEFAULT 'A',
    CONSTRAINT ck_credencial_tipo_rol CHECK (tipo_rol = 'USUARIO_INTERNO'),
    CONSTRAINT ck_credencial_estado   CHECK (estado_administrativo IN ('A', 'I')),
    CONSTRAINT fk_credencial_rol FOREIGN KEY (id_persona_rol, tipo_rol)
        REFERENCES persona_rol (id_persona_rol, tipo_rol)
);

-- ---------------------------------------------------------------------
-- Detalle del rol BROKER.
-- ---------------------------------------------------------------------
CREATE TABLE detalle_broker (
    id_persona_rol    BIGINT      PRIMARY KEY,
    tipo_rol          VARCHAR(20) NOT NULL DEFAULT 'BROKER',
    codigo_broker     VARCHAR(20) NOT NULL UNIQUE,
    zona              VARCHAR(100),
    fecha_designacion DATE        NOT NULL,
    es_administrador  BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_detalle_broker_tipo_rol CHECK (tipo_rol = 'BROKER'),
    CONSTRAINT fk_detalle_broker_rol FOREIGN KEY (id_persona_rol, tipo_rol)
        REFERENCES persona_rol (id_persona_rol, tipo_rol)
);

-- Broker administrador UNICO en todo el sistema (indice unico parcial nativo).
CREATE UNIQUE INDEX uq_broker_admin_unico ON detalle_broker ((es_administrador)) WHERE es_administrador;

-- ---------------------------------------------------------------------
-- Detalle del rol AGENTE.
-- ---------------------------------------------------------------------
CREATE TABLE detalle_agente (
    id_persona_rol   BIGINT      PRIMARY KEY,
    tipo_rol         VARCHAR(20) NOT NULL DEFAULT 'AGENTE',
    codigo_agente    VARCHAR(20) NOT NULL UNIQUE,
    zona_asignada    VARCHAR(100),
    fecha_ingreso    DATE        NOT NULL,
    estado_operativo VARCHAR(1)     NOT NULL DEFAULT 'D',
    CONSTRAINT ck_detalle_agente_tipo_rol CHECK (tipo_rol = 'AGENTE'),
    CONSTRAINT ck_detalle_agente_estado   CHECK (estado_operativo IN ('D', 'L', 'N')),
    CONSTRAINT fk_detalle_agente_rol FOREIGN KEY (id_persona_rol, tipo_rol)
        REFERENCES persona_rol (id_persona_rol, tipo_rol)
);

-- ---------------------------------------------------------------------
-- Supervision broker->agente con vigencia (ex broker_agente de la v1).
-- Es la base del alcance por fila del broker supervisor (Doc 5 §8/§13).
-- ---------------------------------------------------------------------
CREATE TABLE supervision_agente (
    id_supervision   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol_broker    BIGINT NOT NULL REFERENCES detalle_broker (id_persona_rol),
    id_rol_agente    BIGINT NOT NULL REFERENCES detalle_agente (id_persona_rol),
    fecha_asignacion DATE   NOT NULL,
    fecha_fin        DATE,
    motivo           TEXT   NOT NULL,
    CONSTRAINT ck_supervision_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_asignacion)
);

-- Un solo broker supervisor ACTIVO por agente (reemplaza id_agente_activo GENERATED de la v1).
CREATE UNIQUE INDEX uq_supervision_activa ON supervision_agente (id_rol_agente) WHERE fecha_fin IS NULL;
CREATE INDEX ix_supervision_broker ON supervision_agente (id_rol_broker) WHERE fecha_fin IS NULL;
