-- =====================================================================
-- V2: trazabilidad universal (pilar RC-002, Doc 5 §7).
--  * entidad_tipo: catalogo MAESTRO del vocabulario polimorfico (MEJ-19).
--    Dos subconjuntos: auditable (tiene maquina de estados cuyas
--    transiciones emiten historial) y referenciable (tarea/alerta pueden
--    apuntarle). Reemplaza los vocabularios divergentes de la v1.
--  * historial_estado: registro de transiciones para TODAS las entidades
--    auditables. El actor es la persona (identidad unica) + el rol con el
--    que opero; id_actor NULL = actor de sistema (jobs).
-- La escritura se hara SOLO via el aspecto de auditoria de la capa
-- service (F1/F6), nunca con llamadas manuales dispersas (causa MEJ-01).
-- =====================================================================

CREATE TABLE entidad_tipo (
    codigo        VARCHAR(30)  PRIMARY KEY,
    descripcion   VARCHAR(150) NOT NULL,
    auditable     BOOLEAN      NOT NULL DEFAULT FALSE,
    referenciable BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE historial_estado (
    id_historial    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_tipo    VARCHAR(30) NOT NULL REFERENCES entidad_tipo (codigo),
    id_entidad      BIGINT      NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo    VARCHAR(30) NOT NULL,
    id_actor        BIGINT REFERENCES persona (id_persona),
    tipo_rol_actor  VARCHAR(20),
    -- Obligatorio en transiciones sensibles (MEJ-03); lo exige la capa service.
    motivo          VARCHAR(300),
    fecha_evento    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Lectura del timeline por entidad y por actor (heredando el patron de indexado compuesto).
CREATE INDEX ix_historial_entidad ON historial_estado (entidad_tipo, id_entidad, fecha_evento DESC);
CREATE INDEX ix_historial_actor   ON historial_estado (id_actor, fecha_evento DESC);

INSERT INTO entidad_tipo (codigo, descripcion, auditable, referenciable) VALUES
    ('PERSONA',              'Persona (party)',                TRUE,  TRUE),
    ('PROSPECCION',          'Prospeccion de local',           TRUE,  TRUE),
    ('CAPTACION',            'Captacion de local',             TRUE,  TRUE),
    ('PROPIEDAD',            'Propiedad / inmueble',           TRUE,  TRUE),
    ('PUBLICACION',          'Publicacion de propiedad',       TRUE,  TRUE),
    ('OPORTUNIDAD',          'Oportunidad comercial',          TRUE,  TRUE),
    ('VISITA',               'Visita programada',              TRUE,  TRUE),
    ('SOLICITUD_ALQUILER',   'Solicitud de alquiler',          TRUE,  TRUE),
    ('DOCUMENTO_SOLICITUD',  'Documento de solicitud',         TRUE,  TRUE),
    ('EVALUACION',           'Evaluacion de solicitud',        TRUE,  TRUE),
    ('CONTRATO_ALQUILER',    'Contrato de alquiler',           TRUE,  TRUE),
    ('COMISION_LIQUIDACION', 'Liquidacion de comision',        TRUE,  TRUE),
    ('CLIENTE_INTERESADO',   'Cliente interesado',             FALSE, TRUE),
    ('PROPIETARIO',          'Propietario',                    FALSE, TRUE),
    ('REQUERIMIENTO',        'Requerimiento de cliente',       FALSE, TRUE),
    ('TAREA',                'Tarea de la bandeja',            FALSE, FALSE),
    ('ALERTA',               'Alerta',                         FALSE, FALSE);
