-- =====================================================================
-- V30: auditoria de seguridad y bloqueo de accesos.
--
-- Bloque "Seguridad de sesiones, auditoria y bloqueo de accesos".
-- Segunda entrega, despues de V29 (invalidacion de sesiones).
--
-- Dos tablas, dos propositos que NO se mezclan:
--   * evento_seguridad: QUE paso con accesos y privilegios (append-only).
--   * intento_acceso:   CUANTAS veces se intento entrar, para poder frenar.
--
-- Se separan de historial_estado a proposito (Plan S0 §6.3): aquello audita
-- TRANSICIONES DE NEGOCIO; esto audita ACCESOS Y PRIVILEGIOS. Mezclarlos
-- volveria inmanejables las dos consultas.
-- =====================================================================

-- ---------------------------------------------------------------------
-- V30.1  evento_seguridad — APPEND-ONLY
--
-- Sin UPDATE ni DELETE: un registro de seguridad que se puede editar no
-- prueba nada. Aqui se crea la tabla y el indice; retirar los privilegios
-- al usuario de la aplicacion es tarea del despliegue productivo, porque en
-- dev el mismo rol es dueno del esquema.
-- ---------------------------------------------------------------------
CREATE TABLE evento_seguridad (
    id_evento       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    fecha           TIMESTAMPTZ NOT NULL DEFAULT now(),
    tipo            VARCHAR(40) NOT NULL,
    resultado       VARCHAR(10) NOT NULL,
    -- Puede no haber credencial ni persona: un login fallido contra un
    -- usuario inexistente es justo el caso que mas interesa registrar.
    id_credencial   BIGINT,
    id_persona      BIGINT,
    rol_efectivo    VARCHAR(20),
    ip              VARCHAR(45),
    agente_usuario  VARCHAR(300),
    -- Objetivo de una accion administrativa (a quien se le otorgo un rol,
    -- a quien se desbloqueo). NULL cuando el evento es sobre uno mismo.
    id_objetivo     BIGINT,
    motivo          VARCHAR(300),
    detalle_json    TEXT,
    CONSTRAINT ck_evento_seguridad_resultado CHECK (resultado IN ('OK', 'FALLO', 'BLOQUEADO')),
    CONSTRAINT ck_evento_seguridad_tipo CHECK (tipo IN (
        'LOGIN_OK', 'LOGIN_FALLIDO', 'LOGIN_BLOQUEADO_429',
        'LOGOUT', 'SESIONES_INVALIDADAS',
        'CUENTA_BLOQUEADA', 'CUENTA_DESBLOQUEADA',
        'MFA_OK', 'MFA_FALLIDO',
        'PASSWORD_CAMBIADA', 'PASSWORD_RESTABLECIDA',
        'INVITACION_EMITIDA', 'INVITACION_CANJEADA',
        'RECUPERACION_EMITIDA', 'RECUPERACION_CANJEADA',
        'CUENTA_ACTIVADA', 'CUENTA_DESACTIVADA',
        'ROL_OTORGADO', 'ROL_REVOCADO',
        'ACCESO_TENANT_CONCEDIDO', 'ACCESO_TENANT_USADO',
        'BREAK_GLASS_ACTIVADO'
    ))
);

COMMENT ON TABLE evento_seguridad IS
    'Auditoria de accesos y privilegios (Plan S0 §6.3). APPEND-ONLY. '
    'Regla de higiene, verificada por test: detalle_json NO puede llevar '
    'contrasenas, hashes, tokens ni secretos MFA.';

COMMENT ON COLUMN evento_seguridad.tipo IS
    'El CHECK lista los tipos previstos, incluidos los de bloques que todavia '
    'no existen (MFA, invitaciones, break-glass). Estan aqui para que anadir '
    'esos flujos no exija una migracion mas, no porque ya se emitan.';

-- Las dos consultas reales: el timeline de una cuenta y el barrido por tipo
-- ("todos los bloqueos de ayer"). Las dos leen siempre dentro de un tenant.
CREATE INDEX ix_evento_seguridad_persona
    ON evento_seguridad (organizacion_id, id_persona, fecha DESC);
CREATE INDEX ix_evento_seguridad_tipo
    ON evento_seguridad (organizacion_id, tipo, fecha DESC);

-- ---------------------------------------------------------------------
-- V30.2  intento_acceso — el contador del bloqueo (D-S0-21)
--
-- Vive en PostgreSQL y no en memoria ni en Redis:
--   * en memoria, un reinicio borra el contador y con N instancias el limite
--     efectivo se multiplica por N (H-07);
--   * Redis es infraestructura nueva, y el encargo la prohibe sin necesidad
--     demostrada. Con una sola instancia, Postgres es fuente compartida de
--     sobra.
--
-- `organizacion_id` es NULLABLE y la tabla NO es privada de un tenant: un
-- intento de acceso es PRE-TENANT, ocurre antes de saber quien pregunta.
-- Contar solo los usuarios que existen convertiria el propio bloqueo en un
-- oraculo del padron de cuentas.
-- ---------------------------------------------------------------------
CREATE TABLE intento_acceso (
    id_intento       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT REFERENCES organizacion (id_organizacion),
    clave_tipo       VARCHAR(10) NOT NULL,
    -- HASH del identificador, nunca el nombre de usuario en claro: esta tabla
    -- no puede convertirse en un padron de usuarios probados por atacantes.
    clave_valor_hash VARCHAR(64) NOT NULL,
    ocurrido_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    exito            BOOLEAN     NOT NULL,
    ip               VARCHAR(45),
    agente_usuario   VARCHAR(300),
    CONSTRAINT ck_intento_clave_tipo CHECK (clave_tipo IN ('CUENTA', 'IP'))
);

COMMENT ON COLUMN intento_acceso.clave_valor_hash IS
    'SHA-256 en hexadecimal del identificador normalizado (usuario en '
    'minusculas, o IP). Permite contar sin guardar a quien se intento.';

COMMENT ON COLUMN intento_acceso.organizacion_id IS
    'Informativo. NULL cuando el intento no se pudo atribuir a ninguna '
    'organizacion. La tabla NO es privada de un tenant: se cuenta antes de '
    'saber quien pregunta.';

-- La consulta caliente es exactamente una: "fallos de esta clave en los
-- ultimos N minutos". El indice esta hecho para esa y solo esa.
CREATE INDEX ix_intento_ventana
    ON intento_acceso (clave_tipo, clave_valor_hash, ocurrido_en DESC);

-- Purga por retencion: sin ella, la tabla crece sin techo y el barrido de la
-- ventana se degrada. 30 dias es lo que fija el Plan S0 §4.8.
CREATE INDEX ix_intento_purga ON intento_acceso (ocurrido_en);
