-- =====================================================================
-- V31: contrasenas y recuperacion de acceso (Plan S0 §4.1-§4.5).
--
-- Bloque "Contrasenas y recuperacion", el siguiente a sesiones/auditoria.
-- Cierra H-02 (no existe ninguna forma de cambiar una contrasena) y H-08
-- (no existe ninguna forma de recuperar el acceso salvo SQL).
--
-- Lo que NO entra aqui, a proposito: la expansion de identidad
-- (`persona_rol` con ADMIN, `usuario_organizacion` con TENANT_ADMIN /
-- PLATFORM_ADMIN) sigue esperando a D-S0-17. Mientras tanto, las
-- operaciones administrativas de este bloque las ejerce el rol ADMIN
-- actual, que YA es el rol de gobierno del tenant: no opera el flujo
-- comercial, solo administra usuarios y lee. Cuando el Bloque 5 parta
-- ADMIN en TENANT_ADMIN, esas filas de la matriz cambian de titular sin
-- tocar el esquema.
-- =====================================================================

-- ---------------------------------------------------------------------
-- V31.1  Las tres columnas que le faltaban a la credencial
--
-- V29 trajo solo `sesiones_invalidas_desde` porque era lo unico que
-- necesitaba el bloque de sesiones. Estas tres son de su duenio real.
-- ---------------------------------------------------------------------
ALTER TABLE credencial_usuario
    ADD COLUMN debe_cambiar_contrasena BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN password_actualizada_en TIMESTAMPTZ,
    ADD COLUMN algoritmo_hash          VARCHAR(20) NOT NULL DEFAULT 'pbkdf2';

COMMENT ON COLUMN credencial_usuario.debe_cambiar_contrasena IS
    'TRUE = la sesion existe pero esta CAPADA: el filtro solo deja pasar '
    'GET /sesion y POST /perfil/contrasena, y responde 403 en todo lo demas. '
    'Lo enciende la contrasena temporal; lo apaga el cambio efectivo.';

COMMENT ON COLUMN credencial_usuario.password_actualizada_en IS
    'Cuando se fijo la contrasena vigente. NULL = nunca se cambio desde el '
    'alta (las 21 cuentas del seed nacen asi). Sirve para caducidad y para '
    'poder responder "desde cuando" en una auditoria.';

COMMENT ON COLUMN credencial_usuario.algoritmo_hash IS
    'Permite convivir dos algoritmos durante la migracion progresiva del '
    'hash (§4.6): al validar una credencial con el algoritmo viejo se '
    're-hashea con el nuevo en el MISMO login. Hoy solo existe pbkdf2.';

-- Las credenciales que ya existen no se tocan: `password_actualizada_en`
-- queda NULL a proposito (no se inventa una fecha que nadie registro) y
-- `debe_cambiar_contrasena` queda FALSE para no capar de golpe las 21
-- cuentas del seed de desarrollo. La neutralizacion del seed productivo
-- es asunto de V900, que corre solo en `prod`.

-- ---------------------------------------------------------------------
-- V31.2  token_acceso — el token de un solo uso (§4.3)
--
-- Un solo camino para dos flujos que comparten TODA la mecanica:
--   * RECUPERACION: lo pide el propio titular ("olvide mi contrasena").
--   * INVITACION:   lo emite el gobierno del tenant para dar de alta o
--                   devolver el acceso a alguien.
--
-- La regla que hace util a la tabla y que no es negociable: el
-- administrador NUNCA ve, fija ni recupera la contrasena de otra persona.
-- El token es el unico camino y el titular define su clave al canjearlo.
-- ---------------------------------------------------------------------
CREATE TABLE token_acceso (
    id_token        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_credencial   BIGINT      NOT NULL REFERENCES credencial_usuario (id_persona_rol),
    tipo            VARCHAR(15) NOT NULL,
    -- SHA-256 hex del token, nunca el token. Misma logica que una
    -- contrasena: quien lea esta tabla no puede usar lo que encuentre.
    hash_token      VARCHAR(64) NOT NULL,
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_en       TIMESTAMPTZ NOT NULL,
    -- Un solo uso: se sella DENTRO de la misma transaccion que cambia la
    -- clave. Si el cambio falla, el token sigue vivo; si el cambio entra,
    -- el token ya no vale ni aunque alguien lo repita.
    usado_en        TIMESTAMPTZ,
    -- Emitir un token nuevo mata el anterior. Se marca en vez de borrar
    -- para que la auditoria pueda contar cuantos se emitieron.
    invalidado_en   TIMESTAMPTZ,
    -- Quien lo emitio. NULL = lo pidio el propio titular.
    creado_por      BIGINT,
    motivo          VARCHAR(300),
    CONSTRAINT ck_token_acceso_tipo CHECK (tipo IN ('RECUPERACION', 'INVITACION')),
    CONSTRAINT ck_token_acceso_vigencia CHECK (expira_en > creado_en)
);

COMMENT ON TABLE token_acceso IS
    'Token de un solo uso para recuperacion e invitacion (Plan S0 §4.3). '
    'Se guarda el HASH, nunca el token. Vigencia corta y un solo token '
    'activo por credencial.';

-- "Un token activo por credencial" (§4.3) dejado de invariante y no de
-- buena intencion: dos vivos a la vez permitirian que un token viejo
-- filtrado siguiera sirviendo despues de emitir el bueno.
CREATE UNIQUE INDEX uq_token_acceso_activo
    ON token_acceso (id_credencial)
    WHERE usado_en IS NULL AND invalidado_en IS NULL;

-- La consulta del canje: por hash, y siempre acotada al tenant.
CREATE INDEX ix_token_acceso_hash ON token_acceso (hash_token);
-- Purga por retencion, igual que intento_acceso.
CREATE INDEX ix_token_acceso_purga ON token_acceso (creado_en);

-- ---------------------------------------------------------------------
-- V31.3  credencial_password — historial de hashes (§4.5)
--
-- Impide reutilizar de inmediato la contrasena que se acaba de abandonar,
-- que es el patron real: "cambiala" -> se pone la misma de siempre.
--
-- Guarda HASHES, no contrasenas: comparar una candidata contra el
-- historial se hace verificandola contra cada hash, igual que un login.
-- ---------------------------------------------------------------------
CREATE TABLE credencial_password (
    id_password     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    id_credencial   BIGINT       NOT NULL REFERENCES credencial_usuario (id_persona_rol),
    contrasena_hash VARCHAR(255) NOT NULL,
    algoritmo_hash  VARCHAR(20)  NOT NULL DEFAULT 'pbkdf2',
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE credencial_password IS
    'Ultimos hashes de cada credencial (Plan S0 §4.5). Solo para impedir '
    'reutilizacion inmediata; no es un almacen de contrasenas anteriores '
    'porque un hash no se puede volver a leer.';

-- La consulta es siempre "los N ultimos de esta credencial".
CREATE INDEX ix_credencial_password_ultimos
    ON credencial_password (id_credencial, creado_en DESC);
