-- =====================================================================
-- V37: segundo factor TOTP, elevación y el invariante de administrador
--      OPERATIVO (Bloque 6, D-S0-22…D-S0-37).
--
-- Diseño completo: docs/ai/plan-s0-6-mfa-y-break-glass.md.
-- V38 (concesión técnica de recuperación) NO entra aquí y no está
-- aprobada: esta migración no crea ninguna cuenta ni emite PLATFORM_ADMIN.
--
-- ORDEN INTERNO QUE IMPORTA: el backfill de `debe_enrolar_mfa` (§1) va
-- ANTES de sustituir el trigger (§7). Al revés, la propia migración se
-- bloquearía a sí misma: marcar al administrador como "debe enrolar" lo
-- deja no-operativo, y el trigger nuevo no admitiría el UPDATE.
-- =====================================================================

-- ---------------------------------------------------------------------
-- V37.1  Enrolamiento obligatorio para el gobierno (D-S0-25)
-- ---------------------------------------------------------------------
ALTER TABLE credencial_usuario
    ADD COLUMN debe_enrolar_mfa BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN credencial_usuario.debe_enrolar_mfa IS
    'D-S0-25: la sesión existe pero queda CAPADA hasta enrolar el segundo '
    'factor. Gemelo de debe_cambiar_contrasena. Sin esto, exigir MFA a los '
    'administradores el día del despliegue seria una caida de gobierno '
    'autoinfligida: no tienen factor todavia.';

-- Todo administrador vigente queda obligado. No hay ventana en la que un
-- TENANT_ADMIN este sin MFA y sin obligacion de ponerselo.
UPDATE credencial_usuario cu
   SET debe_enrolar_mfa = TRUE
  FROM usuario_organizacion uo
 WHERE uo.id_usuario = cu.id_persona_rol
   AND uo.organizacion_id = cu.organizacion_id
   AND uo.estado = 'A'
   AND uo.rol = 'TENANT_ADMIN';

-- ---------------------------------------------------------------------
-- V37.2  ¿Esta organizacion ya cruzo a MFA de gobierno?
--
-- Es la pieza que hace al invariante de §7 SEGURO EN EL ARRANQUE. Un
-- trigger que exija "siempre >= 1 administrador operativo" deja el
-- sistema tapiado entre el despliegue y el primer enrolamiento: en ese
-- rato NO hay ninguno, porque el backfill de arriba acaba de marcarlos a
-- todos. Y no se puede distinguir "ya estaba roto" de "lo acabas de
-- romper" mirando solo el estado final, que es lo unico que ve un
-- trigger diferido.
--
-- La bandera resuelve esa ambiguedad sin heuristicas: mientras sea
-- FALSE rige la regla de V34 (basta una membresia activa); en cuanto el
-- primer administrador activa su factor pasa a TRUE —en la MISMA
-- transaccion— y desde entonces la organizacion no puede volver a
-- quedarse sin gobierno operativo.
-- ---------------------------------------------------------------------
ALTER TABLE organizacion
    ADD COLUMN mfa_gobierno_exigido BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN organizacion.mfa_gobierno_exigido IS
    'TRUE desde que el primer TENANT_ADMIN activa su factor. Solo la '
    'enciende MfaServiceImpl.confirmar, y nunca se apaga: una organizacion '
    'no des-cruza el umbral de MFA.';

-- ---------------------------------------------------------------------
-- V37.3  El factor
-- ---------------------------------------------------------------------
CREATE TABLE factor_autenticacion (
    id_factor       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_credencial   BIGINT      NOT NULL REFERENCES credencial_usuario (id_persona_rol),
    tipo            VARCHAR(10) NOT NULL DEFAULT 'TOTP',

    -- Cifrado REVERSIBLE, no hash: un TOTP hay que poder recalcularlo.
    -- Esa es la diferencia con una contrasena, y la razon por la que la
    -- clave NO puede vivir en esta base — si vive aqui, cifrar no protege
    -- de nada. El tag de GCM va integrado en el criptograma.
    secreto_cifrado BYTEA       NOT NULL,
    nonce           BYTEA       NOT NULL,
    version_clave   SMALLINT    NOT NULL DEFAULT 1,

    -- Explicitos a proposito: si algun dia cambian, se ve en los datos.
    algoritmo       VARCHAR(20) NOT NULL DEFAULT 'HmacSHA1',
    digitos         SMALLINT    NOT NULL DEFAULT 6,
    periodo         SMALLINT    NOT NULL DEFAULT 30,

    estado          VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE',

    -- Anti-replay (D-S0-31). El paso consumido; la validacion es un
    -- UPDATE condicional sobre esta columna, no una comparacion leida
    -- antes: dos peticiones simultaneas aceptarian el mismo codigo.
    ultimo_paso     BIGINT,

    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    activado_en     TIMESTAMPTZ,
    revocado_en     TIMESTAMPTZ,
    ultimo_uso_en   TIMESTAMPTZ,

    CONSTRAINT ck_factor_tipo   CHECK (tipo IN ('TOTP')),
    CONSTRAINT ck_factor_estado CHECK (estado IN ('PENDIENTE', 'ACTIVO', 'REVOCADO')),
    CONSTRAINT ck_factor_digitos CHECK (digitos BETWEEN 6 AND 8),
    CONSTRAINT ck_factor_periodo CHECK (periodo > 0)
);

-- Un solo factor ACTIVO por credencial. Parcial: los PENDIENTE caducados
-- y los REVOCADO son historia y pueden acumularse.
CREATE UNIQUE INDEX uq_factor_activo_por_credencial
    ON factor_autenticacion (id_credencial) WHERE estado = 'ACTIVO';
CREATE INDEX ix_factor_credencial ON factor_autenticacion (id_credencial, estado);
CREATE INDEX ix_factor_organizacion ON factor_autenticacion (organizacion_id);

COMMENT ON COLUMN factor_autenticacion.ultimo_paso IS
    'D-S0-31: ultimo time-step consumido. Solo se admiten los pasos t y '
    't-1 (D-S0-36): aceptar t+1 dejaria usar un codigo antes de su ventana '
    'y, al sellarlo aqui, tumbaria el codigo actual y el siguiente.';

-- ---------------------------------------------------------------------
-- V37.4  Codigos de respaldo (D-S0-24)
--
-- El IDENTIFICADOR publico es lo que hace viable el hash lento: sin el
-- habria que probar el codigo contra las 8 filas —ocho derivaciones por
-- intento y una palanca de denegacion de servicio regalada—, que es lo
-- que llevaba a usar SHA-256 simple. Con identificador se verifica UNA.
-- ---------------------------------------------------------------------
CREATE TABLE codigo_respaldo_mfa (
    id_codigo       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Lo lleva aunque cuelgue de un factor que ya vive en un tenant: la regla
    -- del proyecto es que TODA fila privada carga el discriminador, y un gate
    -- rompe el build si alguna no lo hace. Ahorrarselo en las hijas es como
    -- se cuela una consulta que cruza corredoras.
    organizacion_id BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_factor       BIGINT      NOT NULL REFERENCES factor_autenticacion (id_factor),
    identificador VARCHAR(8)   NOT NULL,
    -- PBKDF2 con sal, formato de PasswordHasher. El secreto son 80 bits
    -- aleatorios, asi que el trabajo lento aqui es holgura, no necesidad.
    hash_secreto  VARCHAR(255) NOT NULL,
    creado_en     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    usado_en      TIMESTAMPTZ,
    CONSTRAINT uq_codigo_respaldo_identificador UNIQUE (id_factor, identificador)
);

CREATE INDEX ix_codigo_respaldo_factor ON codigo_respaldo_mfa (id_factor) WHERE usado_en IS NULL;
CREATE INDEX ix_codigo_respaldo_organizacion ON codigo_respaldo_mfa (organizacion_id);

-- ---------------------------------------------------------------------
-- V37.5  token_acceso admite el desafio y la elevacion (D-S0-23)
--
-- CONDICION DE LA REUTILIZACION: el tipo es OBLIGATORIO en toda emision,
-- busqueda, consumo e invalidacion. Un DESAFIO_MFA no puede canjearse
-- jamas como RECUPERACION, ni al reves. Si esa comprobacion faltara,
-- compartir tabla seria mala idea.
-- ---------------------------------------------------------------------
ALTER TABLE token_acceso
    ADD COLUMN intentos SMALLINT   NOT NULL DEFAULT 0,
    ADD COLUMN estado   VARCHAR(12) NOT NULL DEFAULT 'VIGENTE';

ALTER TABLE token_acceso DROP CONSTRAINT ck_token_acceso_tipo;
ALTER TABLE token_acceso ADD CONSTRAINT ck_token_acceso_tipo
    CHECK (tipo IN ('RECUPERACION', 'INVITACION', 'DESAFIO_MFA', 'ELEVACION'));
ALTER TABLE token_acceso ADD CONSTRAINT ck_token_acceso_estado
    CHECK (estado IN ('VIGENTE', 'CONSUMIDO', 'REVOCADO', 'AGOTADO'));

COMMENT ON TABLE token_acceso IS
    'Secretos de un solo uso, hasheados: recuperacion e invitacion de '
    'contrasena (V31), desafio de segundo factor y elevacion (V37). NINGUNA '
    'operacion puede resolverse sin fijar el TIPO — es lo que impide canjear '
    'un desafio de MFA como si fuera una recuperacion de contrasena.';

COMMENT ON COLUMN token_acceso.intentos IS
    'D-S0-32: intentos fallidos contra ESTE token. Es solo uno de los tres '
    'controles; el acumulado por cuenta vive en intento_acceso y no se '
    'reinicia al emitir un token nuevo.';

-- El unico parcial de V31 decia "un token vivo por credencial", sin mirar el
-- tipo. Con cuatro tipos eso es demasiado: emitir un desafio de MFA mataria
-- una recuperacion de contrasena pendiente —y al reves—, que son flujos
-- independientes. El invariante correcto es el mismo, acotado: **uno vivo por
-- credencial Y TIPO**. Es la misma proteccion (un token viejo filtrado deja de
-- servir en cuanto se emite el bueno de SU tipo) sin acoplar flujos ajenos.
DROP INDEX uq_token_acceso_activo;
CREATE UNIQUE INDEX uq_token_acceso_activo
    ON token_acceso (id_credencial, tipo)
    WHERE usado_en IS NULL AND invalidado_en IS NULL;

-- ---------------------------------------------------------------------
-- V37.6  Conteo acumulado por cuenta (D-S0-32)
-- ---------------------------------------------------------------------
ALTER TABLE intento_acceso DROP CONSTRAINT ck_intento_clave_tipo;
ALTER TABLE intento_acceso ADD CONSTRAINT ck_intento_clave_tipo
    CHECK (clave_tipo IN ('CUENTA', 'IP', 'MFA_CUENTA'));

COMMENT ON CONSTRAINT ck_intento_clave_tipo ON intento_acceso IS
    'MFA_CUENTA (V37) cuenta los fallos de segundo factor por cuenta. Va '
    'aparte de CUENTA porque un fallo de contrasena y uno de codigo no '
    'deben compartir cupo: si lo hicieran, fallar el TOTP acercaria al '
    'bloqueo del login y al reves.';

-- ---------------------------------------------------------------------
-- V37.7  Tipos de evento (§11 del diseño)
-- ---------------------------------------------------------------------
ALTER TABLE evento_seguridad DROP CONSTRAINT ck_evento_seguridad_tipo;
ALTER TABLE evento_seguridad ADD CONSTRAINT ck_evento_seguridad_tipo CHECK (tipo IN (
    'LOGIN_OK', 'LOGIN_FALLIDO', 'LOGIN_BLOQUEADO_429',
    'LOGOUT', 'SESIONES_INVALIDADAS',
    'CUENTA_BLOQUEADA', 'CUENTA_DESBLOQUEADA',
    'MFA_OK', 'MFA_FALLIDO',
    'PASSWORD_CAMBIADA', 'PASSWORD_RESTABLECIDA',
    'INVITACION_EMITIDA', 'INVITACION_CANJEADA',
    'RECUPERACION_EMITIDA', 'RECUPERACION_CANJEADA',
    'CUENTA_ACTIVADA', 'CUENTA_DESACTIVADA',
    'ROL_OTORGADO', 'ROL_REVOCADO',
    'ACCESO_TENANT_CONCEDIDO', 'ACCESO_TENANT_USADO',
    'BREAK_GLASS_ACTIVADO',
    -- V37 (se emiten)
    'MFA_ACTIVADO', 'MFA_REVOCADO', 'MFA_CODIGOS_REGENERADOS',
    'MFA_CODIGO_RESPALDO_USADO', 'ELEVACION_EMITIDA', 'ELEVACION_FALLIDA',
    -- V38 (previstos, SIN emisor todavia: misma politica que V30)
    'RECUPERACION_EMERGENCIA_EMITIDA', 'RECUPERACION_EMERGENCIA_APLICADA',
    'RECUPERACION_EMERGENCIA_CADUCADA', 'CUSTODIO_APROBACION_FALLIDA'
));

-- ---------------------------------------------------------------------
-- V37.8  El invariante pasa de "hay administrador" a "hay administrador
--        OPERATIVO" (D-S0-37)
--
-- La regla de V34 contaba membresias. No basta: una cuenta suspendida,
-- sin factor o con un cambio obligatorio pendiente figura en el recuento
-- y NO puede gobernar.
--
-- OPERATIVO = membresia TENANT_ADMIN activa
--           + credencial activa
--           + factor ACTIVO
--           + sin debe_cambiar_contrasena
--           + sin debe_enrolar_mfa
--
-- Sigue DEFERRABLE INITIALLY DEFERRED por la misma razon que en V34: un
-- relevo pasa por un instante intermedio invalido y debe juzgarse por su
-- RESULTADO. Con esto siguen siendo legales, en cualquier orden:
--   * el primer enrolamiento (la bandera de §2 aun es FALSE);
--   * reemplazar un factor: revocar el viejo y activar el nuevo;
--   * relevar administradores: degradar a uno y promover a otro.
-- Y deja de serlo dejar a la organizacion sin nadie capaz de gobernar.
-- ---------------------------------------------------------------------
DROP TRIGGER tg_usuario_org_exige_administrador ON usuario_organizacion;
DROP FUNCTION exigir_administrador_de_organizacion();

CREATE FUNCTION exigir_administrador_operativo() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    org BIGINT := COALESCE(NEW.organizacion_id, OLD.organizacion_id);
    exige_mfa BOOLEAN;
BEGIN
    IF org IS NULL THEN
        RETURN NULL;
    END IF;

    -- Una organizacion SIN cuentas activas no necesita gobierno: o esta
    -- naciendo o se esta desmontando entera. Exigirselo impediria las dos
    -- cosas, y en particular retirar un tenant de prueba.
    IF NOT EXISTS (
        SELECT 1 FROM usuario_organizacion
         WHERE organizacion_id = org AND estado = 'A'
    ) THEN
        RETURN NULL;
    END IF;

    SELECT o.mfa_gobierno_exigido INTO exige_mfa
      FROM organizacion o WHERE o.id_organizacion = org;

    IF NOT COALESCE(exige_mfa, FALSE) THEN
        -- Antes del primer enrolamiento rige la regla de V34: basta con
        -- que exista gobierno, aunque todavia no tenga segundo factor.
        IF NOT EXISTS (
            SELECT 1 FROM usuario_organizacion
             WHERE organizacion_id = org AND estado = 'A' AND rol = 'TENANT_ADMIN'
        ) THEN
            RAISE EXCEPTION 'Una organizacion no puede quedarse sin administrador '
                            '(organizacion %)', org
                  USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM usuario_organizacion uo
          JOIN credencial_usuario cu
            ON cu.id_persona_rol = uo.id_usuario
           AND cu.organizacion_id = uo.organizacion_id
          JOIN factor_autenticacion fa
            ON fa.id_credencial = cu.id_persona_rol
           AND fa.estado = 'ACTIVO'
         WHERE uo.organizacion_id = org
           AND uo.estado = 'A'
           AND uo.rol = 'TENANT_ADMIN'
           AND cu.estado_administrativo = 'A'
           AND NOT cu.debe_cambiar_contrasena
           AND NOT cu.debe_enrolar_mfa
    ) THEN
        RAISE EXCEPTION 'Una organizacion no puede quedarse sin administrador '
                        'operativo (organizacion %)', org
              USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NULL;
END $$;

COMMENT ON FUNCTION exigir_administrador_operativo() IS
    'D-S0-37: red de seguridad del invariante ">= 1 TENANT_ADMIN OPERATIVO". '
    'Se evalua al COMMIT, asi que un relevo o un reemplazo de factor son '
    'validos en cualquier orden mientras el resultado final tenga gobierno. '
    'Antes del primer enrolamiento (organizacion.mfa_gobierno_exigido = FALSE) '
    'se conforma con la regla de V34, para no tapiar el sistema justo cuando '
    'nadie ha podido enrolar todavia.';

CREATE CONSTRAINT TRIGGER tg_usuario_org_exige_administrador
    AFTER INSERT OR UPDATE OR DELETE ON usuario_organizacion
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION exigir_administrador_operativo();

-- Revocar un factor tambien puede dejar sin gobierno. No se vigila el
-- INSERT: crear un factor nunca reduce el recuento, y el primer
-- enrolamiento no debe disparar nada.
CREATE CONSTRAINT TRIGGER tg_factor_exige_administrador
    AFTER UPDATE OR DELETE ON factor_autenticacion
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION exigir_administrador_operativo();

-- Suspender la cuenta o encender un cambio obligatorio degradan igual.
-- El WHEN es lo que mantiene esto fuera del camino caliente: el logout
-- escribe `sesiones_invalidas_desde` en cada salida y NO debe disparar
-- una consulta agregada.
CREATE CONSTRAINT TRIGGER tg_credencial_exige_administrador
    AFTER UPDATE ON credencial_usuario
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    WHEN (OLD.estado_administrativo IS DISTINCT FROM NEW.estado_administrativo
       OR OLD.debe_cambiar_contrasena IS DISTINCT FROM NEW.debe_cambiar_contrasena
       OR OLD.debe_enrolar_mfa      IS DISTINCT FROM NEW.debe_enrolar_mfa)
    EXECUTE FUNCTION exigir_administrador_operativo();
