-- =====================================================================
-- V38: concesion tecnica de recuperacion — el NIVEL 3, para cuando una
--      organizacion se queda sin ningun administrador operativo.
--
-- Diseño: docs/ai/plan-s0-6-mfa-y-break-glass.md §9.
-- Procedimiento: backend-spring/operacion/custodios-y-recuperacion-de-emergencia.md
--
-- LO QUE ESTO **NO** CREA, y no es un olvido:
--   * ninguna cuenta, ningun rol, ningun PLATFORM_ADMIN;
--   * ninguna tabla de custodios (D-S0-51): se verifican contra dos hashes
--     en CONFIGURACION, fuera de esta base. Un hash de custodio guardado
--     dentro de la base que este mecanismo viene a rescatar seria una llave
--     dentro de la casa;
--   * ninguna sesion: la concesion no produce token. No hay donde entrar.
--
-- La concesion es un PERMISO: temporal, de alcance fijo y de un solo uso
-- por accion. Repone gobierno; no gobierna.
-- =====================================================================

-- ---------------------------------------------------------------------
-- V38.1  La concesion
-- ---------------------------------------------------------------------
CREATE TABLE concesion_recuperacion (
    id_concesion       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Alcance FIJADO al emitir e inmutable: un tenant, una persona. No hay
    -- forma de ampliarlo despues, ni siquiera con las dos aprobaciones.
    organizacion_id    BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_persona_objetivo BIGINT     NOT NULL REFERENCES persona (id_persona),

    -- LAS TRES IDENTIDADES (D-S0-52). El operador va aqui y no solo en la
    -- consola: «quien ejecuta no custodia» es inaplicable si la identidad de
    -- quien ejecuta no se conserva junto a las otras dos. Un log de texto se
    -- reescribe; esta fila, no.
    operador           VARCHAR(60) NOT NULL,
    custodio_a         VARCHAR(60) NOT NULL,
    custodio_b         VARCHAR(60) NOT NULL,

    -- SHA-256 del secreto entregado. Simple y suficiente *porque* la entropia
    -- esta fijada en 256 bits: no hay diccionario que recorrer.
    hash_secreto       VARCHAR(64) NOT NULL,

    motivo             VARCHAR(300) NOT NULL,

    estado             VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE',
    max_acciones       SMALLINT    NOT NULL DEFAULT 3,
    acciones_consumidas SMALLINT   NOT NULL DEFAULT 0,

    creado_en          TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Se rellena al completarse la SEGUNDA aprobacion: antes no hay ventana
    -- que contar, porque la concesion todavia no autoriza nada.
    vigente_desde      TIMESTAMPTZ,
    expira_en          TIMESTAMPTZ,
    cerrada_en         TIMESTAMPTZ,
    cierre_motivo      VARCHAR(60),
    prorrogas          SMALLINT    NOT NULL DEFAULT 0,

    CONSTRAINT ck_concesion_estado CHECK (estado IN
        ('PENDIENTE', 'VIGENTE', 'CERRADA', 'CADUCADA', 'AGOTADA')),

    -- Las tres desigualdades de D-S0-52. Con identificadores reales —no
    -- etiquetas de ranura «A»/«B»— esto es una comprobacion de verdad.
    CONSTRAINT ck_concesion_custodios_distintos CHECK (custodio_a <> custodio_b),
    CONSTRAINT ck_concesion_operador_no_es_a    CHECK (operador <> custodio_a),
    CONSTRAINT ck_concesion_operador_no_es_b    CHECK (operador <> custodio_b),

    CONSTRAINT ck_concesion_acciones CHECK (
        acciones_consumidas >= 0
        AND max_acciones BETWEEN 1 AND 3
        AND acciones_consumidas <= max_acciones),

    -- Una sola prorroga, y solo con aprobacion dual nueva (§9.8).
    CONSTRAINT ck_concesion_prorrogas CHECK (prorrogas BETWEEN 0 AND 1),

    -- Vigente exige ventana. Sin esto, una fila VIGENTE sin `expira_en`
    -- seria una concesion sin caducidad, que es justo lo que no puede haber.
    CONSTRAINT ck_concesion_ventana CHECK (
        (estado = 'PENDIENTE' AND vigente_desde IS NULL AND expira_en IS NULL)
        OR (estado <> 'PENDIENTE' AND vigente_desde IS NOT NULL AND expira_en IS NOT NULL))
);

-- UNA concesion viva por organizacion. Dos a la vez multiplicarian la
-- superficie sin ninguna necesidad: la emergencia es de una persona.
CREATE UNIQUE INDEX uq_concesion_viva_por_organizacion
    ON concesion_recuperacion (organizacion_id)
    WHERE estado IN ('PENDIENTE', 'VIGENTE');

CREATE INDEX ix_concesion_estado ON concesion_recuperacion (estado, expira_en);

COMMENT ON TABLE concesion_recuperacion IS
    'Nivel 3 (§9): permiso temporal para devolver el gobierno de UN tenant a '
    'UNA persona. No es cuenta, no es rol y no emite sesion. Guarda las TRES '
    'identidades que intervinieron —dos custodios y el operador— y la base '
    'exige que sean distintas.';

COMMENT ON COLUMN concesion_recuperacion.operador IS
    'D-S0-52: quien ejecuto la herramienta. Va en la fila y no solo en la '
    'consola porque la regla "quien ejecuta no custodia" no se puede aplicar '
    'sobre algo que no se conserva.';

COMMENT ON COLUMN concesion_recuperacion.hash_secreto IS
    'SHA-256 del secreto de 256 bits. El secreto se muestra UNA vez, al '
    'completarse la segunda aprobacion, y no se guarda en ningun sitio.';

-- ---------------------------------------------------------------------
-- V38.2  Las dos aprobaciones — estructurales, no un CHECK de textos
--
-- La version descartada confiaba en CHECK (custodio_a <> custodio_b): eso
-- solo compara dos cadenas de UNA fila, y un operador que escriba dos
-- nombres distintos pasa. Aqui cada aprobacion es su propia fila, verificada
-- contra su propio hash de configuracion, y el UNIQUE impide que una sola
-- persona cubra las dos partes.
--
-- Lo que esto prueba, sin adornos: que se presentaron DOS SECRETOS EN MANOS
-- SEPARADAS. Ningun control de software prueba que habia dos personas.
-- ---------------------------------------------------------------------
CREATE TABLE aprobacion_recuperacion (
    id_aprobacion   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Lo lleva aunque cuelgue de una concesion que ya vive en un tenant: la
    -- regla del proyecto es que TODA fila privada carga el discriminador, y un
    -- gate rompe el build si alguna no lo hace. Ahorrarselo en las hijas es
    -- como se cuela una consulta que cruza corredoras.
    organizacion_id BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_concesion    BIGINT      NOT NULL REFERENCES concesion_recuperacion (id_concesion),
    -- Identificador de configuracion, NO una clave ajena: no hay tabla de
    -- custodios (D-S0-51) y este texto es lo unico que la base debe saber.
    identificador_custodio VARCHAR(60) NOT NULL,
    aprobado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    orden           SMALLINT    NOT NULL,

    CONSTRAINT uq_aprobacion_custodio UNIQUE (id_concesion, identificador_custodio),
    CONSTRAINT uq_aprobacion_orden    UNIQUE (id_concesion, orden),
    CONSTRAINT ck_aprobacion_orden    CHECK (orden IN (1, 2))
);

-- NO hay `hash_evidencia`: guardar material derivado de un secreto vivo en
-- una tabla legible regala un objetivo de fuerza bruta a cambio de nada. La
-- verificacion ya ocurrio contra el hash de configuracion; lo que prueba la
-- aprobacion es la existencia de la fila.
COMMENT ON TABLE aprobacion_recuperacion IS
    'Doble aprobacion ESTRUCTURAL (§9.3): dos filas de custodios distintos. '
    'La concesion no pasa a VIGENTE hasta que existen las dos.';

-- ---------------------------------------------------------------------
-- V38.3  Las acciones — una vez cada una, y solo estas tres
-- ---------------------------------------------------------------------
CREATE TABLE accion_recuperacion (
    id_accion    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Mismo motivo que en aprobacion_recuperacion.
    organizacion_id BIGINT   NOT NULL REFERENCES organizacion (id_organizacion),
    id_concesion BIGINT      NOT NULL REFERENCES concesion_recuperacion (id_concesion),
    tipo         VARCHAR(24) NOT NULL,
    aplicada_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- APLICADA = cambio algo; SIN_EFECTO = el estado ya lo cumplia. Las dos
    -- consumen capacidad: lo que se gasta es el intento, no el cambio.
    resultado    VARCHAR(12) NOT NULL,

    CONSTRAINT ck_accion_tipo CHECK (tipo IN
        ('REACTIVAR_CUENTA', 'REVOCAR_MFA', 'REPONER_MEMBRESIA')),
    CONSTRAINT ck_accion_resultado CHECK (resultado IN ('APLICADA', 'SIN_EFECTO')),

    -- Sin este UNIQUE, `max_acciones = 3` deja ejecutar TRES VECES LA MISMA.
    CONSTRAINT uq_accion_por_concesion UNIQUE (id_concesion, tipo)
);

COMMENT ON TABLE accion_recuperacion IS
    'Las tres unicas cosas que una concesion puede hacer, como maximo una vez '
    'cada una y solo sobre id_persona_objetivo. No puede leer datos '
    'comerciales, crear personas ni fijar contrasenas.';
