-- =====================================================================
-- Recuperacion de disponibilidad tras terminar un contrato (Bloque 7.3.2).
--
-- LA REGLA QUE SE CONSERVA: finalizar o rescindir NO devuelve el inmueble al
-- mercado. `F` y `S` dejan la propiedad ALQUILADA y crean una tarea de
-- revision; una persona decide despues, sabiendo como se entrego el local.
-- Esta migracion no cambia eso: le da a esa decision una operacion propia.
--
-- POR QUE UNA TABLA Y NO SOLO `historial_estado`. La transicion de
-- disponibilidad ya se audita ahi (entidad, estado anterior, estado nuevo,
-- actor, rol, fecha, motivo), y se sigue auditando. Lo que `historial_estado`
-- no puede expresar es el CONTRATO ORIGEN: no tiene columna para una entidad
-- relacionada, y meter el id dentro del texto del motivo no es consultable.
-- Esta tabla responde "por que volvio al mercado este local" enlazando el
-- contrato terminado con la decision.
--
-- `R` (Reservado) NO es un resultado posible aqui: reservar pertenece a otra
-- causa de negocio y se resolvera en el punto de estados sin productor.
-- =====================================================================

CREATE TABLE revision_disponibilidad (
    id_revision             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id         BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    id_contrato_alquiler    BIGINT       NOT NULL,
    id_propiedad            BIGINT       NOT NULL,
    disponibilidad_anterior VARCHAR(1)   NOT NULL,
    disponibilidad_nueva    VARCHAR(1)   NOT NULL,
    motivo                  VARCHAR(300) NOT NULL,
    id_actor                BIGINT,
    tipo_rol_actor          VARCHAR(20),
    fecha_revision          DATE         NOT NULL,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Solo dos desenlaces en este tramo: vuelve al mercado o se retira.
    CONSTRAINT ck_revision_destino CHECK (disponibilidad_nueva IN ('D', 'T')),
    -- Se revisa un local OCUPADO; si no estaba alquilado no habia nada que
    -- recuperar y la revision no tiene sentido.
    CONSTRAINT ck_revision_origen CHECK (disponibilidad_anterior = 'A'),
    CONSTRAINT ck_revision_motivo CHECK (btrim(motivo) <> ''),

    -- Un contrato terminado se revisa UNA vez. Ademas del invariante de
    -- negocio, da idempotencia: un segundo intento choca aqui.
    CONSTRAINT uq_revision_contrato UNIQUE (id_contrato_alquiler),
    CONSTRAINT uq_revision_org UNIQUE (organizacion_id, id_revision),
    CONSTRAINT fk_revision_contrato_org FOREIGN KEY (organizacion_id, id_contrato_alquiler)
        REFERENCES contrato_alquiler (organizacion_id, id_contrato_alquiler),
    CONSTRAINT fk_revision_propiedad_org FOREIGN KEY (organizacion_id, id_propiedad)
        REFERENCES propiedad (organizacion_id, id_propiedad)
);

CREATE INDEX ix_revision_propiedad
    ON revision_disponibilidad (organizacion_id, id_propiedad, fecha_revision DESC);

-- ---------------------------------------------------------------------
-- OCUPACION: un inmueble no puede tener dos contratos vivos a la vez.
--
-- Es el invariante que hace imposible la "ventana falsa de disponibilidad" de
-- la renovacion: al renovar, el anterior pasa a `R` y el sucesor nace `D`, asi
-- que solo uno esta vivo. Sin esto, una revision del contrato ANTERIOR podria
-- devolver al mercado un local que el sucesor sigue ocupando.
--
-- La comprobacion de negocio vive en el service y da el mensaje; este indice
-- es el guardian que sobrevive a una carrera entre dos peticiones.
-- Verificado antes de crearlo: 0 propiedades con mas de un contrato en D/V.
-- ---------------------------------------------------------------------
CREATE UNIQUE INDEX uq_contrato_vivo_por_propiedad
    ON contrato_alquiler (organizacion_id, id_propiedad)
    WHERE estado_contrato IN ('D', 'V');

COMMENT ON TABLE revision_disponibilidad IS
    'Decision explicita que devuelve un inmueble al mercado (D) o lo retira (T) '
    'tras terminar o anular su contrato. Una por contrato.';
