-- =====================================================================
-- V47 - M1 del modelo universal: una propiedad puede tener varios titulares.
--
-- QUE PROBLEMA CIERRA
-- `propiedad.id_rol_propietario` es 1:1 NOT NULL: una propiedad, un dueno. Una
-- copropiedad, una sucesion o una sociedad conyugal no caben en el modelo, y en
-- el mercado inmobiliario son la norma, no la excepcion.
--
-- POR QUE UNA TABLA Y NO UNA SEGUNDA COLUMNA
-- Una copropiedad no es "dos duenos": es CUOTAS, un REPRESENTANTE con quien se
-- habla, y una VIGENCIA. Y una venta no borra al titular anterior: le pone
-- fecha de fin. Sin eso, el historico de propiedad se pierde en el primer
-- cierre, que es justo el dato que un sistema inmobiliario no puede perder.
--
-- QUE NO HACE ESTA MIGRACION
-- No toca `propiedad.id_rol_propietario`. Se conserva porque la entidad la
-- mapea y el cable la publica: quitarla rompería el arranque. Queda como la
-- proyeccion del titular representante, y el codigo migra modulo a modulo.
--
-- LAS DOS INVARIANTES, IMPUESTAS POR LA BASE
--   1. Las cuotas vigentes de una propiedad suman 100.
--   2. Exactamente un titular vigente es el representante.
-- La primera va en un CONSTRAINT TRIGGER DEFERRABLE: al insertar los tres
-- titulares de una copropiedad, los estados intermedios (50, luego 80) no
-- suman 100 y con una comprobacion inmediata seria imposible escribirlos.
-- =====================================================================

CREATE TABLE titularidad_propiedad (
    id_titularidad       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id      BIGINT        NOT NULL REFERENCES organizacion (id_organizacion),
    id_propiedad         BIGINT        NOT NULL REFERENCES propiedad (id_propiedad),

    -- Mismo patron que `propiedad`: FK compuesta contra persona_rol para que la
    -- base garantice que el rol referenciado es de tipo PROPIETARIO y no otro.
    id_rol_propietario   BIGINT        NOT NULL,
    tipo_rol_propietario VARCHAR(20)   NOT NULL DEFAULT 'PROPIETARIO',

    -- Porcentaje de la propiedad. 100 cuando hay un solo titular.
    cuota                NUMERIC(6,3)  NOT NULL,

    -- Con quien se habla. No tiene por que ser el de mayor cuota.
    es_representante     BOOLEAN       NOT NULL DEFAULT false,

    vigente_desde        DATE          NOT NULL,
    -- NULL = vigente. Una venta cierra unas titularidades y abre otras.
    vigente_hasta        DATE,
    motivo_fin           VARCHAR(200),

    fecha_creacion       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_actualizacion  TIMESTAMPTZ,

    CONSTRAINT ck_titularidad_cuota
        CHECK (cuota > 0 AND cuota <= 100),
    CONSTRAINT ck_titularidad_vigencia
        CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),
    CONSTRAINT ck_titularidad_motivo_fin
        CHECK ((vigente_hasta IS NULL AND motivo_fin IS NULL)
               OR vigente_hasta IS NOT NULL),
    CONSTRAINT ck_titularidad_tipo_rol
        CHECK (tipo_rol_propietario = 'PROPIETARIO'),
    CONSTRAINT fk_titularidad_propietario
        FOREIGN KEY (id_rol_propietario, tipo_rol_propietario)
        REFERENCES persona_rol (id_persona_rol, tipo_rol)
);

COMMENT ON TABLE titularidad_propiedad IS
    'Quien es dueno de que parte de una propiedad, y desde cuando. D-E4-1 M1.';

CREATE INDEX ix_titularidad_propiedad     ON titularidad_propiedad (id_propiedad);
CREATE INDEX ix_titularidad_organizacion  ON titularidad_propiedad (organizacion_id);
CREATE INDEX ix_titularidad_propietario   ON titularidad_propiedad (id_rol_propietario);

-- Un mismo titular no puede figurar dos veces vigente sobre la misma propiedad.
CREATE UNIQUE INDEX uq_titularidad_vigente
    ON titularidad_propiedad (id_propiedad, id_rol_propietario)
    WHERE vigente_hasta IS NULL;

-- Y exactamente uno de los vigentes es el representante.
CREATE UNIQUE INDEX uq_titularidad_representante
    ON titularidad_propiedad (id_propiedad)
    WHERE es_representante AND vigente_hasta IS NULL;

-- ---------------------------------------------------------------------
-- Invariante 1: las cuotas vigentes suman 100.
--
-- Diferida a fin de transaccion a proposito: escribir una copropiedad son
-- varias filas y los estados intermedios no suman 100. Lo que importa es que
-- al COMMIT sume.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION exigir_cuotas_completas()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    prop   bigint;
    total  numeric(9,3);
BEGIN
    prop := COALESCE(NEW.id_propiedad, OLD.id_propiedad);

    SELECT COALESCE(sum(cuota), 0) INTO total
      FROM titularidad_propiedad
     WHERE id_propiedad = prop
       AND vigente_hasta IS NULL;

    -- Cero titulares vigentes es un estado legitimo y transitorio: ocurre
    -- mientras se sustituye al dueno. Lo que no puede quedar es una suma
    -- distinta de 100 con titulares dentro.
    IF total <> 0 AND total <> 100 THEN
        RAISE EXCEPTION
            'Las cuotas vigentes de la propiedad % suman %, y tienen que sumar 100', prop, total
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER tg_titularidad_cuotas
    AFTER INSERT OR UPDATE OR DELETE ON titularidad_propiedad
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION exigir_cuotas_completas();

-- ---------------------------------------------------------------------
-- Backfill: el dueno actual pasa a ser titular unico al 100 % y representante.
--
-- No es una estimacion: `propiedad.id_rol_propietario` es NOT NULL, asi que
-- toda propiedad tiene exactamente un dueno declarado hoy. La fecha de inicio
-- es la de registro de la propiedad, que es la primera fecha en la que consta.
--
-- Idempotente: el NOT EXISTS deja cualquier reejecucion en 0 filas.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    insertadas bigint;
    huerfanas  bigint;
BEGIN
    INSERT INTO titularidad_propiedad
        (organizacion_id, id_propiedad, id_rol_propietario, cuota, es_representante, vigente_desde)
    SELECT p.organizacion_id,
           p.id_propiedad,
           p.id_rol_propietario,
           100,
           true,
           p.fecha_registro::date
      FROM propiedad p
     WHERE NOT EXISTS (
           SELECT 1 FROM titularidad_propiedad t
            WHERE t.id_propiedad = p.id_propiedad
              AND t.vigente_hasta IS NULL);

    GET DIAGNOSTICS insertadas = ROW_COUNT;

    SELECT count(*) INTO huerfanas
      FROM propiedad p
     WHERE NOT EXISTS (
           SELECT 1 FROM titularidad_propiedad t
            WHERE t.id_propiedad = p.id_propiedad
              AND t.vigente_hasta IS NULL);

    RAISE NOTICE 'V47: % titularidades creadas; % propiedades sin titular vigente', insertadas, huerfanas;

    IF huerfanas > 0 THEN
        RAISE EXCEPTION 'V47: quedan % propiedades sin titular vigente', huerfanas;
    END IF;
END $$;
