-- =====================================================================
-- V48 - M2 del modelo universal: los atributos del inmueble se gobiernan.
--
-- QUE PROBLEMA CIERRA
-- Hoy lo especifico de un subtipo vive en `detalle_local_comercial`: UNA TABLA
-- POR TIPO. Con siete tipos serian siete tablas, siete formularios y siete
-- ramas en cada consulta. Es exactamente lo que el motor de registro (D-E4-2)
-- viene a evitar.
--
-- POR QUE NO UN EAV LIBRE
-- El riesgo del modelo dinamico es que cada quien invente su clave: entonces ni
-- la busqueda ni el matcher pueden comparar dos propiedades, porque una dice
-- `dormitorios` y otra `habitaciones`. Aqui la clave viene de un CATALOGO que
-- declara tipo de dato, unidad, a que tipos de propiedad aplica y en cuales es
-- obligatoria. Sin fila en el catalogo no hay atributo.
--
-- QUE NO HACE ESTA MIGRACION
-- No borra `detalle_local_comercial` ni las columnas de subtipo de `propiedad`
-- (ambientes, frente, zonificacion...). Se conservan porque las entidades las
-- mapean; el codigo migra modulo a modulo y esta tabla ya queda poblada.
-- =====================================================================

-- ---------------------------------------------------------------------
-- El catalogo. `organizacion_id` NULL = atributo del sistema, comun a todos
-- los tenants; una organizacion puede anadir los suyos pero no borrar estos
-- ni redefinir su tipo.
-- ---------------------------------------------------------------------
CREATE TABLE catalogo_atributo (
    id_catalogo_atributo BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id      BIGINT       REFERENCES organizacion (id_organizacion),
    clave                VARCHAR(60)  NOT NULL,
    rotulo               VARCHAR(120) NOT NULL,
    tipo_dato            VARCHAR(10)  NOT NULL,
    unidad               VARCHAR(20),
    -- true = aplica a cualquier tipo de propiedad; si es false, manda la tabla
    -- catalogo_atributo_tipo.
    aplica_todos         BOOLEAN      NOT NULL DEFAULT false,
    del_sistema          BOOLEAN      NOT NULL DEFAULT false,
    orden                INTEGER      NOT NULL DEFAULT 100,
    activo               BOOLEAN      NOT NULL DEFAULT true,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_catalogo_atributo_tipo_dato
        CHECK (tipo_dato IN ('TEXTO', 'ENTERO', 'DECIMAL', 'BOOLEANO', 'LISTA')),
    CONSTRAINT ck_catalogo_atributo_sistema
        CHECK ((del_sistema AND organizacion_id IS NULL)
               OR (NOT del_sistema AND organizacion_id IS NOT NULL))
);

COMMENT ON TABLE catalogo_atributo IS
    'Que caracteristicas puede tener un inmueble, con su tipo y su unidad. D-E4-1 M2.';

-- Una clave por organizacion; los del sistema (org NULL) van aparte. `coalesce`
-- porque en un indice unico dos NULL no chocan entre si.
CREATE UNIQUE INDEX uq_catalogo_atributo_clave
    ON catalogo_atributo (COALESCE(organizacion_id, 0), clave);

-- A que tipos de propiedad aplica cada atributo, y en cuales es obligatorio.
CREATE TABLE catalogo_atributo_tipo (
    id_catalogo_atributo BIGINT      NOT NULL REFERENCES catalogo_atributo (id_catalogo_atributo) ON DELETE CASCADE,
    tipo_propiedad       VARCHAR(1)  NOT NULL,
    requerido            BOOLEAN     NOT NULL DEFAULT false,
    PRIMARY KEY (id_catalogo_atributo, tipo_propiedad),
    -- L local, O oficina, D departamento, C casa, T terreno, A almacen, X otro.
    CONSTRAINT ck_catalogo_atributo_tipo
        CHECK (tipo_propiedad IN ('L', 'O', 'D', 'C', 'T', 'A', 'X'))
);

-- ---------------------------------------------------------------------
-- El valor. Una fila por (propiedad, clave); el valor va en la columna del
-- tipo declarado y solo en una.
-- ---------------------------------------------------------------------
CREATE TABLE atributo_propiedad (
    id_atributo_propiedad BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id       BIGINT        NOT NULL REFERENCES organizacion (id_organizacion),
    id_propiedad          BIGINT        NOT NULL REFERENCES propiedad (id_propiedad),
    clave                 VARCHAR(60)   NOT NULL,
    valor_texto           TEXT,
    valor_numero          NUMERIC(14,4),
    valor_booleano        BOOLEAN,
    fecha_creacion        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_actualizacion   TIMESTAMPTZ,

    -- Exactamente un valor. Un atributo sin responder NO se guarda vacio: se
    -- omite, para que el matcher pueda distinguir "no aplica" de "no lo se".
    CONSTRAINT ck_atributo_un_valor
        CHECK (num_nonnulls(valor_texto, valor_numero, valor_booleano) = 1)
);

COMMENT ON TABLE atributo_propiedad IS
    'Valor de una caracteristica gobernada para una propiedad. D-E4-1 M2.';

CREATE UNIQUE INDEX uq_atributo_propiedad_clave
    ON atributo_propiedad (id_propiedad, clave);
CREATE INDEX ix_atributo_propiedad_organizacion
    ON atributo_propiedad (organizacion_id);
-- El indice que sostiene el matcher: "propiedades con dormitorios >= 3".
CREATE INDEX ix_atributo_propiedad_clave_numero
    ON atributo_propiedad (organizacion_id, clave, valor_numero)
    WHERE valor_numero IS NOT NULL;

-- La clave tiene que existir en el catalogo y aplicar al tipo de la propiedad.
-- Va en trigger y no en FK porque el catalogo admite claves del sistema
-- (organizacion NULL) y de la organizacion, y una FK no puede expresar esa
-- union.
CREATE OR REPLACE FUNCTION exigir_atributo_gobernado()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    cat        catalogo_atributo%ROWTYPE;
    tipo_prop  varchar(1);
BEGIN
    SELECT * INTO cat
      FROM catalogo_atributo
     WHERE clave = NEW.clave
       AND activo
       AND (organizacion_id IS NULL OR organizacion_id = NEW.organizacion_id)
     ORDER BY organizacion_id NULLS LAST
     LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El atributo "%" no esta en el catalogo', NEW.clave
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    SELECT tipo_inmueble INTO tipo_prop FROM propiedad WHERE id_propiedad = NEW.id_propiedad;

    IF NOT cat.aplica_todos
       AND NOT EXISTS (SELECT 1 FROM catalogo_atributo_tipo t
                        WHERE t.id_catalogo_atributo = cat.id_catalogo_atributo
                          AND t.tipo_propiedad = tipo_prop) THEN
        RAISE EXCEPTION 'El atributo "%" no aplica a una propiedad de tipo %', NEW.clave, tipo_prop
            USING ERRCODE = 'check_violation';
    END IF;

    -- El valor tiene que estar en la columna que corresponde a su tipo.
    IF cat.tipo_dato IN ('ENTERO', 'DECIMAL') AND NEW.valor_numero IS NULL THEN
        RAISE EXCEPTION 'El atributo "%" es numerico y llego sin valor_numero', NEW.clave
            USING ERRCODE = 'check_violation';
    ELSIF cat.tipo_dato = 'BOOLEANO' AND NEW.valor_booleano IS NULL THEN
        RAISE EXCEPTION 'El atributo "%" es booleano y llego sin valor_booleano', NEW.clave
            USING ERRCODE = 'check_violation';
    ELSIF cat.tipo_dato IN ('TEXTO', 'LISTA') AND NEW.valor_texto IS NULL THEN
        RAISE EXCEPTION 'El atributo "%" es de texto y llego sin valor_texto', NEW.clave
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER tg_atributo_gobernado
    BEFORE INSERT OR UPDATE ON atributo_propiedad
    FOR EACH ROW
    EXECUTE FUNCTION exigir_atributo_gobernado();

-- ---------------------------------------------------------------------
-- Semilla del catalogo del sistema. Es la misma lista que
-- `docs/ai/modelo/modelo-universal.js`, y de ella deriva el motor de registro
-- las preguntas de cada tipo: anadir un tipo de propiedad se hace aqui, no en
-- una pantalla.
-- ---------------------------------------------------------------------
INSERT INTO catalogo_atributo (organizacion_id, clave, rotulo, tipo_dato, unidad, aplica_todos, del_sistema, orden) VALUES
    (NULL, 'metraje_total',                'Metraje total',                'DECIMAL', 'm2',     true,  true, 10),
    (NULL, 'antiguedad_anios',             'Antiguedad',                   'ENTERO',  'anios',  true,  true, 20),
    (NULL, 'estacionamientos',             'Estacionamientos',             'ENTERO',  NULL,     true,  true, 30),
    (NULL, 'metraje_construido',           'Metraje construido',           'DECIMAL', 'm2',     false, true, 40),
    (NULL, 'ambientes',                    'Ambientes',                    'ENTERO',  NULL,     false, true, 50),
    (NULL, 'piso',                         'Piso',                         'TEXTO',   NULL,     false, true, 60),
    (NULL, 'cuota_mantenimiento',          'Cuota de mantenimiento',       'DECIMAL', 'moneda', false, true, 70),
    (NULL, 'dormitorios',                  'Dormitorios',                  'ENTERO',  NULL,     false, true, 80),
    (NULL, 'banos',                        'Banos',                        'DECIMAL', NULL,     false, true, 90),
    (NULL, 'amoblado',                     'Amoblado',                     'BOOLEANO',NULL,     false, true, 100),
    (NULL, 'pisos_edificacion',            'Pisos de la edificacion',      'ENTERO',  NULL,     false, true, 110),
    (NULL, 'frente',                       'Frente',                       'DECIMAL', 'm',      false, true, 120),
    (NULL, 'carga_electrica_kw',           'Carga electrica',              'DECIMAL', 'kW',     false, true, 130),
    (NULL, 'altura_libre',                 'Altura libre',                 'DECIMAL', 'm',      false, true, 140),
    (NULL, 'apto_licencia_funcionamiento', 'Apto para licencia',           'BOOLEANO',NULL,     false, true, 150),
    (NULL, 'rubro_permitido',              'Rubro permitido',              'TEXTO',   NULL,     false, true, 160),
    (NULL, 'zonificacion',                 'Zonificacion',                 'TEXTO',   NULL,     false, true, 170),
    (NULL, 'area_terreno',                 'Area de terreno',              'DECIMAL', 'm2',     false, true, 180),
    (NULL, 'servicios_disponibles',        'Servicios disponibles',        'LISTA',   NULL,     false, true, 190);

-- A que tipos aplica cada uno, y donde es obligatorio.
INSERT INTO catalogo_atributo_tipo (id_catalogo_atributo, tipo_propiedad, requerido)
SELECT c.id_catalogo_atributo, t.tipo, t.req
  FROM catalogo_atributo c
  JOIN (VALUES
        ('metraje_total',                'L', true),  ('metraje_total',                'O', true),
        ('metraje_total',                'D', true),  ('metraje_total',                'C', true),
        ('metraje_total',                'T', true),  ('metraje_total',                'A', true),
        ('metraje_total',                'X', true),

        ('metraje_construido', 'L', false), ('metraje_construido', 'O', false),
        ('metraje_construido', 'D', false), ('metraje_construido', 'C', false),
        ('metraje_construido', 'A', false),

        ('ambientes', 'L', false), ('ambientes', 'O', false), ('ambientes', 'D', false),
        ('ambientes', 'C', false), ('ambientes', 'A', false),

        ('piso', 'L', false), ('piso', 'O', false), ('piso', 'D', false),

        ('cuota_mantenimiento', 'L', false), ('cuota_mantenimiento', 'O', false),
        ('cuota_mantenimiento', 'D', false),

        ('dormitorios', 'D', true),  ('dormitorios', 'C', true),
        ('banos',       'D', false), ('banos',       'C', false),
        ('amoblado',    'D', false), ('amoblado',    'C', false),
        ('pisos_edificacion', 'C', false),

        ('frente', 'L', false), ('frente', 'T', false), ('frente', 'A', false),

        ('carga_electrica_kw', 'L', false), ('carga_electrica_kw', 'O', false),
        ('carga_electrica_kw', 'A', false),

        ('altura_libre', 'A', false), ('altura_libre', 'L', false),

        ('apto_licencia_funcionamiento', 'L', false),
        ('apto_licencia_funcionamiento', 'O', false),
        ('apto_licencia_funcionamiento', 'A', false),

        -- La oficina tambien lleva rubro: `detalle_local_comercial` es
        -- obligatoria para L **y O**, y en la base las dos oficinas existentes
        -- lo tienen relleno. Lo dijo el ensayo de la migracion, no el diseno.
        ('rubro_permitido', 'L', false), ('rubro_permitido', 'O', false),
        ('rubro_permitido', 'A', false),

        ('zonificacion', 'T', true),  ('zonificacion', 'L', false),
        ('zonificacion', 'A', false), ('zonificacion', 'C', false),

        ('area_terreno', 'T', false), ('area_terreno', 'C', false), ('area_terreno', 'A', false),

        ('servicios_disponibles', 'T', false)
       ) AS t(clave, tipo, req) ON t.clave = c.clave
 WHERE c.del_sistema;

-- ---------------------------------------------------------------------
-- Backfill: lo que ya esta escrito en columnas pasa a ser atributo.
--
-- No se inventa nada: cada INSERT copia una columna que ya tiene valor. Las
-- columnas de origen SE CONSERVAN hasta que el codigo deje de leerlas.
-- Idempotente por el ON CONFLICT.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    total bigint;
BEGIN
    -- Numericos de `propiedad`.
    INSERT INTO atributo_propiedad (organizacion_id, id_propiedad, clave, valor_numero)
    SELECT p.organizacion_id, p.id_propiedad, v.clave, v.valor
      FROM propiedad p
      CROSS JOIN LATERAL (VALUES
            ('metraje_total',       p.metraje),
            ('antiguedad_anios',    p.antiguedad_anios::numeric),
            ('estacionamientos',    p.numero_estacionamientos::numeric),
            ('ambientes',           p.ambientes::numeric),
            ('frente',              p.frente),
            ('cuota_mantenimiento', p.cuota_mantenimiento)
           ) AS v(clave, valor)
     WHERE v.valor IS NOT NULL
    ON CONFLICT (id_propiedad, clave) DO NOTHING;

    -- Textos de `propiedad`.
    INSERT INTO atributo_propiedad (organizacion_id, id_propiedad, clave, valor_texto)
    SELECT p.organizacion_id, p.id_propiedad, v.clave, v.valor
      FROM propiedad p
      CROSS JOIN LATERAL (VALUES
            ('zonificacion', p.zonificacion),
            ('piso',         p.piso)
           ) AS v(clave, valor)
     WHERE v.valor IS NOT NULL AND btrim(v.valor) <> ''
    ON CONFLICT (id_propiedad, clave) DO NOTHING;

    -- Lo especifico del local comercial.
    INSERT INTO atributo_propiedad (organizacion_id, id_propiedad, clave, valor_texto)
    SELECT d.organizacion_id, d.id_propiedad, 'rubro_permitido', d.rubro_permitido
      FROM detalle_local_comercial d
     WHERE d.rubro_permitido IS NOT NULL AND btrim(d.rubro_permitido) <> ''
    ON CONFLICT (id_propiedad, clave) DO NOTHING;

    INSERT INTO atributo_propiedad (organizacion_id, id_propiedad, clave, valor_numero)
    SELECT d.organizacion_id, d.id_propiedad, 'carga_electrica_kw', d.carga_electrica_kw
      FROM detalle_local_comercial d
     WHERE d.carga_electrica_kw IS NOT NULL
    ON CONFLICT (id_propiedad, clave) DO NOTHING;

    INSERT INTO atributo_propiedad (organizacion_id, id_propiedad, clave, valor_booleano)
    SELECT d.organizacion_id, d.id_propiedad, 'apto_licencia_funcionamiento', d.apto_licencia_funcionamiento
      FROM detalle_local_comercial d
     WHERE d.apto_licencia_funcionamiento IS NOT NULL
    ON CONFLICT (id_propiedad, clave) DO NOTHING;

    SELECT count(*) INTO total FROM atributo_propiedad;
    RAISE NOTICE 'V48: catalogo con % atributos del sistema; % valores migrados',
        (SELECT count(*) FROM catalogo_atributo WHERE del_sistema), total;
END $$;
