-- =====================================================================
-- V4: oferta - locales comerciales (F2, Doc 5 §4).
--
-- Decisiones aplicadas:
--  * propiedad GENERALIZA local_comercial (MEJ-12/31): columnas comunes a
--    cualquier tipo de inmueble en propiedad; lo especifico del local vive
--    en detalle_local_comercial (composicion). El detalle es OBLIGATORIO
--    para tipo 'L'/'O' (lo exige la capa service; un CHECK cross-tabla no
--    es expresable sin triggers).
--  * Propietario = rol PROPIETARIO de la persona (Party-Role): FK compuesta
--    (id_rol_propietario, tipo_rol_propietario) -> persona_rol, con el tipo
--    fijado por DEFAULT + CHECK (misma tecnica que los detalles de rol V1).
--    En el cable congelado, idPropietario = persona_rol.id de ese rol.
--  * distrito: se conserva la columna de TEXTO del cable congelado ademas
--    de la FK al catalogo (id_distrito NULL si el nombre no esta
--    catalogado, igual que la v1). MEJ-13 (solo FK) se completa POST-corte:
--    el contrato actual acepta y devuelve el texto tal como se escribio.
--  * Codigos de 1 caracter del cable en VARCHAR(1) (CHAR es bpchar y rompe
--    el validate de JPA): estado D/N/I, tipo L/O/D/C/T/X, uso C/V/I/M,
--    hito E/R/U/P/O/A/C, estado publicacion B/P/S/C.
--  * Indices heredados de la v1: precio (id,fecha), publicacion
--    (id, fecha DESC), fotos (id, orden) - sirven listas y DISTINCT ON
--    de portada/estado de publicacion.
-- =====================================================================

CREATE TABLE distrito (
    id_distrito    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(100) NOT NULL UNIQUE,
    provincia      VARCHAR(100) NOT NULL DEFAULT 'Lima',
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE propiedad (
    id_propiedad             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                   VARCHAR(20)  NOT NULL UNIQUE,
    direccion                VARCHAR(200) NOT NULL,
    -- Texto del cable congelado; id_distrito es la FK resuelta (ver cabecera).
    distrito                 VARCHAR(100) NOT NULL,
    id_distrito              BIGINT REFERENCES distrito (id_distrito),
    metraje                  NUMERIC(10, 2) NOT NULL,
    precio_referencial       NUMERIC(12, 2) NOT NULL,
    descripcion              TEXT,
    estado                   VARCHAR(1) NOT NULL,
    tipo_inmueble            VARCHAR(1) NOT NULL DEFAULT 'L',
    uso                      VARCHAR(1) NOT NULL DEFAULT 'C',
    ambientes                INT,
    antiguedad_anios         INT,
    zona_urbanizacion        VARCHAR(150),
    geo_lat                  NUMERIC(10, 7),
    geo_long                 NUMERIC(10, 7),
    frente                   NUMERIC(8, 2),
    zonificacion             VARCHAR(40),
    numero_estacionamientos  INT,
    cuota_mantenimiento      NUMERIC(10, 2),
    id_rol_propietario       BIGINT      NOT NULL,
    tipo_rol_propietario     VARCHAR(20) NOT NULL DEFAULT 'PROPIETARIO',
    fecha_registro           TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion      TIMESTAMPTZ,
    CONSTRAINT ck_propiedad_estado           CHECK (estado IN ('D', 'N', 'I')),
    CONSTRAINT ck_propiedad_tipo             CHECK (tipo_inmueble IN ('L', 'O', 'D', 'C', 'T', 'X')),
    CONSTRAINT ck_propiedad_uso              CHECK (uso IN ('C', 'V', 'I', 'M')),
    CONSTRAINT ck_propiedad_metraje          CHECK (metraje > 0),
    CONSTRAINT ck_propiedad_precio           CHECK (precio_referencial >= 0),
    CONSTRAINT ck_propiedad_ambientes        CHECK (ambientes IS NULL OR ambientes > 0),
    CONSTRAINT ck_propiedad_antiguedad       CHECK (antiguedad_anios IS NULL OR antiguedad_anios >= 0),
    CONSTRAINT ck_propiedad_frente           CHECK (frente IS NULL OR frente >= 0),
    CONSTRAINT ck_propiedad_estacionamientos CHECK (numero_estacionamientos IS NULL OR numero_estacionamientos >= 0),
    CONSTRAINT ck_propiedad_mantenimiento    CHECK (cuota_mantenimiento IS NULL OR cuota_mantenimiento >= 0),
    CONSTRAINT ck_propiedad_rol_propietario  CHECK (tipo_rol_propietario = 'PROPIETARIO'),
    CONSTRAINT fk_propiedad_propietario FOREIGN KEY (id_rol_propietario, tipo_rol_propietario)
        REFERENCES persona_rol (id_persona_rol, tipo_rol)
);

CREATE INDEX ix_propiedad_propietario ON propiedad (id_rol_propietario);
CREATE INDEX ix_propiedad_distrito    ON propiedad (id_distrito);

-- ---------------------------------------------------------------------
-- Detalle por tipo LOCAL/OFICINA (composicion, Doc 5 §4): rubro obligatorio.
-- ---------------------------------------------------------------------
CREATE TABLE detalle_local_comercial (
    id_propiedad                 BIGINT PRIMARY KEY REFERENCES propiedad (id_propiedad),
    rubro_permitido              VARCHAR(120) NOT NULL,
    apto_licencia_funcionamiento BOOLEAN,
    carga_electrica_kw           NUMERIC(8, 2),
    CONSTRAINT ck_detalle_local_carga CHECK (carga_electrica_kw IS NULL OR carga_electrica_kw >= 0)
);

-- ---------------------------------------------------------------------
-- Galeria de fotos: el binario vive en el almacen (S3/disco), aqui la clave.
-- ---------------------------------------------------------------------
CREATE TABLE foto_propiedad (
    id_foto        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propiedad   BIGINT       NOT NULL REFERENCES propiedad (id_propiedad),
    clave          VARCHAR(200) NOT NULL,
    nombre_archivo VARCHAR(150) NOT NULL,
    orden          INT          NOT NULL DEFAULT 0,
    fecha_registro TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_foto_propiedad ON foto_propiedad (id_propiedad, orden, id_foto);

-- ---------------------------------------------------------------------
-- Historico de precios por hito (heredado de la v1: fortaleza a conservar).
-- ---------------------------------------------------------------------
CREATE TABLE precio_propiedad (
    id_precio      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propiedad   BIGINT         NOT NULL REFERENCES propiedad (id_propiedad),
    hito           VARCHAR(1)     NOT NULL,
    moneda         VARCHAR(3)     NOT NULL,
    monto          NUMERIC(12, 2) NOT NULL,
    fecha          DATE           NOT NULL,
    fecha_creacion TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_precio_hito   CHECK (hito IN ('E', 'R', 'U', 'P', 'O', 'A', 'C')),
    CONSTRAINT ck_precio_moneda CHECK (moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_precio_monto  CHECK (monto >= 0)
);

CREATE INDEX ix_precio_propiedad ON precio_propiedad (id_propiedad, fecha);

-- ---------------------------------------------------------------------
-- Publicaciones del inmueble (MEJ-04: esquema rico conservado; explotar o
-- simplificar se decide al migrar la pantalla de pauta).
-- ---------------------------------------------------------------------
CREATE TABLE publicacion (
    id_publicacion      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propiedad        BIGINT         NOT NULL REFERENCES propiedad (id_propiedad),
    canal               VARCHAR(30)    NOT NULL,
    url_publicacion     VARCHAR(500),
    version_anuncio     INT            NOT NULL DEFAULT 1,
    titulo_anuncio      VARCHAR(200)   NOT NULL,
    renta_publicada     NUMERIC(12, 2) NOT NULL,
    moneda              VARCHAR(3)     NOT NULL,
    inversion_pauta     NUMERIC(12, 2),
    codigo_origen       VARCHAR(50)    NOT NULL,
    fecha_publicacion   TIMESTAMPTZ    NOT NULL,
    fecha_baja          TIMESTAMPTZ,
    estado              VARCHAR(1)     NOT NULL,
    fecha_creacion      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT ck_publicacion_canal CHECK (
        canal IN ('URBANIA', 'ADONDEVIVIR', 'PROPERATI', 'NEXO_INMOBILIARIO',
                  'FACEBOOK', 'MARKETPLACE', 'INSTAGRAM', 'WHATSAPP',
                  'WEB_PROPIA', 'REFERIDO', 'OTRO')
    ),
    CONSTRAINT ck_publicacion_moneda CHECK (moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_publicacion_estado CHECK (estado IN ('B', 'P', 'S', 'C'))
);

CREATE INDEX ix_publicacion_propiedad ON publicacion (id_propiedad, fecha_publicacion DESC, id_publicacion DESC);

-- =====================================================================
-- Seed: catalogo de distritos (paridad con database/02_seed_base_data.sql).
-- =====================================================================
INSERT INTO distrito (nombre, provincia, activo) VALUES
    ('Lima', 'Lima', TRUE),
    ('Ancon', 'Lima', TRUE),
    ('Ate', 'Lima', TRUE),
    ('Barranco', 'Lima', TRUE),
    ('Brena', 'Lima', TRUE),
    ('Carabayllo', 'Lima', TRUE),
    ('Chaclacayo', 'Lima', TRUE),
    ('Chorrillos', 'Lima', TRUE),
    ('Cieneguilla', 'Lima', TRUE),
    ('Comas', 'Lima', TRUE),
    ('El Agustino', 'Lima', TRUE),
    ('Independencia', 'Lima', TRUE),
    ('Jesus Maria', 'Lima', TRUE),
    ('La Molina', 'Lima', TRUE),
    ('La Victoria', 'Lima', TRUE),
    ('Lince', 'Lima', TRUE),
    ('Los Olivos', 'Lima', TRUE),
    ('Lurigancho-Chosica', 'Lima', TRUE),
    ('Lurin', 'Lima', TRUE),
    ('Magdalena del Mar', 'Lima', TRUE),
    ('Miraflores', 'Lima', TRUE),
    ('Pachacamac', 'Lima', TRUE),
    ('Pucusana', 'Lima', TRUE),
    ('Pueblo Libre', 'Lima', TRUE),
    ('Puente Piedra', 'Lima', TRUE),
    ('Punta Hermosa', 'Lima', TRUE),
    ('Punta Negra', 'Lima', TRUE),
    ('Rimac', 'Lima', TRUE),
    ('San Bartolo', 'Lima', TRUE),
    ('San Borja', 'Lima', TRUE),
    ('San Isidro', 'Lima', TRUE),
    ('San Juan de Lurigancho', 'Lima', TRUE),
    ('San Juan de Miraflores', 'Lima', TRUE),
    ('San Luis', 'Lima', TRUE),
    ('San Martin de Porres', 'Lima', TRUE),
    ('San Miguel', 'Lima', TRUE),
    ('Santa Anita', 'Lima', TRUE),
    ('Santa Maria del Mar', 'Lima', TRUE),
    ('Santa Rosa', 'Lima', TRUE),
    ('Santiago de Surco', 'Lima', TRUE),
    ('Surquillo', 'Lima', TRUE),
    ('Villa El Salvador', 'Lima', TRUE),
    ('Villa Maria del Triunfo', 'Lima', TRUE);

-- =====================================================================
-- Seed DEMO de desarrollo (no existe en la v1; el backfill real llega por
-- el pipeline de sync del Doc 6): 3 propietarios + 2 locales para que las
-- listas y el alta se puedan probar sin los modulos de personas/captacion.
-- =====================================================================
INSERT INTO persona (tipo_persona, tipo_documento, numero_documento, nombres_o_razon_social,
                     telefono, correo, estado, consentimiento_uso_dato) VALUES
    ('J', 'R', '20601234567', 'Inmobiliaria Pacifico SAC',    '999888777', 'contacto@pacifico-demo.pe',  'A', TRUE),
    ('N', 'D', '41552637',    'Elena Castillo Paredes',       '988776655', 'ecastillo@correo-demo.pe',   'A', TRUE),
    ('J', 'R', '20558877665', 'Grupo Andino Propiedades SAC', '977665544', 'ventas@andino-demo.pe',      'A', TRUE);

INSERT INTO persona_rol (id_persona, tipo_rol, vigencia_desde)
SELECT p.id_persona, 'PROPIETARIO', DATE '2025-01-15'
FROM persona p
WHERE p.numero_documento IN ('20601234567', '41552637', '20558877665');

INSERT INTO propiedad (codigo, direccion, distrito, id_distrito, metraje, precio_referencial,
                       descripcion, estado, tipo_inmueble, uso, ambientes, antiguedad_anios,
                       zona_urbanizacion, zonificacion, numero_estacionamientos, cuota_mantenimiento,
                       id_rol_propietario)
SELECT 'LOC-0001', 'Av. Larco 812', 'Miraflores', d.id_distrito, 120.00, 8500.00,
       'Local comercial en esquina, primera linea de avenida.', 'D', 'L', 'C', 3, 8,
       'Centro comercial de Miraflores', 'CZ', 2, 450.00,
       r.id_persona_rol
FROM distrito d, persona p
JOIN persona_rol r ON r.id_persona = p.id_persona AND r.tipo_rol = 'PROPIETARIO'
WHERE d.nombre = 'Miraflores' AND p.numero_documento = '20601234567';

INSERT INTO propiedad (codigo, direccion, distrito, id_distrito, metraje, precio_referencial,
                       descripcion, estado, tipo_inmueble, uso, ambientes, antiguedad_anios,
                       id_rol_propietario)
SELECT 'LOC-0002', 'Jr. Camana 615', 'Lima', d.id_distrito, 85.00, 4200.00,
       'Local en galeria del centro, alto transito peatonal.', 'D', 'L', 'C', 2, 25,
       r.id_persona_rol
FROM distrito d, persona p
JOIN persona_rol r ON r.id_persona = p.id_persona AND r.tipo_rol = 'PROPIETARIO'
WHERE d.nombre = 'Lima' AND p.numero_documento = '41552637';

INSERT INTO detalle_local_comercial (id_propiedad, rubro_permitido, apto_licencia_funcionamiento, carga_electrica_kw)
SELECT id_propiedad, 'Restaurante / cafeteria', TRUE, 15.00 FROM propiedad WHERE codigo = 'LOC-0001';

INSERT INTO detalle_local_comercial (id_propiedad, rubro_permitido, apto_licencia_funcionamiento, carga_electrica_kw)
SELECT id_propiedad, 'Comercio minorista', TRUE, 6.00 FROM propiedad WHERE codigo = 'LOC-0002';

-- Precio esperado inicial (hito E) de cada local demo.
INSERT INTO precio_propiedad (id_propiedad, hito, moneda, monto, fecha)
SELECT id_propiedad, 'E', 'PEN', precio_referencial, DATE '2025-02-01' FROM propiedad;

-- LOC-0001 sale publicado en el canal web propio; LOC-0002 queda en borrador (sin fila).
INSERT INTO publicacion (id_propiedad, canal, titulo_anuncio, renta_publicada, moneda,
                         codigo_origen, fecha_publicacion, estado)
SELECT id_propiedad, 'WEB_PROPIA', 'Publicacion LOC-0001', 8500.00, 'PEN',
       'WEB-' || id_propiedad, now(), 'P'
FROM propiedad WHERE codigo = 'LOC-0001';
