-- =====================================================================
-- V52 - El outbox de eventos de dominio.
--
-- QUE PROBLEMA CIERRA
-- Neo4j NO entra como dependencia: PostgreSQL sigue siendo la verdad y el grafo
-- sera una proyeccion reconstruible. Pero una proyeccion solo se puede
-- reconstruir si existe el rastro de LO QUE PASO, y ese rastro es imposible de
-- fabricar despues: nadie puede saber en 2027 el orden exacto en que una
-- oportunidad paso por sus estados si nunca se anoto.
--
-- Escribirlo ahora cuesta una tabla. No escribirlo cuesta la historia.
--
-- POR QUE OUTBOX Y NO UNA COLA
-- El evento se escribe en la MISMA transaccion que el hecho. Si la transaccion
-- falla, no queda un evento que anuncia algo que nunca ocurrio; si tiene exito,
-- el evento esta garantizado sin necesidad de dos fases. Un consumidor lo lee y
-- marca `proyectado_en`. Sin consumidor, la tabla simplemente crece despacio y
-- no molesta a nadie.
--
-- QUE NO ES ESTA TABLA
-- No sustituye a `historial_estado` (que audita transiciones) ni a
-- `evento_seguridad` (que es append-only y tiene su propio escritor unico).
-- Es la fuente de las PROYECCIONES: el grafo, el matcher, la inteligencia.
-- =====================================================================

CREATE TABLE evento_dominio (
    id_evento        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),

    -- Que paso. En pasado y con nombre de negocio: PROPIEDAD_REGISTRADA,
    -- ENCARGO_ABIERTO, OFERTA_PRESENTADA, CONTRATO_FIRMADO...
    tipo             VARCHAR(60)  NOT NULL,

    -- Sobre que. Mismo vocabulario que `historial_estado.entidad_tipo`.
    entidad_tipo     VARCHAR(30)  NOT NULL,
    entidad_id       BIGINT       NOT NULL,

    -- Cuando ocurrio el HECHO (puede no ser cuando se escribio la fila).
    ocurrido_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Quien. NULL solo si lo produjo el propio sistema sin actor.
    id_persona_rol   BIGINT,

    -- De donde vino: UI, KAIROS o API. Es la columna que permite responder
    -- "quien decidio esto" cuando el agente sea conversacional (D-K-1).
    origen           VARCHAR(10)  NOT NULL DEFAULT 'UI',

    -- Los ids de lo relacionado, para poder proyectar aristas sin volver a
    -- consultar: {"idPropiedad":12,"idCaptacion":34,"idCliente":8}.
    carga_util       JSONB        NOT NULL DEFAULT '{}'::jsonb,

    -- NULL hasta que un consumidor lo procesa. Reprocesar = ponerlo a NULL.
    proyectado_en    TIMESTAMPTZ,

    fecha_creacion   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_evento_origen CHECK (origen IN ('UI', 'KAIROS', 'API', 'SISTEMA'))
);

COMMENT ON TABLE evento_dominio IS
    'Outbox transaccional: la fuente de las proyecciones (grafo, matcher, inteligencia). D-E4-1.';

CREATE INDEX ix_evento_dominio_organizacion ON evento_dominio (organizacion_id, ocurrido_en);
CREATE INDEX ix_evento_dominio_entidad      ON evento_dominio (entidad_tipo, entidad_id);

-- El indice del consumidor: solo mira lo que falta por proyectar, asi que un
-- indice parcial lo deja en microsegundos por muy grande que sea la tabla.
CREATE INDEX ix_evento_dominio_pendiente
    ON evento_dominio (id_evento)
    WHERE proyectado_en IS NULL;

-- Consultas por relacion: "eventos que mencionan esta propiedad".
CREATE INDEX ix_evento_dominio_carga ON evento_dominio USING GIN (carga_util);
