-- =====================================================================
-- V56 - El borrador de captura: donde se quedo una operacion incompleta.
--
-- QUE PROBLEMA CIERRA
-- Hoy un alta que se interrumpe se pierde entera. Da igual que el agente
-- llevara ocho de los diez datos: si cierra la pestana, vuelve a empezar. Y
-- en cuanto la captura sea conversacional el problema deja de ser una
-- molestia y pasa a ser estructural: una conversacion de WhatsApp se corta,
-- se retoma al dia siguiente y el contexto del modelo NO es el sitio donde
-- puede vivir el estado de una operacion de negocio.
--
-- LA DISTINCION QUE ESTA TABLA FIJA
--   historial conversacional  != estado transaccional de una captura
-- El primero es de KAIROS y puede perderse sin consecuencias. El segundo es
-- de BROX y es el que permite decir "te faltan la direccion y el area".
-- KAIROS necesitara los dos; de este es BROX la fuente de verdad.
--
-- POR QUE LOS DATOS VAN COMO JSON Y NO EN COLUMNAS
-- Lo conocido de una captura depende de la INTENCION: registrar una propiedad
-- pide tipo, titulares y operacion; registrar un cliente pide otra cosa.
-- Columnarlo obligaria a una tabla por intencion y a una migracion por cada
-- pregunta nueva, que es justo lo que el catalogo de atributos vino a evitar.
--
-- Como en V53, va como TEXTO con un CHECK que exige JSON valido: el modulo de
-- dominio depende solo de `jakarta.persistence-api` y mapear jsonb exigiria
-- `@JdbcTypeCode`, que es de Hibernate.
--
-- QUE NO ES
-- No es un cache ni una cola. Una fila aqui es una operacion que ALGUIEN
-- empezo y que sigue viva; cuando el caso de uso se ejecuta, el borrador se
-- marca EJECUTADO y guarda a que entidad dio lugar. Esa es la trazabilidad
-- que permite responder "esta propiedad la registro KAIROS a partir de la
-- conversacion del martes".
-- =====================================================================

CREATE TABLE borrador_captura (
    id_borrador          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id      BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),

    -- Legible por una persona: es lo que se dice en voz alta por telefono.
    codigo               VARCHAR(20)  NOT NULL,

    -- Quien la empezo. persona_rol, como el resto del sistema.
    id_persona_rol       BIGINT       NOT NULL,

    -- QUE intenta hacer. Hoy solo REGISTRAR_PROPIEDAD; el vocabulario crece
    -- con los casos de uso, y el CHECK obliga a declararlo aqui.
    intencion            VARCHAR(40)  NOT NULL,

    -- E en curso, J ejecutado, D descartado.
    estado               VARCHAR(1)   NOT NULL DEFAULT 'E',

    -- La entidad que el borrador produjo. NULL mientras no se haya ejecutado.
    entidad_objetivo_tipo VARCHAR(30),
    entidad_objetivo_id   BIGINT,

    -- Por donde entro: UI, KAIROS, API, SISTEMA. Mismo vocabulario que
    -- evento_dominio.origen, a proposito: son la misma pregunta.
    canal_origen         VARCHAR(10)  NOT NULL DEFAULT 'UI',

    -- Lo que ya se sabe, tal cual se sabe. {"tipoPropiedad":"D","operacion":"V"}
    datos_conocidos      TEXT         NOT NULL DEFAULT '{}',

    -- Lo que falta, en el orden en que se va a preguntar. ["titular","direccion"]
    datos_faltantes      TEXT         NOT NULL DEFAULT '[]',

    -- Bloqueo optimista: dos canales pueden estar tocando el mismo borrador
    -- -- que es justo el escenario que esta tabla existe para permitir --  y
    -- el ultimo en escribir no debe pisar al otro en silencio.
    version              INTEGER      NOT NULL DEFAULT 0,

    creado_en            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_borrador_estado
        CHECK (estado IN ('E', 'J', 'D')),
    CONSTRAINT ck_borrador_intencion
        CHECK (intencion IN ('REGISTRAR_PROPIEDAD')),
    CONSTRAINT ck_borrador_canal
        CHECK (canal_origen IN ('UI', 'KAIROS', 'API', 'SISTEMA')),
    CONSTRAINT ck_borrador_conocidos_json
        CHECK (jsonb_typeof(datos_conocidos::jsonb) = 'object'),
    CONSTRAINT ck_borrador_faltantes_json
        CHECK (jsonb_typeof(datos_faltantes::jsonb) = 'array'),
    -- Un borrador ejecutado tiene que decir QUE produjo; uno en curso, no.
    CONSTRAINT ck_borrador_objetivo
        CHECK ((estado = 'J' AND entidad_objetivo_tipo IS NOT NULL AND entidad_objetivo_id IS NOT NULL)
               OR (estado <> 'J' AND entidad_objetivo_id IS NULL))
);

COMMENT ON TABLE borrador_captura IS
    'Estado transaccional de una captura incompleta. Lo comparten Angular y KAIROS. D-E4-2.';

CREATE UNIQUE INDEX uq_borrador_codigo
    ON borrador_captura (organizacion_id, codigo);

-- La consulta del dia a dia: "que dejaste a medias". Parcial, asi que no
-- crece con los borradores ya ejecutados.
CREATE INDEX ix_borrador_en_curso
    ON borrador_captura (organizacion_id, id_persona_rol, actualizado_en DESC)
    WHERE estado = 'E';

CREATE INDEX ix_borrador_objetivo
    ON borrador_captura (entidad_objetivo_tipo, entidad_objetivo_id)
    WHERE entidad_objetivo_id IS NOT NULL;

DO $$
BEGIN
    RAISE NOTICE 'V56: borrador_captura creada; intencion inicial REGISTRAR_PROPIEDAD';
END $$;
