-- =====================================================================
-- V57 - Idempotencia de comandos: un reintento no crea una segunda propiedad.
--
-- QUE PROBLEMA CIERRA
-- `evento_dominio` (V52) dice QUIEN hizo QUE y desde donde. Eso es
-- trazabilidad, y NO es idempotencia: si KAIROS reenvia el mismo
-- `RegistrarPropiedad` porque se cayo la conexion antes de leer la respuesta,
-- el outbox registrara dos altas -- correctamente, porque hubo dos -- y en la
-- cartera habra dos propiedades identicas.
--
-- Y eso va a pasar. Un canal conversacional sobre WhatsApp reintenta por
-- diseno: el emisor no distingue "no llego" de "llego y no me contestaron".
-- Sin esta tabla, la unica defensa seria adivinar por contenido, y por
-- contenido es imposible: dos departamentos iguales en el mismo edificio son
-- un caso real, no un duplicado.
--
-- LA REGLA
--   unicidad (organizacion_id, idempotency_key)
-- La clave la pone el CLIENTE -- un UUID por operacion, repetido igual en
-- cada reintento de ESA operacion -- porque solo el cliente sabe si esto es
-- una operacion nueva o el mismo intento otra vez. Es la misma decision que
-- ya tomo `Idempotencia` para los movimientos de comision (D-F7); aqui se
-- generaliza a cualquier comando.
--
-- POR QUE GUARDA EL RESULTADO Y NO SOLO LA CLAVE
-- El reintento tiene que recibir LO MISMO que recibio el primero, no un 409.
-- Para el cliente, reintentar y acertar a la primera deben ser
-- indistinguibles; si el segundo intento devuelve un error, el canal
-- conversacional le dira al usuario que fallo algo que en realidad salio bien.
--
-- LA HUELLA, Y POR QUE NO BASTA LA CLAVE
-- Si llega la misma clave con OTRO contenido, no es un reintento: es una
-- clave reutilizada por error. Devolver el resultado anterior seria confirmar
-- una operacion que nadie pidio. Por eso se guarda el SHA-256 del comando y
-- la discrepancia se rechaza.
-- =====================================================================

CREATE TABLE comando_idempotente (
    id_comando          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id     BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),

    -- La clave que puso el cliente. VARCHAR(64) como en
    -- `comision_movimiento.clave_idempotencia`: un UUID cabe de sobra.
    idempotency_key     VARCHAR(64)  NOT NULL,

    -- Que comando fue: REGISTRAR_PROPIEDAD, EDITAR_PROPIEDAD...
    tipo_comando        VARCHAR(60)  NOT NULL,

    -- SHA-256 del contenido. Distingue un reintento honesto de una clave
    -- reutilizada para otra cosa.
    huella              VARCHAR(64)  NOT NULL,

    -- Que produjo. Con esto se responde al reintento sin re-ejecutar nada.
    entidad_tipo        VARCHAR(30)  NOT NULL,
    entidad_id          BIGINT       NOT NULL,

    -- Lo que devolvio, para reproducir la respuesta completa. JSON como texto,
    -- por la misma razon que en V53 y V56.
    resultado           TEXT         NOT NULL DEFAULT '{}',

    id_persona_rol      BIGINT,
    origen              VARCHAR(10)  NOT NULL DEFAULT 'UI',
    fecha               TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_comando_origen
        CHECK (origen IN ('UI', 'KAIROS', 'API', 'SISTEMA')),
    CONSTRAINT ck_comando_resultado_json
        CHECK (jsonb_typeof(resultado::jsonb) = 'object')
);

COMMENT ON TABLE comando_idempotente IS
    'Un comando ya ejecutado, con lo que devolvio. Un reintento con la misma clave lo relee. D-E4-2.';

-- LA restriccion. Por organizacion y no global: dos tenants pueden generar el
-- mismo UUID sin que eso signifique nada, y una clave de un tenant no debe
-- poder resolver un comando de otro.
CREATE UNIQUE INDEX uq_comando_idempotente
    ON comando_idempotente (organizacion_id, idempotency_key);

CREATE INDEX ix_comando_entidad
    ON comando_idempotente (entidad_tipo, entidad_id);

CREATE INDEX ix_comando_fecha
    ON comando_idempotente (organizacion_id, fecha DESC);

DO $$
BEGIN
    RAISE NOTICE 'V57: comando_idempotente creada; unicidad por (organizacion, clave)';
END $$;
