-- =====================================================================
-- V5: proceso comercial F2 - prospeccion + captacion (contrato congelado
-- en docs/ai/contrato-congelado-f2-prospeccion-captacion.md).
--  * Actores por ROL (Party-Role): id_rol_agente -> detalle_agente,
--    id_rol_broker_revisor -> detalle_broker (ya no ids de subtipo v1).
--  * Una sola captacion ACTIVA por local: indice unico parcial nativo
--    (reemplaza la columna GENERATED id_local_activo de la v1, MEJ-21).
--  * reasignacion_captacion es TABLA-EVENTO de actor (Doc 5 §7): cambia
--    el agente, no el estado; se integra al timeline en lectura.
--  * Vocabulario del cable: estados P/C/R/E/S/T/D (prospeccion),
--    P/O/R/A/C/V (captacion), resultado_propuesta P/A/R/S.
-- =====================================================================

CREATE TABLE captacion (
    id_captacion          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_captacion      VARCHAR(20)   NOT NULL UNIQUE,
    fecha_captacion       DATE          NOT NULL,
    fecha_inicio_vigencia DATE,
    fecha_fin_vigencia    DATE,
    comision_pactada      NUMERIC(10,2) NOT NULL,
    observaciones         TEXT,
    estado                VARCHAR(1)    NOT NULL,
    fecha_revision        TIMESTAMPTZ,
    observacion_revision  TEXT,
    id_propiedad          BIGINT        NOT NULL REFERENCES propiedad (id_propiedad),
    id_rol_agente         BIGINT        NOT NULL REFERENCES detalle_agente (id_persona_rol),
    id_rol_broker_revisor BIGINT        REFERENCES detalle_broker (id_persona_rol),
    -- Semilla de OperacionComercial: fijo 'A' hasta retirar el backend viejo (Doc 5 §12).
    motivo_operacion      VARCHAR(1)    NOT NULL DEFAULT 'A',
    urgencia              INT,
    exclusividad          BOOLEAN,
    fecha_creacion        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_actualizacion   TIMESTAMPTZ,
    CONSTRAINT ck_captacion_estado   CHECK (estado IN ('P', 'O', 'R', 'A', 'C', 'V')),
    CONSTRAINT ck_captacion_comision CHECK (comision_pactada >= 0),
    CONSTRAINT ck_captacion_fechas   CHECK (
        fecha_fin_vigencia IS NULL OR fecha_inicio_vigencia IS NULL
        OR fecha_fin_vigencia >= fecha_inicio_vigencia
    ),
    CONSTRAINT ck_captacion_motivo_operacion CHECK (motivo_operacion = 'A'),
    CONSTRAINT ck_captacion_urgencia CHECK (urgencia IS NULL OR (urgencia BETWEEN 1 AND 5))
);

CREATE UNIQUE INDEX uq_captacion_activa_por_local ON captacion (id_propiedad) WHERE estado = 'A';
-- Herencia del indexado compuesto (actor, estado, fecha) de la v1 (RC-003).
CREATE INDEX ix_captacion_agente_estado ON captacion (id_rol_agente, estado, fecha_captacion DESC);
CREATE INDEX ix_captacion_estado ON captacion (estado, fecha_captacion DESC);
CREATE INDEX ix_captacion_propiedad ON captacion (id_propiedad);

CREATE TABLE prospeccion (
    id_prospeccion      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_prospeccion  VARCHAR(20) NOT NULL UNIQUE,
    fecha_registro      TIMESTAMPTZ NOT NULL DEFAULT now(),
    estado              VARCHAR(1)  NOT NULL,
    resultado_propuesta VARCHAR(1),
    -- fecha_contacto registra solo el PRIMER contacto y no cambia despues.
    fecha_contacto      DATE,
    fecha_reunion       DATE,
    fecha_propuesta     DATE,
    -- Ultima accion de seguimiento con el propietario; desde el dia 8 sin accion toca recontactar.
    fecha_recontacto    DATE,
    observaciones       TEXT,
    id_propiedad        BIGINT NOT NULL REFERENCES propiedad (id_propiedad),
    id_rol_agente       BIGINT NOT NULL REFERENCES detalle_agente (id_persona_rol),
    id_captacion        BIGINT REFERENCES captacion (id_captacion),
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT ck_prospeccion_estado CHECK (estado IN ('P', 'C', 'R', 'E', 'S', 'T', 'D')),
    CONSTRAINT ck_prospeccion_resultado CHECK (
        resultado_propuesta IS NULL OR resultado_propuesta IN ('P', 'A', 'R', 'S')
    ),
    CONSTRAINT ck_prospeccion_recontacto CHECK (
        fecha_recontacto IS NULL OR estado IN ('C', 'R', 'E', 'S')
    )
);

CREATE INDEX ix_prospeccion_agente_estado ON prospeccion (id_rol_agente, estado, id_prospeccion DESC);
CREATE INDEX ix_prospeccion_recontacto ON prospeccion (fecha_recontacto) WHERE fecha_recontacto IS NOT NULL;
CREATE INDEX ix_prospeccion_propiedad ON prospeccion (id_propiedad);

CREATE TABLE reasignacion_captacion (
    id_reasignacion       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_cambio          TIMESTAMPTZ NOT NULL DEFAULT now(),
    motivo                TEXT   NOT NULL,
    id_captacion          BIGINT NOT NULL REFERENCES captacion (id_captacion),
    id_rol_agente_anterior BIGINT NOT NULL REFERENCES detalle_agente (id_persona_rol),
    id_rol_agente_nuevo   BIGINT NOT NULL REFERENCES detalle_agente (id_persona_rol),
    id_rol_broker         BIGINT NOT NULL REFERENCES detalle_broker (id_persona_rol),
    CONSTRAINT ck_reasignacion_agentes CHECK (id_rol_agente_anterior <> id_rol_agente_nuevo)
);

CREATE INDEX ix_reasignacion_captacion ON reasignacion_captacion (id_captacion, fecha_cambio DESC);

-- ---------------------------------------------------------------------
-- Seed DEMO de desarrollo (sobre los locales DEMO de V4 y el agente AGE-001):
--  * PRO-0001: prospeccion CAPTADA del LOC-0001 -> captacion CAP-0001
--    PENDIENTE de revision (alimenta la bandeja del broker BRK-001).
--  * PRO-0002: prospeccion CONTACTADA del LOC-0002 con recontacto vencido
--    (alimenta /prospecciones/recontactar).
-- ---------------------------------------------------------------------

INSERT INTO captacion (codigo_captacion, fecha_captacion, comision_pactada, observaciones,
                       estado, id_propiedad, id_rol_agente, urgencia, exclusividad)
SELECT 'CAP-0001', DATE '2026-07-08', 4250.00,
       'Captacion demo pendiente de revision del broker.',
       'P', p.id_propiedad, da.id_persona_rol, 3, TRUE
FROM propiedad p, detalle_agente da
WHERE p.codigo = 'LOC-0001' AND da.codigo_agente = 'AGE-001';

INSERT INTO prospeccion (codigo_prospeccion, fecha_registro, estado, resultado_propuesta,
                         fecha_contacto, fecha_reunion, fecha_propuesta, fecha_recontacto,
                         observaciones, id_propiedad, id_rol_agente, id_captacion)
SELECT 'PRO-0001', TIMESTAMPTZ '2026-06-18 10:00:00-05', 'T', 'A',
       DATE '2026-06-20', DATE '2026-06-25', DATE '2026-07-01', NULL,
       'Propietario acepto el encargo de alquiler.',
       p.id_propiedad, da.id_persona_rol, c.id_captacion
FROM propiedad p, detalle_agente da, captacion c
WHERE p.codigo = 'LOC-0001' AND da.codigo_agente = 'AGE-001' AND c.codigo_captacion = 'CAP-0001';

INSERT INTO prospeccion (codigo_prospeccion, fecha_registro, estado, fecha_contacto,
                         fecha_recontacto, observaciones, id_propiedad, id_rol_agente)
SELECT 'PRO-0002', TIMESTAMPTZ '2026-06-28 09:30:00-05', 'C',
       DATE '2026-07-01', DATE '2026-07-01',
       'Primer contacto hecho; propietario pidio llamar de nuevo.',
       p.id_propiedad, da.id_persona_rol
FROM propiedad p, detalle_agente da
WHERE p.codigo = 'LOC-0002' AND da.codigo_agente = 'AGE-001';
