-- =====================================================================
-- V6: nucleo multi-tenant (D-16/D-18/D-20/D-22/D-24/D-25/D-26).
-- Plan: docs/ai/plan-migracion-v6-tenancy.md.
--  * Tenant UNICO de legado (BROX_LEGACY): la app sigue operando igual,
--    pero toda entidad privada queda acotada por organizacion_id.
--  * Aislamiento V6 = discriminador + filtro en app; RLS se activa al
--    habilitar multi-tenant real (post-corte GlassFish).
--  * Globales (SIN organizacion_id): entidad_tipo, distrito.
--  * Sin DEFAULT permanente en organizacion_id: el backend provee el
--    tenant explicitamente (un DEFAULT ocultaria codigo sin contexto).
-- =====================================================================

-- ---------------------------------------------------------------------
-- V6.1  Organizacion + tenant de legado
-- ---------------------------------------------------------------------
CREATE TABLE organizacion (
    id_organizacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(30)  NOT NULL UNIQUE,
    nombre          VARCHAR(150) NOT NULL,
    estado          VARCHAR(1)   NOT NULL DEFAULT 'A',
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_organizacion_estado CHECK (estado IN ('A', 'I'))
);

-- SIVAN es la empresa duena de la plataforma, NO un tenant: el legado es BROX_LEGACY.
INSERT INTO organizacion (codigo, nombre) VALUES ('BROX_LEGACY', 'Organizacion de legado');

-- ---------------------------------------------------------------------
-- V6.2  organizacion_id NULLABLE -> backfill -> NOT NULL (14 privadas)
--   Patron por tabla: ADD COLUMN null -> UPDATE al legado -> SET NOT NULL.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    legado    BIGINT := (SELECT id_organizacion FROM organizacion WHERE codigo = 'BROX_LEGACY');
    privada   TEXT;
    privadas  TEXT[] := ARRAY[
        'persona', 'persona_rol', 'credencial_usuario', 'detalle_broker',
        'detalle_agente', 'supervision_agente', 'historial_estado',
        'propiedad', 'detalle_local_comercial', 'foto_propiedad',
        'precio_propiedad', 'publicacion', 'captacion', 'prospeccion',
        'reasignacion_captacion'
    ];
BEGIN
    FOREACH privada IN ARRAY privadas LOOP
        EXECUTE format(
            'ALTER TABLE %I ADD COLUMN organizacion_id BIGINT REFERENCES organizacion (id_organizacion)',
            privada);
        EXECUTE format('UPDATE %I SET organizacion_id = %L WHERE organizacion_id IS NULL',
            privada, legado);
        EXECUTE format('ALTER TABLE %I ALTER COLUMN organizacion_id SET NOT NULL', privada);
        -- Nombre del indice por concatenacion (%s), tabla como identificador (%I).
        EXECUTE format('CREATE INDEX ix_%s_organizacion ON %I (organizacion_id)', privada, privada);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------
-- V6.3  Unicidades globales -> por organizacion
-- ---------------------------------------------------------------------
-- persona: documento y correo unicos DENTRO de la organizacion.
ALTER TABLE persona DROP CONSTRAINT uq_persona_documento;
ALTER TABLE persona ADD  CONSTRAINT uq_persona_documento
    UNIQUE (organizacion_id, tipo_documento, numero_documento);
ALTER TABLE persona DROP CONSTRAINT uq_persona_correo;
ALTER TABLE persona ADD  CONSTRAINT uq_persona_correo
    UNIQUE (organizacion_id, correo);

-- credencial_usuario: el login es unico por org (D-22: alias durante la convivencia).
ALTER TABLE credencial_usuario DROP CONSTRAINT credencial_usuario_nombre_usuario_key;
ALTER TABLE credencial_usuario ADD  CONSTRAINT uq_credencial_nombre_usuario
    UNIQUE (organizacion_id, nombre_usuario);

-- codigos operativos: cada corredora numera sus BRK-/AGE- desde 001.
ALTER TABLE detalle_broker DROP CONSTRAINT detalle_broker_codigo_broker_key;
ALTER TABLE detalle_broker ADD  CONSTRAINT uq_broker_codigo
    UNIQUE (organizacion_id, codigo_broker);
ALTER TABLE detalle_agente DROP CONSTRAINT detalle_agente_codigo_agente_key;
ALTER TABLE detalle_agente ADD  CONSTRAINT uq_agente_codigo
    UNIQUE (organizacion_id, codigo_agente);

-- un ADMINISTRADOR por organizacion (antes era uno GLOBAL).
DROP INDEX uq_broker_admin_unico;
CREATE UNIQUE INDEX uq_broker_admin_unico ON detalle_broker (organizacion_id)
    WHERE es_administrador;

-- codigos de oferta y proceso.
ALTER TABLE propiedad DROP CONSTRAINT propiedad_codigo_key;
ALTER TABLE propiedad ADD  CONSTRAINT uq_propiedad_codigo
    UNIQUE (organizacion_id, codigo);
ALTER TABLE captacion DROP CONSTRAINT captacion_codigo_captacion_key;
ALTER TABLE captacion ADD  CONSTRAINT uq_captacion_codigo
    UNIQUE (organizacion_id, codigo_captacion);
ALTER TABLE prospeccion DROP CONSTRAINT prospeccion_codigo_prospeccion_key;
ALTER TABLE prospeccion ADD  CONSTRAINT uq_prospeccion_codigo
    UNIQUE (organizacion_id, codigo_prospeccion);

-- invariante "una captacion ACTIVA por local", ahora acotado por org.
DROP INDEX uq_captacion_activa_por_local;
CREATE UNIQUE INDEX uq_captacion_activa_por_local
    ON captacion (organizacion_id, id_propiedad) WHERE estado = 'A';

-- ---------------------------------------------------------------------
-- V6.4  Proteccion de relaciones: UNIQUE (organizacion_id, pk) en padres
--        + FK compuestas con tenant en los vinculos criticos.
--   Aunque una consulta tenga un bug, no podra cruzar organizaciones.
-- ---------------------------------------------------------------------
ALTER TABLE persona        ADD CONSTRAINT uq_persona_org        UNIQUE (organizacion_id, id_persona);
ALTER TABLE persona_rol    ADD CONSTRAINT uq_persona_rol_org    UNIQUE (organizacion_id, id_persona_rol);
ALTER TABLE propiedad      ADD CONSTRAINT uq_propiedad_org      UNIQUE (organizacion_id, id_propiedad);
ALTER TABLE captacion      ADD CONSTRAINT uq_captacion_org      UNIQUE (organizacion_id, id_captacion);
ALTER TABLE detalle_agente ADD CONSTRAINT uq_detalle_agente_org UNIQUE (organizacion_id, id_persona_rol);

-- persona_rol -> persona (misma org).
ALTER TABLE persona_rol ADD CONSTRAINT fk_persona_rol_persona_org
    FOREIGN KEY (organizacion_id, id_persona) REFERENCES persona (organizacion_id, id_persona);

-- propiedad -> persona_rol propietario (misma org).
ALTER TABLE propiedad ADD CONSTRAINT fk_propiedad_propietario_org
    FOREIGN KEY (organizacion_id, id_rol_propietario) REFERENCES persona_rol (organizacion_id, id_persona_rol);

-- captacion/prospeccion -> propiedad y -> detalle_agente (misma org).
ALTER TABLE captacion ADD CONSTRAINT fk_captacion_propiedad_org
    FOREIGN KEY (organizacion_id, id_propiedad) REFERENCES propiedad (organizacion_id, id_propiedad);
ALTER TABLE captacion ADD CONSTRAINT fk_captacion_agente_org
    FOREIGN KEY (organizacion_id, id_rol_agente) REFERENCES detalle_agente (organizacion_id, id_persona_rol);
ALTER TABLE prospeccion ADD CONSTRAINT fk_prospeccion_propiedad_org
    FOREIGN KEY (organizacion_id, id_propiedad) REFERENCES propiedad (organizacion_id, id_propiedad);
ALTER TABLE prospeccion ADD CONSTRAINT fk_prospeccion_agente_org
    FOREIGN KEY (organizacion_id, id_rol_agente) REFERENCES detalle_agente (organizacion_id, id_persona_rol);

-- reasignacion -> captacion (misma org).
ALTER TABLE reasignacion_captacion ADD CONSTRAINT fk_reasignacion_captacion_org
    FOREIGN KEY (organizacion_id, id_captacion) REFERENCES captacion (organizacion_id, id_captacion);

-- ---------------------------------------------------------------------
-- V6.5  Membresia del usuario interno (D-26). La CUENTA de acceso global
--        (D-22) se separa en el corte de GlassFish; aqui la membresia ya
--        existe para que las asignaciones referencien la organizacion.
--   id_usuario = referencia a la futura cuenta global; durante la
--   convivencia apunta al persona_rol del usuario interno (1:1 con el login).
-- ---------------------------------------------------------------------
CREATE TABLE usuario_organizacion (
    id_usuario_organizacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_usuario       BIGINT      NOT NULL,   -- cuenta global (transitorio: id_persona_rol del interno)
    rol              VARCHAR(20) NOT NULL,   -- BROKER | AGENTE | ADMIN (banda operativa)
    nombre_visible   VARCHAR(120),
    estado           VARCHAR(1)  NOT NULL DEFAULT 'A',
    -- Vinculo OPCIONAL a una persona del MISMO tenant, solo si el usuario
    -- tambien es actor del dominio (agente que alquila para si). No cambia permisos.
    id_persona       BIGINT,
    fecha_alta       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_usuario_org_estado CHECK (estado IN ('A', 'I')),
    CONSTRAINT uq_usuario_org UNIQUE (organizacion_id, id_usuario),
    CONSTRAINT fk_usuario_org_persona_org
        FOREIGN KEY (organizacion_id, id_persona) REFERENCES persona (organizacion_id, id_persona)
);
CREATE INDEX ix_usuario_org_organizacion ON usuario_organizacion (organizacion_id, estado);

-- Backfill: una membresia por usuario interno existente (credencial_usuario),
-- con la banda operativa segun su detalle (ADMIN si es_administrador, si no BROKER/AGENTE).
INSERT INTO usuario_organizacion (organizacion_id, id_usuario, rol, nombre_visible, id_persona)
SELECT cu.organizacion_id, cu.id_persona_rol,
       CASE
           WHEN db.es_administrador THEN 'ADMIN'
           WHEN db.id_persona_rol IS NOT NULL THEN 'BROKER'
           ELSE 'AGENTE'
       END,
       per.nombres_o_razon_social,
       pr.id_persona
FROM credencial_usuario cu
JOIN persona_rol pr ON pr.id_persona_rol = cu.id_persona_rol
JOIN persona     per ON per.id_persona = pr.id_persona
LEFT JOIN detalle_broker db ON db.id_persona_rol = cu.id_persona_rol;

-- ---------------------------------------------------------------------
-- V6.6  Consentimiento granular (D-25): finalidad + base juridica +
--        estado + version del aviso + evidencia + vigencia. Contrato
--        listo; los flujos conversacionales de KAIROS llegan despues.
-- ---------------------------------------------------------------------
CREATE TABLE finalidad_tratamiento (
    codigo                VARCHAR(40) PRIMARY KEY,
    nombre                VARCHAR(120) NOT NULL,
    descripcion           VARCHAR(300),
    requiere_consentimiento BOOLEAN    NOT NULL DEFAULT TRUE,
    permite_revocacion    BOOLEAN      NOT NULL DEFAULT TRUE,
    nivel                 VARCHAR(20),
    estado                VARCHAR(1)   NOT NULL DEFAULT 'A',
    CONSTRAINT ck_finalidad_estado CHECK (estado IN ('A', 'I'))
);

INSERT INTO finalidad_tratamiento (codigo, nombre, requiere_consentimiento, permite_revocacion, nivel) VALUES
    ('OPERACION_SERVICIO',    'Operacion del servicio',        FALSE, FALSE, 'NECESARIA'),
    ('ANALITICA_AGREGADA',    'Analitica agregada',            TRUE,  TRUE,  'OPCIONAL'),
    ('MEJORA_MODELOS',        'Mejora de modelos',             TRUE,  TRUE,  'OPCIONAL'),
    ('RED_COLABORATIVA',      'Participacion en red',          TRUE,  TRUE,  'OPCIONAL'),
    ('PROSPECCION_COMERCIAL', 'Prospeccion comercial',         TRUE,  TRUE,  'OPCIONAL');

CREATE TABLE aviso_privacidad_version (
    id_aviso        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         VARCHAR(20)  NOT NULL UNIQUE,
    contenido_hash  VARCHAR(64)  NOT NULL,
    contenido       TEXT         NOT NULL,
    vigente_desde   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    vigente_hasta   TIMESTAMPTZ
);

CREATE TABLE evidencia_autorizacion (
    id_evidencia        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal               VARCHAR(20)  NOT NULL,   -- WEB | WHATSAPP | …
    mensaje_id          VARCHAR(100),
    ip                  VARCHAR(45),
    user_agent          VARCHAR(300),
    phone_number_id     VARCHAR(60),
    whatsapp_message_id VARCHAR(100),
    fecha_hora          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    texto_mostrado      TEXT,
    respuesta_recibida  TEXT
);

-- Registro APPEND-ONLY: el estado vigente se deriva por proyeccion, no se
-- destruye el evento anterior (trazabilidad completa del consentimiento).
CREATE TABLE autorizacion_tratamiento_evento (
    id_evento        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    id_persona       BIGINT       NOT NULL,
    finalidad_codigo VARCHAR(40)  NOT NULL REFERENCES finalidad_tratamiento (codigo),
    evento           VARCHAR(24)  NOT NULL,
    base_juridica    VARCHAR(24)  NOT NULL,
    version_aviso    VARCHAR(20),
    ocurrido_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    id_evidencia     BIGINT REFERENCES evidencia_autorizacion (id_evidencia),
    CONSTRAINT ck_autorizacion_evento CHECK (
        evento IN ('INFORMADO', 'OTORGADO', 'RECHAZADO', 'REVOCADO',
                   'REOTORGADO', 'EXPIRADO', 'CAMBIO_BASE_JURIDICA')
    ),
    CONSTRAINT ck_autorizacion_base CHECK (
        base_juridica IN ('CONSENTIMIENTO', 'RELACION_CONTRACTUAL',
                          'OBLIGACION_LEGAL', 'OTRA_EXCEPCION_LEGAL')
    ),
    CONSTRAINT fk_autorizacion_persona_org
        FOREIGN KEY (organizacion_id, id_persona) REFERENCES persona (organizacion_id, id_persona)
);
CREATE INDEX ix_autorizacion_persona
    ON autorizacion_tratamiento_evento (organizacion_id, id_persona, finalidad_codigo, ocurrido_en DESC);
