-- =====================================================================
-- V7: vertical F3 - DEMANDA (contrato congelado en
-- docs/ai/contrato-congelado-f3-demanda.md).
--  * El cliente interesado es un ROL de persona (Party-Role), igual que
--    agente/broker/propietario: detalle_cliente cuelga de persona_rol con
--    tipo_rol='CLIENTE'. No se duplican nombre/documento/contacto.
--  * oportunidad_comercial es la entidad-HUB: conserva la trazabilidad
--    aunque el interesado nunca llegue a presentar una solicitud.
--  * interaccion_comercial es la bitacora POLIMORFICA: cuelga de UNA de
--    cuatro entidades segun 'contexto', con CHECK que lo garantiza.
--  * Todo es privado del tenant (V6): organizacion_id NOT NULL sin
--    DEFAULT, unicidades por organizacion y FK compuestas con el tenant.
--  * Los codigos de entidad_tipo (OPORTUNIDAD, VISITA, CLIENTE_INTERESADO,
--    REQUERIMIENTO) ya estan sembrados desde V2.
--  * Vocabulario del cable: estado oportunidad A/S/N/F/X, visita
--    P/G/C/N/R. OJO: requerimiento y resultado de interaccion NO son
--    CHAR(1) — la v1 emite el nombre del enum (ver §1 del contrato).
-- =====================================================================

-- Falta desde V6.4: la interaccion de prospeccion necesita la FK compuesta.
ALTER TABLE prospeccion ADD CONSTRAINT uq_prospeccion_org UNIQUE (organizacion_id, id_prospeccion);

-- ---------------------------------------------------------------------
-- Detalle del rol CLIENTE (demanda). Lo comercial vive aqui; lo civil
-- (nombre, documento, telefono, correo, estado) sigue en persona.
-- ---------------------------------------------------------------------
CREATE TABLE detalle_cliente (
    id_persona_rol         BIGINT      PRIMARY KEY,
    tipo_rol               VARCHAR(20) NOT NULL DEFAULT 'CLIENTE',
    organizacion_id        BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    rubro_comercial        VARCHAR(150),
    -- Consentimiento de CONTACTO comercial; el de uso de dato vive en persona.
    consentimiento_contacto BOOLEAN,
    fecha_registro         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_detalle_cliente_tipo_rol CHECK (tipo_rol = 'CLIENTE'),
    CONSTRAINT fk_detalle_cliente_rol FOREIGN KEY (id_persona_rol, tipo_rol)
        REFERENCES persona_rol (id_persona_rol, tipo_rol),
    CONSTRAINT uq_detalle_cliente_org UNIQUE (organizacion_id, id_persona_rol)
);

CREATE INDEX ix_detalle_cliente_organizacion ON detalle_cliente (organizacion_id);

-- ---------------------------------------------------------------------
-- Requerimiento = perfil de busqueda del cliente. Solo los ACTIVO
-- alimentan el matching de cartera.
-- ---------------------------------------------------------------------
CREATE TABLE requerimiento_cliente (
    id_requerimiento    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id     BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    id_rol_cliente      BIGINT       NOT NULL REFERENCES detalle_cliente (id_persona_rol),
    rubro               VARCHAR(150) NOT NULL,
    -- Nombre del enum, no CHAR(1): asi lo emite la v1 (TipoInmuebleComercial).
    tipo_inmueble       VARCHAR(30),
    renta_min           NUMERIC(12, 2),
    renta_max           NUMERIC(12, 2),
    moneda              VARCHAR(3),
    metraje_min         NUMERIC(10, 2),
    metraje_max         NUMERIC(10, 2),
    frente_minimo       NUMERIC(8, 2),
    estado              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVO',
    observaciones       TEXT,
    fecha_creacion      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT ck_requerimiento_estado CHECK (estado IN ('ACTIVO', 'PAUSADO', 'CERRADO')),
    CONSTRAINT ck_requerimiento_tipo CHECK (
        tipo_inmueble IS NULL OR tipo_inmueble IN (
            'LOCAL_COMERCIAL', 'OFICINA', 'DEPOSITO_ALMACEN',
            'STAND_MODULO', 'TERRENO_COMERCIAL', 'OTRO')
    ),
    CONSTRAINT ck_requerimiento_moneda CHECK (moneda IS NULL OR moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_requerimiento_renta CHECK (
        renta_min IS NULL OR renta_max IS NULL OR renta_max >= renta_min),
    CONSTRAINT ck_requerimiento_metraje CHECK (
        metraje_min IS NULL OR metraje_max IS NULL OR metraje_max >= metraje_min),
    CONSTRAINT uq_requerimiento_org UNIQUE (organizacion_id, id_requerimiento),
    CONSTRAINT fk_requerimiento_cliente_org FOREIGN KEY (organizacion_id, id_rol_cliente)
        REFERENCES detalle_cliente (organizacion_id, id_persona_rol)
);

CREATE INDEX ix_requerimiento_cliente ON requerimiento_cliente (organizacion_id, id_rol_cliente);
CREATE INDEX ix_requerimiento_activo ON requerimiento_cliente (organizacion_id, estado);

-- Zonas buscadas: N:M contra el catalogo GLOBAL de distritos.
CREATE TABLE requerimiento_distrito (
    id_requerimiento BIGINT NOT NULL REFERENCES requerimiento_cliente (id_requerimiento) ON DELETE CASCADE,
    id_distrito      BIGINT NOT NULL REFERENCES distrito (id_distrito),
    PRIMARY KEY (id_requerimiento, id_distrito)
);

-- ---------------------------------------------------------------------
-- Oportunidad comercial: el HUB del proceso de demanda.
-- ---------------------------------------------------------------------
CREATE TABLE oportunidad_comercial (
    id_oportunidad            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id           BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    codigo_oportunidad        VARCHAR(20) NOT NULL,
    estado                    VARCHAR(1)  NOT NULL,
    id_rol_cliente            BIGINT      NOT NULL REFERENCES detalle_cliente (id_persona_rol),
    id_captacion              BIGINT      NOT NULL REFERENCES captacion (id_captacion),
    id_rol_agente             BIGINT      NOT NULL REFERENCES detalle_agente (id_persona_rol),
    id_publicacion_origen     BIGINT      REFERENCES publicacion (id_publicacion),
    observaciones             TEXT,
    motivo_cierre             TEXT,
    fecha_registro            TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- La v1 la iguala a fecha_registro en el alta; se conserva por trazabilidad.
    fecha_primera_consulta    TIMESTAMPTZ,
    fecha_cierre              TIMESTAMPTZ,
    fecha_actualizacion_estado TIMESTAMPTZ,
    fecha_actualizacion       TIMESTAMPTZ,
    CONSTRAINT ck_oportunidad_estado CHECK (estado IN ('A', 'S', 'N', 'F', 'X')),
    CONSTRAINT uq_oportunidad_codigo UNIQUE (organizacion_id, codigo_oportunidad),
    CONSTRAINT uq_oportunidad_org UNIQUE (organizacion_id, id_oportunidad),
    CONSTRAINT fk_oportunidad_cliente_org FOREIGN KEY (organizacion_id, id_rol_cliente)
        REFERENCES detalle_cliente (organizacion_id, id_persona_rol),
    CONSTRAINT fk_oportunidad_captacion_org FOREIGN KEY (organizacion_id, id_captacion)
        REFERENCES captacion (organizacion_id, id_captacion),
    CONSTRAINT fk_oportunidad_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol)
);

CREATE INDEX ix_oportunidad_agente_estado ON oportunidad_comercial (id_rol_agente, estado, id_oportunidad DESC);
CREATE INDEX ix_oportunidad_captacion ON oportunidad_comercial (id_captacion);
CREATE INDEX ix_oportunidad_cliente ON oportunidad_comercial (id_rol_cliente);
CREATE INDEX ix_oportunidad_organizacion ON oportunidad_comercial (organizacion_id);

-- Cierre por no continuidad: queda el POR QUE, no solo el estado.
CREATE TABLE motivo_no_continuidad (
    id_motivo         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id   BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_oportunidad    BIGINT      NOT NULL REFERENCES oportunidad_comercial (id_oportunidad),
    razon_principal   VARCHAR(1)  NOT NULL,
    observaciones     TEXT,
    id_rol_agente     BIGINT      NOT NULL REFERENCES detalle_agente (id_persona_rol),
    fecha_registro    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_motivo_razon CHECK (razon_principal IN ('P', 'U', 'C', 'L', 'N', 'E', 'O')),
    CONSTRAINT fk_motivo_oportunidad_org FOREIGN KEY (organizacion_id, id_oportunidad)
        REFERENCES oportunidad_comercial (organizacion_id, id_oportunidad)
);

CREATE INDEX ix_motivo_oportunidad ON motivo_no_continuidad (id_oportunidad);

-- ---------------------------------------------------------------------
-- Visita al local. El desenlace (nivel de interes, objecion, opinion de
-- precio, proxima accion) solo tiene sentido en estado REALIZADA.
-- ---------------------------------------------------------------------
CREATE TABLE visita (
    id_visita           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id     BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_oportunidad      BIGINT      NOT NULL REFERENCES oportunidad_comercial (id_oportunidad),
    id_rol_agente       BIGINT      NOT NULL REFERENCES detalle_agente (id_persona_rol),
    fecha_visita        DATE        NOT NULL,
    hora_visita         TIME,
    estado              VARCHAR(1)  NOT NULL,
    observaciones       TEXT,
    -- Codigo del enum ResultadoInteraccion: MIXTO (1 char o palabra) en la v1.
    resultado           VARCHAR(30),
    nivel_interes       INT,
    objecion_principal  VARCHAR(1),
    opinion_precio      VARCHAR(1),
    proxima_accion      VARCHAR(1),
    razon_no_continuidad VARCHAR(1),
    fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ,
    CONSTRAINT ck_visita_estado CHECK (estado IN ('P', 'G', 'C', 'N', 'R')),
    CONSTRAINT ck_visita_nivel CHECK (nivel_interes IS NULL OR (nivel_interes BETWEEN 1 AND 5)),
    CONSTRAINT ck_visita_objecion CHECK (objecion_principal IS NULL OR objecion_principal IN ('P','U','E','C','O')),
    CONSTRAINT ck_visita_opinion CHECK (opinion_precio IS NULL OR opinion_precio IN ('A','J','B')),
    CONSTRAINT ck_visita_proxima CHECK (proxima_accion IS NULL OR proxima_accion IN ('V','O','S','D')),
    CONSTRAINT ck_visita_razon CHECK (razon_no_continuidad IS NULL OR razon_no_continuidad IN ('P','U','C','L','N','E','O')),
    -- El desenlace solo existe si la visita se realizo.
    CONSTRAINT ck_visita_desenlace CHECK (
        estado = 'R' OR (resultado IS NULL AND nivel_interes IS NULL
                         AND objecion_principal IS NULL AND opinion_precio IS NULL
                         AND proxima_accion IS NULL)
    ),
    CONSTRAINT uq_visita_org UNIQUE (organizacion_id, id_visita),
    CONSTRAINT fk_visita_oportunidad_org FOREIGN KEY (organizacion_id, id_oportunidad)
        REFERENCES oportunidad_comercial (organizacion_id, id_oportunidad),
    CONSTRAINT fk_visita_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol)
);

CREATE INDEX ix_visita_agente_fecha ON visita (id_rol_agente, fecha_visita DESC, id_visita DESC);
CREATE INDEX ix_visita_oportunidad ON visita (id_oportunidad);
-- Bandeja "proximas": las que siguen vivas, por fecha ascendente.
CREATE INDEX ix_visita_programadas ON visita (organizacion_id, fecha_visita, hora_visita)
    WHERE estado IN ('P', 'G');

-- ---------------------------------------------------------------------
-- Bitacora POLIMORFICA. Cuelga de UNA entidad segun contexto; el CHECK
-- impide que quede colgada de ninguna o de dos a la vez (la v1 solo lo
-- validaba en la capa REST).
-- ---------------------------------------------------------------------
CREATE TABLE interaccion_comercial (
    id_interaccion     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id    BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    contexto           VARCHAR(20) NOT NULL,
    id_oportunidad     BIGINT      REFERENCES oportunidad_comercial (id_oportunidad),
    id_prospeccion     BIGINT      REFERENCES prospeccion (id_prospeccion),
    id_captacion       BIGINT      REFERENCES captacion (id_captacion),
    id_rol_cliente     BIGINT      REFERENCES detalle_cliente (id_persona_rol),
    id_rol_agente      BIGINT      NOT NULL REFERENCES detalle_agente (id_persona_rol),
    canal_contacto     VARCHAR(1)  NOT NULL,
    resultado          VARCHAR(30),
    observaciones      TEXT,
    transcripcion_nota TEXT,
    fecha_hora         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_interaccion_canal CHECK (canal_contacto IN ('L','W','E','P','R','T','O')),
    CONSTRAINT ck_interaccion_contexto CHECK (
        (contexto = 'OPORTUNIDAD' AND id_oportunidad IS NOT NULL
             AND id_prospeccion IS NULL AND id_captacion IS NULL AND id_rol_cliente IS NULL)
     OR (contexto = 'PROSPECCION' AND id_prospeccion IS NOT NULL
             AND id_oportunidad IS NULL AND id_captacion IS NULL AND id_rol_cliente IS NULL)
     OR (contexto = 'CAPTACION'   AND id_captacion IS NOT NULL
             AND id_oportunidad IS NULL AND id_prospeccion IS NULL AND id_rol_cliente IS NULL)
     OR (contexto = 'CLIENTE'     AND id_rol_cliente IS NOT NULL
             AND id_oportunidad IS NULL AND id_prospeccion IS NULL AND id_captacion IS NULL)
    ),
    CONSTRAINT fk_interaccion_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol),
    CONSTRAINT fk_interaccion_oportunidad_org FOREIGN KEY (organizacion_id, id_oportunidad)
        REFERENCES oportunidad_comercial (organizacion_id, id_oportunidad),
    CONSTRAINT fk_interaccion_prospeccion_org FOREIGN KEY (organizacion_id, id_prospeccion)
        REFERENCES prospeccion (organizacion_id, id_prospeccion),
    CONSTRAINT fk_interaccion_captacion_org FOREIGN KEY (organizacion_id, id_captacion)
        REFERENCES captacion (organizacion_id, id_captacion),
    CONSTRAINT fk_interaccion_cliente_org FOREIGN KEY (organizacion_id, id_rol_cliente)
        REFERENCES detalle_cliente (organizacion_id, id_persona_rol)
);

-- Orden del cable: fecha_hora desc, id desc.
CREATE INDEX ix_interaccion_agente_fecha ON interaccion_comercial (id_rol_agente, fecha_hora DESC, id_interaccion DESC);
CREATE INDEX ix_interaccion_oportunidad ON interaccion_comercial (id_oportunidad) WHERE id_oportunidad IS NOT NULL;
CREATE INDEX ix_interaccion_prospeccion ON interaccion_comercial (id_prospeccion) WHERE id_prospeccion IS NOT NULL;
CREATE INDEX ix_interaccion_captacion ON interaccion_comercial (id_captacion) WHERE id_captacion IS NOT NULL;
CREATE INDEX ix_interaccion_cliente ON interaccion_comercial (id_rol_cliente) WHERE id_rol_cliente IS NOT NULL;

-- =====================================================================
-- Seed DEMO de desarrollo (tenant de legado):
--  * 2 clientes con requerimiento ACTIVO que casa con los locales de V4,
--    para que el matching de cartera tenga con que responder.
--  * 1 oportunidad ABIERTA sobre CAP-0001 con 1 visita PROGRAMADA.
-- =====================================================================
DO $$
DECLARE
    legado     BIGINT := (SELECT id_organizacion FROM organizacion WHERE codigo = 'BROX_LEGACY');
    rol_agente BIGINT := (SELECT id_persona_rol FROM detalle_agente WHERE codigo_agente = 'AGE-001');
    id_cap     BIGINT := (SELECT id_captacion FROM captacion WHERE codigo_captacion = 'CAP-0001');
    persona_a  BIGINT;
    persona_b  BIGINT;
    rol_a      BIGINT;
    rol_b      BIGINT;
    req_a      BIGINT;
    req_b      BIGINT;
    oportunidad BIGINT;
BEGIN
    -- Cliente A: cafeteria buscando en Miraflores.
    INSERT INTO persona (organizacion_id, tipo_persona, tipo_documento, numero_documento,
                         nombres_o_razon_social, telefono, correo, consentimiento_uso_dato)
    VALUES (legado, 'N', 'D', '45781234', 'Mariana Delgado Ruiz', '987654321',
            'mariana.delgado@demo.test', TRUE)
    RETURNING id_persona INTO persona_a;

    INSERT INTO persona_rol (organizacion_id, id_persona, tipo_rol, vigencia_desde)
    VALUES (legado, persona_a, 'CLIENTE', DATE '2026-06-01')
    RETURNING id_persona_rol INTO rol_a;

    INSERT INTO detalle_cliente (id_persona_rol, organizacion_id, rubro_comercial, consentimiento_contacto)
    VALUES (rol_a, legado, 'Cafeteria', TRUE);

    INSERT INTO requerimiento_cliente (organizacion_id, id_rol_cliente, rubro, tipo_inmueble,
                                       renta_min, renta_max, moneda, metraje_min, metraje_max,
                                       estado, observaciones)
    VALUES (legado, rol_a, 'Cafeteria', 'LOCAL_COMERCIAL', 3000, 12000, 'PEN', 80, 200,
            'ACTIVO', 'Busca local a pie de calle con buen transito.')
    RETURNING id_requerimiento INTO req_a;

    INSERT INTO requerimiento_distrito (id_requerimiento, id_distrito)
    SELECT req_a, d.id_distrito FROM distrito d WHERE d.nombre IN ('Miraflores', 'San Isidro');

    -- Cliente B: retail juridico con busqueda mas amplia.
    INSERT INTO persona (organizacion_id, tipo_persona, tipo_documento, numero_documento,
                         nombres_o_razon_social, telefono, correo, consentimiento_uso_dato)
    VALUES (legado, 'J', 'R', '20551234567', 'Retail Andino SAC', '014567890',
            'contacto@retailandino.test', TRUE)
    RETURNING id_persona INTO persona_b;

    INSERT INTO persona_rol (organizacion_id, id_persona, tipo_rol, vigencia_desde)
    VALUES (legado, persona_b, 'CLIENTE', DATE '2026-06-15')
    RETURNING id_persona_rol INTO rol_b;

    INSERT INTO detalle_cliente (id_persona_rol, organizacion_id, rubro_comercial, consentimiento_contacto)
    VALUES (rol_b, legado, 'Retail', TRUE);

    INSERT INTO requerimiento_cliente (organizacion_id, id_rol_cliente, rubro, tipo_inmueble,
                                       renta_min, renta_max, moneda, metraje_min,
                                       estado, observaciones)
    VALUES (legado, rol_b, 'Retail', 'LOCAL_COMERCIAL', 5000, 20000, 'PEN', 100,
            'ACTIVO', 'Expansion de tiendas para el proximo trimestre.')
    RETURNING id_requerimiento INTO req_b;

    INSERT INTO requerimiento_distrito (id_requerimiento, id_distrito)
    SELECT req_b, d.id_distrito FROM distrito d WHERE d.nombre = 'Miraflores';

    -- Oportunidad ABIERTA del cliente A sobre la captacion demo + visita programada.
    INSERT INTO oportunidad_comercial (organizacion_id, codigo_oportunidad, estado, id_rol_cliente,
                                       id_captacion, id_rol_agente, observaciones,
                                       fecha_registro, fecha_primera_consulta)
    VALUES (legado, 'OP-0001', 'A', rol_a, id_cap, rol_agente,
            'Interesada tras ver el anuncio en la web propia.',
            TIMESTAMPTZ '2026-07-10 11:00:00-05', TIMESTAMPTZ '2026-07-10 11:00:00-05')
    RETURNING id_oportunidad INTO oportunidad;

    INSERT INTO visita (organizacion_id, id_oportunidad, id_rol_agente, fecha_visita, hora_visita,
                        estado, observaciones)
    VALUES (legado, oportunidad, rol_agente, DATE '2026-07-30', TIME '16:00',
            'P', 'Primera visita coordinada con la clienta.');

    INSERT INTO interaccion_comercial (organizacion_id, contexto, id_oportunidad, id_rol_agente,
                                       canal_contacto, resultado, observaciones, fecha_hora)
    VALUES (legado, 'OPORTUNIDAD', oportunidad, rol_agente, 'W', 'INTERESADO',
            'Confirmo interes y disponibilidad para visitar.',
            TIMESTAMPTZ '2026-07-10 11:30:00-05');
END $$;
