-- =====================================================================
-- V83 - LA PROCEDENCIA DEL DATO GOBERNADO  (microcorte 4.P, D-4P-1)
--
-- Hasta hoy la procedencia se registraba DEL ACTO y no DEL DATO. Un solo PUT
-- puede cambiar `tipo_acceso` (lo vio el agente en una visita), `zonificacion`
-- (lo dice un certificado) y `vigilancia` (lo dijo el propietario), y el evento
-- de ese PUT --carga util `{"idPropiedad": N}`-- no explica ninguna de las tres.
--
-- Y peor: una edicion o un borrado DESTRUIAN el pasado. `uq_atributo_propiedad_clave`
-- deja una fila por (propiedad, clave), asi que editar es un UPDATE que pisa; y
-- retirar es un DELETE fisico que no deja nada. Un multivalor se reescribe entero
-- --`borrarDe(ancla)` y un `save` por opcion-- asi que el conjunto anterior
-- desaparecia sin rastro.
--
-- ---------------------------------------------------------------------
-- POR QUE UNA TABLA PROPIA Y NO COLUMNAS  (D-4P-1 seccion 1, medido)
--
-- Se midieron tres alternativas contra las 12 invariantes del encargo:
--
--   A1 columnas en atributo_propiedad/atributo_encargo -> IMPOSIBLE por cinco
--      razones medidas. Las 4 claves ESTRUCTURAL (metraje_total, piso,
--      partida_registral, oficina_registral) NO CREAN FILA -- su autoridad es
--      una columna de `propiedad` --, asi que una columna en la tabla de
--      atributos no puede darles linaje. Y `uq_..._clave` rechaza la segunda
--      fila, con lo que editar seguiria pisando.
--
--   A2 reutilizar historial_estado -> IMPOSIBLE por forma. No tiene columna
--      `clave` (direcciona por id_entidad), y `estado_anterior`/`estado_nuevo`
--      son varchar(1): no cabe A_PIE_DE_CALLE (14), ni un decimal, ni una fecha,
--      ni un conjunto.
--
--   A3 tabla propia append-only -> sostiene las 12. Es la elegida.
--
-- La clave de A3 es la IDENTIDAD LOGICA: el rastro se direcciona por
-- (organizacion_id, sujeto, id_agregado, clave) y JAMAS por el id de la fila
-- vigente. Eso es lo que mete las cinco superficies de escritura en un solo
-- mecanismo -- incluidas las dos que no tienen fila: la ESTRUCTURAL (que escribe
-- una columna del agregado) y la RETIRADA (donde la fila vigente desaparece).
--
-- ---------------------------------------------------------------------
-- DOS EJES, NUNCA UNO
--
--   naturaleza    DECLARADO | OBSERVADO | INFERIDO   a veces solo lo sabe quien captura
--   canal/origen  SPA | WHATSAPP | API | SISTEMA     lo sabe el Core, siempre
--
-- Son independientes: `naturaleza=DECLARADO` con `canal=WHATSAPP` significa
-- "alguien lo declaro y el asistente lo capturo", y `naturaleza=OBSERVADO` con
-- `canal=SPA` significa "un profesional afirma haberlo visto".
--
-- **NULL NO ES UNA CUARTA NATURALEZA.** No existe DESCONOCIDO, ni aqui ni en el
-- CHECK ni en el cable, y la razon no es de nombres:
--
--   naturaleza = NULL      -> NO sabemos COMO se obtuvo el hecho
--   naturaleza = INFERIDO  -> SI lo sabemos: por una inferencia
--
-- Un DESCONOCIDO en el vocabulario colapsaria las dos, y "no consta como se
-- supo" no es un metodo de obtencion. La ausencia se representa como ausencia.
-- El resto del registro sigue teniendo procedencia OPERACIONAL -- quien, cuando,
-- por que canal --, que es cosa del otro eje.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. El rastro de un valor gobernado.
--
-- Append-only. Una fila por ESCRITURA, no por valor: la tabla de atributos
-- sigue siendo el ESTADO VIGENTE y esto es la HISTORIA.
-- ---------------------------------------------------------------------
CREATE TABLE rastro_valor_gobernado (
    id_rastro             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id       BIGINT        NOT NULL REFERENCES organizacion (id_organizacion),

    -- La identidad LOGICA. No hay FK al agregado y es deliberado: la columna
    -- apunta a `propiedad` o a `captacion` segun el sujeto, igual que
    -- `evento_dominio.entidad_id` y `historial_estado.id_entidad`, y una FK no
    -- puede ser polimorfica. Colgar del `id_atributo_propiedad` habria sido la
    -- alternativa "con FK", y es exactamente la que pierde la retirada: al
    -- borrarse la fila vigente se llevaria por delante su propio linaje.
    sujeto                VARCHAR(9)    NOT NULL,
    id_agregado           BIGINT        NOT NULL,
    clave                 VARCHAR(60)   NOT NULL,
    verbo                 VARCHAR(8)    NOT NULL,

    -- El valor que QUEDA tras la escritura. Espejo exacto de las columnas de
    -- `atributo_propiedad` tras V72: un tipo de dato significa lo mismo lo lleve
    -- quien lo lleve. Vacio en una RETIRADA, porque no queda ninguno.
    valor_texto           TEXT,
    valor_numero          NUMERIC(14,4),
    valor_booleano        BOOLEAN,
    valor_fecha           DATE,
    valor_moneda          VARCHAR(3),
    -- Un LISTA_MULTIPLE no cabe en un escalar: sus elementos viven en
    -- `rastro_valor_opcion`, y esta bandera dice que hay que mirar alli.
    es_multivalor         BOOLEAN       NOT NULL DEFAULT false,

    -- El valor que el Core ENCONTRO justo antes de escribir. Es una
    -- CONSTATACION DEL ESTADO HALLADO, no una genesis: no dice cuando nacio ese
    -- valor, ni quien lo origino, ni por que canal, ni como se conocio. Solo
    -- dice lo unico cierto -- "en el momento de esta escritura, aqui habia
    -- esto" --, que es lo que la propia operacion presencia.
    --
    -- Es lo que hace que la PRIMERA modificacion de un valor legado conserve el
    -- anterior sin atribuirle una procedencia que nadie puede demostrar
    -- (D-4P-1 seccion 3 bis.1). Vale para las cuatro claves ESTRUCTURAL, cuyo
    -- valor historico vive en una columna de `propiedad` sin fecha propia, y
    -- para cualquier fila de `atributo_propiedad` anterior a esta migracion.
    hallado_texto         TEXT,
    hallado_numero        NUMERIC(14,4),
    hallado_booleano      BOOLEAN,
    hallado_fecha         DATE,
    hallado_moneda        VARCHAR(3),

    -- EJE 1: como se conocio el hecho. Opcional POR VALOR y nunca deducida.
    naturaleza            VARCHAR(9),

    -- EJE 2: las nueve dimensiones de `Procedencia` (V59). No se duplican aqui
    -- por gusto: se ENGANCHAN al valor. `evento_dominio` las persiste para la
    -- OPERACION y sigue haciendolo -- son dos preguntas distintas y ninguna
    -- sustituye a la otra.
    canal                 VARCHAR(20),
    agente                VARCHAR(30),
    agente_modelo         VARCHAR(60),
    agente_modelo_version VARCHAR(40),
    conversacion_id       VARCHAR(64),
    turno_id              VARCHAR(64),
    mensaje_id            VARCHAR(128),
    peticion              TEXT,
    herramienta           VARCHAR(60),

    -- Quien y cuando. Lo deriva el Core de la sesion: el usuario no lo teclea.
    id_persona_rol        BIGINT,
    rol_actor             VARCHAR(20),
    registrado_en         TIMESTAMPTZ   NOT NULL DEFAULT now(),

    -- Cuando se observo el hecho, si se sabe. Distinto de `registrado_en`:
    -- una visita del martes anotada el viernes vale por el martes.
    observado_en          DATE,
    -- El puntero a la prueba: un documento, una foto, una columna de la que se
    -- transcribio. Texto libre a proposito -- las fuentes reales son un hecho
    -- del campo y nadie las ha inventariado.
    evidencia_ref         VARCHAR(300),
    -- Cuanto se fia el que infirio. Solo tiene sentido con INFERIDO.
    confianza             NUMERIC(4,3),

    CONSTRAINT ck_rastro_sujeto CHECK (sujeto IN ('PROPIEDAD', 'ENCARGO')),
    CONSTRAINT ck_rastro_verbo  CHECK (verbo IN ('ALTA', 'EDICION', 'RETIRADA')),

    -- El vocabulario cerrado de la naturaleza. Tres valores y NULL. Anadir un
    -- DESCONOCIDO aqui seria convertir "no consta" en un metodo de obtencion.
    CONSTRAINT ck_rastro_naturaleza
        CHECK (naturaleza IS NULL OR naturaleza IN ('DECLARADO', 'OBSERVADO', 'INFERIDO')),

    -- Un INFERIDO no puede existir sin decir QUIEN infirio, con QUE modelo, en
    -- que VERSION y con cuanta CONFIANZA. Sin eso no es una inferencia: es una
    -- afirmacion sin autor, y en dos meses nadie puede revisarla ni retirarla
    -- cuando el modelo resulte estar equivocado.
    CONSTRAINT ck_rastro_inferido_completo
        CHECK (naturaleza <> 'INFERIDO'
               OR (agente IS NOT NULL AND agente_modelo IS NOT NULL
                   AND agente_modelo_version IS NOT NULL AND confianza IS NOT NULL)),
    CONSTRAINT ck_rastro_confianza
        CHECK (confianza IS NULL OR (confianza >= 0 AND confianza <= 1)),

    CONSTRAINT ck_rastro_moneda
        CHECK (valor_moneda IS NULL OR valor_moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_rastro_hallado_moneda
        CHECK (hallado_moneda IS NULL OR hallado_moneda IN ('PEN', 'USD')),

    -- La forma del valor escrito, verbo a verbo:
    --   RETIRADA -> ninguno: no queda valor, y el que se quito esta en `hallado_*`
    --   multivalor -> ninguno escalar: sus elementos viven en la tabla hija
    --   resto -> exactamente uno
    CONSTRAINT ck_rastro_forma_del_valor CHECK (
        CASE
            WHEN verbo = 'RETIRADA' THEN
                num_nonnulls(valor_texto, valor_numero, valor_booleano, valor_fecha) = 0
            WHEN es_multivalor THEN
                num_nonnulls(valor_texto, valor_numero, valor_booleano, valor_fecha) = 0
            ELSE
                num_nonnulls(valor_texto, valor_numero, valor_booleano, valor_fecha) = 1
        END),
    CONSTRAINT ck_rastro_moneda_con_monto
        CHECK (valor_moneda IS NULL OR valor_numero IS NOT NULL),

    -- Un ALTA es la primera escritura de esa clave: no habia nada que hallar.
    CONSTRAINT ck_rastro_hallado_solo_si_habia CHECK (
        verbo <> 'ALTA'
        OR num_nonnulls(hallado_texto, hallado_numero, hallado_booleano, hallado_fecha) = 0),
    CONSTRAINT ck_rastro_hallado_un_valor CHECK (
        num_nonnulls(hallado_texto, hallado_numero, hallado_booleano, hallado_fecha) <= 1),
    CONSTRAINT ck_rastro_hallado_moneda_con_monto
        CHECK (hallado_moneda IS NULL OR hallado_numero IS NOT NULL)
);

COMMENT ON TABLE rastro_valor_gobernado IS
    'De donde salio ESTA afirmacion concreta. Append-only: una fila por '
    'escritura. Se direcciona por (organizacion, sujeto, agregado, clave) y '
    'NUNCA por el id de la fila vigente -- por eso una retirada, un multivalor y '
    'una clave ESTRUCTURAL (que no crea fila) dejan linaje igual que un escalar.';

COMMENT ON COLUMN rastro_valor_gobernado.naturaleza IS
    'Como se conocio el hecho: DECLARADO, OBSERVADO o INFERIDO. NULL significa '
    'que NO CONSTA, y no es una cuarta clase de evidencia. El Core JAMAS la '
    'deduce del canal, del actor ni del endpoint.';

COMMENT ON COLUMN rastro_valor_gobernado.hallado_texto IS
    'Constatacion del estado hallado, no genesis: lo que el Core encontro justo '
    'antes de escribir. No se le atribuye ni canal, ni actor, ni fecha de '
    'nacimiento, ni naturaleza.';

COMMENT ON COLUMN rastro_valor_gobernado.canal IS
    'Por donde entro la peticion. Independiente de `naturaleza`: son dos ejes.';

-- La FK compuesta que necesita la tabla hija, igual que `uq_atributo_propiedad_org`
-- (V72): sin ella un elemento de un conjunto podria colgar del rastro de otra
-- corredora.
ALTER TABLE rastro_valor_gobernado
    ADD CONSTRAINT uq_rastro_valor_org UNIQUE (organizacion_id, id_rastro);

-- La consulta que sostiene todo: la historia de UNA clave logica, en orden.
CREATE INDEX ix_rastro_valor_identidad
    ON rastro_valor_gobernado (organizacion_id, sujeto, id_agregado, clave, id_rastro);
-- Y la del gate del cutover: que hay a cada lado de la frontera.
CREATE INDEX ix_rastro_valor_registrado
    ON rastro_valor_gobernado (organizacion_id, registrado_en);

-- ---------------------------------------------------------------------
-- 2. El CONJUNTO de un multivalor -- entero, no la diferencia.
--
-- Espejo de `atributo_propiedad_opcion` / `atributo_encargo_opcion`, cuyas
-- claves primarias son (id_atributo, valor): un conjunto SIN ORDEN y SIN
-- DUPLICADOS. Conservar el conjunto ES conservar el dato completo.
--
-- `momento` es lo que permite que una EDICION guarde las dos versiones: el
-- conjunto que habia --lo unico que el borrado destruia-- y el que queda. Un
-- diff no sirve: "quito CASETA_24H" no dice que habia antes si el anterior era
-- legado y nadie lo escribio nunca.
-- ---------------------------------------------------------------------
CREATE TABLE rastro_valor_opcion (
    organizacion_id BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_rastro       BIGINT      NOT NULL,
    momento         VARCHAR(7)  NOT NULL,
    valor           VARCHAR(40) NOT NULL,

    PRIMARY KEY (id_rastro, momento, valor),
    CONSTRAINT fk_rastro_opcion_rastro
        FOREIGN KEY (organizacion_id, id_rastro)
        REFERENCES rastro_valor_gobernado (organizacion_id, id_rastro),
    CONSTRAINT ck_rastro_opcion_momento CHECK (momento IN ('HALLADO', 'ESCRITO'))
);

COMMENT ON TABLE rastro_valor_opcion IS
    'Los N elementos de un LISTA_MULTIPLE en una escritura. HALLADO = el '
    'conjunto que el Core encontro; ESCRITO = el que queda. Los dos enteros, '
    'nunca su diferencia.';

CREATE INDEX ix_rastro_opcion_organizacion ON rastro_valor_opcion (organizacion_id);

-- ---------------------------------------------------------------------
-- 3. El append-only, dicho por la base.
--
-- Mismo patron que `tg_observacion_append_only` (V76). El trigger NO ESCRIBE:
-- solo impide. Escribe el servicio, en la misma transaccion que el valor.
--
-- Una regla que solo vive en el servicio se rodea con un psql, y aqui rodearla
-- no rompe una fila: borra la unica constancia de por que un dato dice lo que
-- dice.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION proteger_rastro_de_procedencia()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'El linaje de un valor gobernado no se % : es un hecho fechado. Si el '
        'valor cambio, escribelo otra vez -- las dos filas juntas son las que '
        'cuentan la historia.', lower(TG_OP)
        USING ERRCODE = 'check_violation';
END $$;

CREATE TRIGGER tg_rastro_valor_append_only
    BEFORE UPDATE OR DELETE ON rastro_valor_gobernado
    FOR EACH ROW EXECUTE FUNCTION proteger_rastro_de_procedencia();

CREATE TRIGGER tg_rastro_opcion_append_only
    BEFORE UPDATE OR DELETE ON rastro_valor_opcion
    FOR EACH ROW EXECUTE FUNCTION proteger_rastro_de_procedencia();

-- ---------------------------------------------------------------------
-- 4. LA FRONTERA DE GARANTIA -- explicita, no al criterio de quien consulte.
--
--   ANTES de esta migracion -> puede existir legado SIN linaje. NO es defecto.
--   DESPUES                 -> una escritura gobernada SIN linaje ES UN DEFECTO.
--
-- Se hornea el instante de instalacion en el cuerpo de la funcion en vez de
-- guardarlo en una fila, por dos razones: una fila se puede UPDATEar y esta
-- frontera no debe moverse nunca, y un gate necesita poder preguntarla desde
-- SQL sin acordarse de que tabla mirar.
-- ---------------------------------------------------------------------
DO $$
BEGIN
    EXECUTE format(
        'CREATE OR REPLACE FUNCTION frontera_de_linaje() RETURNS timestamptz '
        'LANGUAGE sql IMMUTABLE AS $f$ SELECT %L::timestamptz $f$', now());
END $$;

COMMENT ON FUNCTION frontera_de_linaje() IS
    'El cutover de 4.P (V83). Antes de este instante puede haber valores '
    'gobernados sin linaje y no es defecto; despues, una escritura gobernada '
    'sin linaje SI lo es.';

-- ---------------------------------------------------------------------
-- 5. GENESIS SELECTIVA -- ni backfill, ni ausencia por norma.
--
-- La regla congelada: genesis SOLO donde la procedencia sea REALMENTE
-- demostrable, fila a fila. Donde no lo sea, ninguna. Y en toda genesis que se
-- escriba, `naturaleza` AUSENTE: la procedencia operacional puede ser
-- demostrable; como se conocio el hecho, casi nunca lo es.
--
-- ---------------------------------------------------------------------
-- LO QUE **NO** SE SIEMBRA, Y POR QUE  (medido al implementar)
--
-- (a) Las 70 filas que V48 copio de las columnas legadas eran EL CASO
--     CANDIDATO, y la prueba NO SE SOSTIENE. La unica forma de identificarlas
--     seria comparar su `fecha_creacion` (timestamptz) con
--     `flyway_schema_history.installed_on`, que es `timestamp WITHOUT time zone`
--     -- su valor depende de la zona horaria de la sesion que corrio la
--     migracion, y esa zona no se guarda en ninguna parte. Medido el 2026-08-25
--     en las dos bases de este proyecto:
--
--       controllocal_dev          V48 installed_on 2026-08-17 23:23:23.526438
--                                 filas            2026-08-17 23:23:23.570485+00   (+44 ms)
--       controllocal_repositorios V48 installed_on 2026-08-18 04:58:49.966623
--                                 filas            2026-08-18 09:58:50.001402+00   (+5 h 35 ms)
--
--     Cinco horas de diferencia entre dos bases del mismo repositorio, porque
--     una la migro el contenedor (UTC) y la otra una JVM en America/Lima. Un
--     predicado escrito sobre esa comparacion parece cierto en la base en la
--     que se probo y miente en la de al lado. Asi que esas filas SE QUEDAN SIN
--     GENESIS, y queda dicho.
--
-- (b) Las cuatro claves ESTRUCTURAL no reciben genesis retroactiva (decision
--     del titular, E2). No hay fecha por valor, y nada demuestra que el
--     `metraje` lo escribiera el sistema y no un agente desde el SPA. Su linaje
--     empieza en la primera escritura posterior a esta migracion, que si es
--     completa -- y esa conservara el valor anterior en `hallado_*`.
--
-- ---------------------------------------------------------------------
-- LO QUE SI SE SIEMBRA
--
-- Las filas cuyo acto de escritura dejo un `evento_dominio` CORRELACIONABLE, y
-- solo con lo que ese evento demuestra. La correlacion exige las tres cosas:
--
--   * mismo tenant y mismo agregado;
--   * el evento ocurrio DENTRO de la ventana de la transaccion que creo la fila
--     (`fecha_creacion` es el `now()` de esa transaccion, y `ocurrido_en` un
--     instante posterior dentro de ella);
--   * **es el UNICO** evento de esa ventana. Si hay dos, cual de ellos escribio
--     esta clave no se puede saber, y adivinarlo seria inventar.
--
-- Lo que se afirma de cada fila sembrada es solo lo comprobable:
-- `registrado_en` = su propio `fecha_creacion` (una columna suya, no una
-- deduccion), y canal/agente/conversacion/actor = los del evento. `rol_actor`
-- queda NULL: el evento guarda el id del rol, no con que banda actuo.
-- `naturaleza` queda NULL. `verbo` es ALTA porque `fecha_creacion` es, por
-- construccion, el instante en que esa clave recibio valor por primera vez.
--
-- QUE NO GARANTIZA ESTO: el vinculo fila-evento no esta REGISTRADO en ninguna
-- parte -- la carga util del evento es `{"idPropiedad": N}` y no nombra la
-- clave --, asi que la correlacion es una reconstruccion, no un dato. Se exige
-- unicidad justamente para que solo se reconstruya cuando no hay eleccion
-- posible.
-- ---------------------------------------------------------------------
INSERT INTO rastro_valor_gobernado (
        organizacion_id, sujeto, id_agregado, clave, verbo,
        valor_texto, valor_numero, valor_booleano, valor_fecha, valor_moneda,
        es_multivalor, canal, agente, agente_modelo, agente_modelo_version,
        conversacion_id, turno_id, mensaje_id, herramienta,
        id_persona_rol, registrado_en, evidencia_ref)
SELECT a.organizacion_id, 'PROPIEDAD', a.id_propiedad, a.clave, 'ALTA',
       a.valor_texto, a.valor_numero, a.valor_booleano, a.valor_fecha, a.valor_moneda,
       -- Una fila SIN escalar es un ancla de multivalor por definicion
       -- (`ck_atributo_un_valor` admite cero desde V72), tenga o no opciones:
       -- un conjunto vacio es un conjunto, y decir lo contrario dejaria la fila
       -- sin ninguna forma valida.
       num_nonnulls(a.valor_texto, a.valor_numero, a.valor_booleano, a.valor_fecha) = 0,
       e.canal, e.agente, e.agente_modelo, e.agente_modelo_version,
       e.conversacion_id, e.turno_id, e.mensaje_id, e.herramienta,
       e.id_persona_rol, a.fecha_creacion,
       -- La evidencia: el evento que demuestra el acto y, cuando lo hay, la
       -- fuente TEXTUAL de la que se transcribio el valor (seccion 6).
       'evento_dominio#' || e.id_evento || coalesce(
           (SELECT ' + propiedad.descripcion'
              FROM (VALUES ('LOC-D001',  'A_PIE_DE_CALLE',   'a pie de calle'),
                           ('LOC-0002',  'GALERIA_INTERIOR', 'en galeria')) AS t(codigo, valor, frase)
             WHERE t.codigo = p.codigo
               AND a.clave = 'tipo_acceso'
               AND a.valor_texto = t.valor
               AND lower(coalesce(p.descripcion, '')) LIKE '%' || t.frase || '%'), '')
  FROM atributo_propiedad a
  JOIN propiedad p ON p.id_propiedad = a.id_propiedad
  JOIN LATERAL (
        SELECT ev.*
          FROM evento_dominio ev
         WHERE ev.organizacion_id = a.organizacion_id
           AND ev.entidad_tipo = 'PROPIEDAD'
           AND ev.entidad_id = a.id_propiedad
           AND ev.ocurrido_en >= a.fecha_creacion
           AND ev.ocurrido_en <  a.fecha_creacion + interval '5 seconds'
       ) e ON true
 WHERE (SELECT count(*) FROM evento_dominio ev2
         WHERE ev2.organizacion_id = a.organizacion_id
           AND ev2.entidad_tipo = 'PROPIEDAD'
           AND ev2.entidad_id = a.id_propiedad
           AND ev2.ocurrido_en >= a.fecha_creacion
           AND ev2.ocurrido_en <  a.fecha_creacion + interval '5 seconds') = 1;

-- El gemelo del ENCARGO, desde el primer commit. `atributo_encargo` tiene cero
-- filas en la cartera de desarrollo, asi que aqui esto no sembrara nada -- y
-- escribirlo igual es lo que impide que la simetria se pierda el dia que si las
-- tenga. La asimetria que el encargo teme YA existia: pactar una condicion no
-- emite ni el evento de operacion que si emite editar una propiedad, asi que
-- la correlacion solo puede darse contra el `ENCARGO_ABIERTO` del alta.
INSERT INTO rastro_valor_gobernado (
        organizacion_id, sujeto, id_agregado, clave, verbo,
        valor_texto, valor_numero, valor_booleano, valor_fecha, valor_moneda,
        es_multivalor, canal, agente, agente_modelo, agente_modelo_version,
        conversacion_id, turno_id, mensaje_id, herramienta,
        id_persona_rol, registrado_en, evidencia_ref)
SELECT a.organizacion_id, 'ENCARGO', a.id_captacion, a.clave, 'ALTA',
       a.valor_texto, a.valor_numero, a.valor_booleano, a.valor_fecha, a.valor_moneda,
       num_nonnulls(a.valor_texto, a.valor_numero, a.valor_booleano, a.valor_fecha) = 0,
       e.canal, e.agente, e.agente_modelo, e.agente_modelo_version,
       e.conversacion_id, e.turno_id, e.mensaje_id, e.herramienta,
       e.id_persona_rol, a.fecha_creacion,
       'evento_dominio#' || e.id_evento
  FROM atributo_encargo a
  JOIN LATERAL (
        SELECT ev.*
          FROM evento_dominio ev
         WHERE ev.organizacion_id = a.organizacion_id
           AND ev.entidad_tipo = 'CAPTACION'
           AND ev.entidad_id = a.id_captacion
           AND ev.ocurrido_en >= a.fecha_creacion
           AND ev.ocurrido_en <  a.fecha_creacion + interval '5 seconds'
       ) e ON true
 WHERE (SELECT count(*) FROM evento_dominio ev2
         WHERE ev2.organizacion_id = a.organizacion_id
           AND ev2.entidad_tipo = 'CAPTACION'
           AND ev2.entidad_id = a.id_captacion
           AND ev2.ocurrido_en >= a.fecha_creacion
           AND ev2.ocurrido_en <  a.fecha_creacion + interval '5 seconds') = 1;

-- Y el conjunto de los multivalores sembrados, entero.
INSERT INTO rastro_valor_opcion (organizacion_id, id_rastro, momento, valor)
SELECT r.organizacion_id, r.id_rastro, 'ESCRITO', o.valor
  FROM rastro_valor_gobernado r
  JOIN atributo_propiedad a
    ON a.organizacion_id = r.organizacion_id
   AND a.id_propiedad = r.id_agregado
   AND a.clave = r.clave
  JOIN atributo_propiedad_opcion o ON o.id_atributo_propiedad = a.id_atributo_propiedad
 WHERE r.sujeto = 'PROPIEDAD' AND r.es_multivalor;

INSERT INTO rastro_valor_opcion (organizacion_id, id_rastro, momento, valor)
SELECT r.organizacion_id, r.id_rastro, 'ESCRITO', o.valor
  FROM rastro_valor_gobernado r
  JOIN atributo_encargo a
    ON a.organizacion_id = r.organizacion_id
   AND a.id_captacion = r.id_agregado
   AND a.clave = r.clave
  JOIN atributo_encargo_opcion o ON o.id_atributo_encargo = a.id_atributo_encargo
 WHERE r.sujeto = 'ENCARGO' AND r.es_multivalor;

-- ---------------------------------------------------------------------
-- 6. La fuente TEXTUAL de las dos transcripciones documentadas.
--    (Va DENTRO del INSERT de arriba, no en un UPDATE posterior: la tabla es
--     append-only y su trigger rechaza el UPDATE, con razon.)
--
-- `LOC-D001` y `LOC-0002` recibieron su `tipo_acceso` transcribiendo LITERALMENTE
-- una frase que ya estaba en `propiedad.descripcion` -- «Local a pie de calle con
-- vitrina» y «Local en galeria del centro» --, no capturandolo en una visita.
-- El evento de esa edicion demuestra el ACTO (quien, cuando, por que canal) y no
-- dice nada de la FUENTE, asi que sin esto los dos valores quedarian
-- indistinguibles de uno observado.
--
-- **Aqui no se miente en ninguna direccion.** Se afirma de donde se copio el
-- texto -- que es comprobable, y esta migracion LO COMPRUEBA antes de afirmarlo:
-- si la descripcion ya no contiene la frase, no anade nada -- y NO se afirma
-- quien origino esa descripcion, que nadie sabe. Por eso `naturaleza` sigue
-- ausente: no se les atribuye DECLARADO, porque el sistema no puede demostrar
-- que hubiera una declaracion de contraparte.
--
-- La lista es corta y explicita a proposito, como el `codigo IN (...)` de V14 y
-- V76: son dos hechos concretos de una cartera concreta, no una regla.
--
-- ---------------------------------------------------------------------
-- 7. Lo que esta migracion NO hace, dicho para que no se busque.
--
-- No anade ninguna columna a `atributo_propiedad` ni a `atributo_encargo`: esas
-- dos tablas siguen siendo el ESTADO VIGENTE y no cambian ni una fila.
--
-- No pone la procedencia NOT NULL en ninguna de las cuatro tablas de valor, y
-- es una DECISION, no una concesion: seis suites E2E y `gate-modelo-universal.sql`
-- escriben por SQL directo, deliberadamente, para probar los triggers de la base
-- intentando romperlos. Un NOT NULL alli convertiria el gate en rehen del
-- servicio. La invariante "toda escritura gobernada deja linaje" se sostiene EN
-- LA FRONTERA DEL SERVICIO, con un test de arquitectura -- y lo que un INSERT
-- manual escriba no lo cubre nadie, ni aqui ni en el codigo.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    sembradas bigint;
    huerfanas bigint;
BEGIN
    SELECT count(*) INTO sembradas FROM rastro_valor_gobernado;
    SELECT count(*) INTO huerfanas FROM rastro_valor_gobernado WHERE naturaleza IS NOT NULL;
    IF huerfanas > 0 THEN
        RAISE EXCEPTION 'V83: % filas de genesis con naturaleza declarada. La genesis '
                        'nunca dice COMO se conocio el hecho.', huerfanas;
    END IF;
    RAISE NOTICE 'V83: linaje de valor gobernado en marcha; % filas de genesis demostrable, '
                 'frontera en %', sembradas, frontera_de_linaje();
END $$;
