-- =====================================================================
-- V8: vertical F4 - SOLICITUD, DOCUMENTOS, EVALUACION, CONTRATO Y
-- COMISION (contrato congelado en
-- docs/ai/contrato-congelado-f4-solicitud.md).
--  * Es la vertical que CIERRA el ciclo: el contrato registrado sobre una
--    solicitud aprobada es lo que cierra la oportunidad como exitosa
--    (por eso /oportunidades/{id}/cierre-exitoso responde 400 para
--    siempre; el cierre no lo produce un boton).
--  * tipo_documento_requerido es CATALOGO GLOBAL (como distrito): no
--    lleva organizacion_id y debe declararse global en
--    ArquitecturaTenancyTest. El resto es privado del tenant (V6):
--    organizacion_id NOT NULL sin DEFAULT, unicidades por organizacion y
--    FK compuestas con el tenant.
--  * Los ids 1..8 del catalogo son PARTE DEL CABLE: el enum
--    TipoDocumentoSolicitud de la v1 mapea codigo <-> idCatalogo por
--    posicion (I=1, R=2, V=3, P=4, E=5, G=6, D=7, O=8). No reordenar.
--  * Vocabulario del cable: solicitud G/E/O/A/R/D/C, documento R/O/V con
--    revision P/C/O, evaluacion A/R/O y tipo P/O/F, contrato
--    P/D/V/R/F/S/A. OJO: comision y forma de pago NO son CHAR(1) — la v1
--    emite el NOMBRE del enum (ver §1 del contrato), igual que F3.
--  * Los codigos de entidad_tipo (SOLICITUD_ALQUILER, DOCUMENTO_SOLICITUD,
--    EVALUACION, CONTRATO_ALQUILER, COMISION_LIQUIDACION) ya estan
--    sembrados desde V2.
-- =====================================================================

-- Falta desde V6.4: la evaluacion necesita la FK compuesta contra el broker.
ALTER TABLE detalle_broker ADD CONSTRAINT uq_detalle_broker_org UNIQUE (organizacion_id, id_persona_rol);

-- ---------------------------------------------------------------------
-- Catalogo GLOBAL de tipos de documento requeridos para el alquiler.
-- tipo_operacion siempre 'A' (alquiler): la v1 ya lo restringe asi.
-- ---------------------------------------------------------------------
CREATE TABLE tipo_documento_requerido (
    id_tipo_documento_requerido BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_operacion              VARCHAR(1)  NOT NULL,
    tipo_documento              VARCHAR(60) NOT NULL,
    obligatorio                 BOOLEAN     NOT NULL,
    activo                      BOOLEAN     NOT NULL,
    descripcion                 VARCHAR(200),
    CONSTRAINT ck_tipo_documento_operacion CHECK (tipo_operacion = 'A'),
    CONSTRAINT uq_tipo_documento_operacion UNIQUE (tipo_operacion, tipo_documento)
);

-- Los ids son explicitos porque el cable los usa (ver cabecera).
INSERT INTO tipo_documento_requerido
    (id_tipo_documento_requerido, tipo_operacion, tipo_documento, obligatorio, activo, descripcion) VALUES
    (1, 'A', 'Documento de identidad',  TRUE,  TRUE, 'Documento de identidad del solicitante'),
    (2, 'A', 'Ficha o constancia RUC',  TRUE,  TRUE, 'Ficha RUC vigente para persona juridica'),
    (3, 'A', 'Vigencia de poder',       TRUE,  TRUE, 'Vigencia de poder del representante'),
    (4, 'A', 'Poder de representacion', FALSE, TRUE, 'Poder que autoriza la representacion'),
    (5, 'A', 'Sustento economico',      TRUE,  TRUE, 'Documentos de solvencia o ingresos'),
    (6, 'A', 'Documento de garantia',   FALSE, TRUE, 'Documento asociado a la garantia'),
    (7, 'A', 'Declaracion jurada',      FALSE, TRUE, 'Declaracion jurada complementaria'),
    (8, 'A', 'Otro',                    FALSE, TRUE, 'Otro documento solicitado');

-- La secuencia de identidad arranca despues de los ids sembrados.
ALTER TABLE tipo_documento_requerido ALTER COLUMN id_tipo_documento_requerido RESTART WITH 9;

-- ---------------------------------------------------------------------
-- Solicitud de alquiler: la oferta formal del interesado sobre la
-- oportunidad. UNA por oportunidad (unicidad del cable v1).
-- La captacion NO se duplica aqui: se deriva por la oportunidad.
-- ---------------------------------------------------------------------
CREATE TABLE solicitud_alquiler (
    id_solicitud               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id            BIGINT        NOT NULL REFERENCES organizacion (id_organizacion),
    codigo_solicitud           VARCHAR(20)   NOT NULL,
    fecha_registro             DATE          NOT NULL,
    monto_propuesto            NUMERIC(12,2) NOT NULL,
    plazo_tentativo            VARCHAR(50),
    observaciones              TEXT,
    estado                     VARCHAR(1)    NOT NULL,
    fecha_actualizacion_estado TIMESTAMPTZ,
    fecha_vigencia_oferta      DATE,
    -- Condiciones del trato que el broker evalua y que el contrato hereda al cerrar.
    plazo_contrato_meses       INTEGER,
    fecha_inicio_contrato      DATE,
    forma_pago                 VARCHAR(20),
    meses_garantia             INTEGER,
    meses_adelanto             INTEGER,
    id_oportunidad             BIGINT        NOT NULL REFERENCES oportunidad_comercial (id_oportunidad),
    id_rol_agente              BIGINT        NOT NULL REFERENCES detalle_agente (id_persona_rol),
    fecha_creacion             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_actualizacion        TIMESTAMPTZ,
    -- G registrada, E en evaluacion, O observada, A aprobada, R rechazada,
    -- D desistida, C cerrada (su alquiler se concreto en contrato).
    CONSTRAINT ck_solicitud_estado CHECK (estado IN ('G', 'E', 'O', 'A', 'R', 'D', 'C')),
    CONSTRAINT ck_solicitud_monto CHECK (monto_propuesto >= 0),
    CONSTRAINT ck_solicitud_plazo CHECK (plazo_contrato_meses IS NULL OR plazo_contrato_meses > 0),
    CONSTRAINT ck_solicitud_meses CHECK (
        (meses_garantia IS NULL OR meses_garantia >= 0)
        AND (meses_adelanto IS NULL OR meses_adelanto >= 0)),
    -- Una sola solicitud por oportunidad (cable v1: id_oportunidad UNIQUE).
    CONSTRAINT uq_solicitud_oportunidad UNIQUE (id_oportunidad),
    -- El codigo SOL-yyMMddHHmmss es unico DENTRO del tenant (D-F4-4).
    CONSTRAINT uq_solicitud_codigo UNIQUE (organizacion_id, codigo_solicitud),
    CONSTRAINT uq_solicitud_org UNIQUE (organizacion_id, id_solicitud),
    CONSTRAINT fk_solicitud_oportunidad_org FOREIGN KEY (organizacion_id, id_oportunidad)
        REFERENCES oportunidad_comercial (organizacion_id, id_oportunidad),
    CONSTRAINT fk_solicitud_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol)
);

CREATE INDEX ix_solicitud_agente ON solicitud_alquiler (organizacion_id, id_rol_agente);
CREATE INDEX ix_solicitud_estado ON solicitud_alquiler (organizacion_id, estado);

-- ---------------------------------------------------------------------
-- Documento entregado para la solicitud. Nace Registrado con revision
-- Pendiente; el broker lo deja Validado u Observado.
-- ---------------------------------------------------------------------
CREATE TABLE documento_solicitud (
    id_documento                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id             BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    id_solicitud                BIGINT       NOT NULL REFERENCES solicitud_alquiler (id_solicitud) ON DELETE CASCADE,
    id_tipo_documento_requerido BIGINT       NOT NULL REFERENCES tipo_documento_requerido (id_tipo_documento_requerido),
    nombre_archivo              VARCHAR(255) NOT NULL,
    -- Clave del almacen hibrido (S3 o disco), no una ruta del sistema.
    ruta_archivo                VARCHAR(255),
    fecha_entrega               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    estado                      VARCHAR(1)   NOT NULL,
    resultado_revision          VARCHAR(1),
    observaciones               TEXT,
    CONSTRAINT ck_documento_estado CHECK (estado IN ('R', 'O', 'V')),
    CONSTRAINT ck_documento_revision CHECK (
        resultado_revision IS NULL OR resultado_revision IN ('P', 'C', 'O')),
    -- Un documento observado SIEMPRE lleva el porque (MEJ-03, como en captaciones).
    CONSTRAINT ck_documento_observacion CHECK (
        resultado_revision <> 'O' OR (observaciones IS NOT NULL AND btrim(observaciones) <> '')),
    CONSTRAINT uq_documento_org UNIQUE (organizacion_id, id_documento),
    CONSTRAINT fk_documento_solicitud_org FOREIGN KEY (organizacion_id, id_solicitud)
        REFERENCES solicitud_alquiler (organizacion_id, id_solicitud)
);

CREATE INDEX ix_documento_solicitud ON documento_solicitud (organizacion_id, id_solicitud);
CREATE INDEX ix_documento_tipo ON documento_solicitud (id_tipo_documento_requerido);

-- ---------------------------------------------------------------------
-- Evaluacion del broker. NO es transicionable: es un evento con
-- resultado que MUEVE la solicitud (aprobar / rechazar / observar).
-- El tipo se DERIVA del resultado, el broker no lo elige.
-- ---------------------------------------------------------------------
CREATE TABLE evaluacion_solicitud (
    id_evaluacion    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_solicitud     BIGINT      NOT NULL REFERENCES solicitud_alquiler (id_solicitud),
    id_rol_broker    BIGINT      NOT NULL REFERENCES detalle_broker (id_persona_rol),
    fecha_evaluacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    resultado        VARCHAR(1)  NOT NULL,
    tipo_evaluacion  VARCHAR(1)  NOT NULL,
    observaciones    TEXT,
    CONSTRAINT ck_evaluacion_resultado CHECK (resultado IN ('A', 'R', 'O')),
    CONSTRAINT ck_tipo_evaluacion CHECK (tipo_evaluacion IN ('P', 'O', 'F')),
    -- El tipo se deriva del resultado (cable v1): observada => OBSERVACION,
    -- aprobada/rechazada => FINAL. El CHECK lo garantiza en la BD.
    CONSTRAINT ck_evaluacion_tipo_derivado CHECK (
        (resultado = 'O' AND tipo_evaluacion = 'O')
        OR (resultado IN ('A', 'R') AND tipo_evaluacion = 'F')),
    CONSTRAINT uq_evaluacion_org UNIQUE (organizacion_id, id_evaluacion),
    CONSTRAINT fk_evaluacion_solicitud_org FOREIGN KEY (organizacion_id, id_solicitud)
        REFERENCES solicitud_alquiler (organizacion_id, id_solicitud),
    CONSTRAINT fk_evaluacion_broker_org FOREIGN KEY (organizacion_id, id_rol_broker)
        REFERENCES detalle_broker (organizacion_id, id_persona_rol)
);

-- "Solo una evaluacion FINAL por solicitud": la v1 lo resolvia con una
-- columna generada + UNIQUE; en Postgres es un unico parcial nativo.
CREATE UNIQUE INDEX uq_evaluacion_final_por_solicitud
    ON evaluacion_solicitud (id_solicitud) WHERE tipo_evaluacion = 'F';

CREATE INDEX ix_evaluacion_solicitud ON evaluacion_solicitud (organizacion_id, id_solicitud);
CREATE INDEX ix_evaluacion_broker ON evaluacion_solicitud (organizacion_id, id_rol_broker);

-- ---------------------------------------------------------------------
-- Contrato de alquiler: vinculo + formalizacion. Las condiciones del
-- trato viven en la solicitud, no se copian.
-- ---------------------------------------------------------------------
CREATE TABLE contrato_alquiler (
    id_contrato_alquiler BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id      BIGINT      NOT NULL REFERENCES organizacion (id_organizacion),
    id_oportunidad       BIGINT      NOT NULL REFERENCES oportunidad_comercial (id_oportunidad),
    id_solicitud         BIGINT      REFERENCES solicitud_alquiler (id_solicitud),
    fecha_cierre         DATE        NOT NULL,
    estado_contrato      VARCHAR(1)  NOT NULL,
    incidencias          TEXT,
    fecha_creacion       TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion  TIMESTAMPTZ,
    CONSTRAINT ck_contrato_estado CHECK (estado_contrato IN ('P', 'D', 'V', 'R', 'F', 'S', 'A')),
    -- Un contrato por oportunidad y por solicitud (cable v1: ambas UNIQUE).
    CONSTRAINT uq_contrato_oportunidad UNIQUE (id_oportunidad),
    CONSTRAINT uq_contrato_solicitud UNIQUE (id_solicitud),
    CONSTRAINT uq_contrato_org UNIQUE (organizacion_id, id_contrato_alquiler),
    CONSTRAINT fk_contrato_oportunidad_org FOREIGN KEY (organizacion_id, id_oportunidad)
        REFERENCES oportunidad_comercial (organizacion_id, id_oportunidad),
    CONSTRAINT fk_contrato_solicitud_org FOREIGN KEY (organizacion_id, id_solicitud)
        REFERENCES solicitud_alquiler (organizacion_id, id_solicitud)
);

CREATE INDEX ix_contrato_organizacion ON contrato_alquiler (organizacion_id);

-- ---------------------------------------------------------------------
-- Liquidacion de comision. Nace PENDIENTE con la bruta (% pactado x un
-- mes de renta); el broker supervisor define despues el monto del agente
-- y el sistema calcula el de la empresa.
-- estado y forma_pago viajan con el NOMBRE del enum, no CHAR(1).
-- ---------------------------------------------------------------------
CREATE TABLE comision_liquidacion (
    id_comision_liquidacion BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id         BIGINT        NOT NULL REFERENCES organizacion (id_organizacion),
    id_contrato_alquiler    BIGINT        NOT NULL REFERENCES contrato_alquiler (id_contrato_alquiler),
    monto                   NUMERIC(12,2) NOT NULL,
    moneda                  VARCHAR(10)   NOT NULL,
    monto_agente            NUMERIC(12,2),
    monto_empresa           NUMERIC(12,2),
    fecha_cobro             DATE,
    forma_pago              VARCHAR(20),
    estado                  VARCHAR(20)   NOT NULL,
    CONSTRAINT ck_comision_moneda CHECK (moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_comision_estado CHECK (estado IN ('PENDIENTE', 'PARCIAL', 'COBRADA', 'ANULADA')),
    CONSTRAINT ck_comision_forma_pago CHECK (
        forma_pago IS NULL OR forma_pago IN (
            'TRANSFERENCIA', 'DEPOSITO_BANCARIO', 'EFECTIVO', 'CHEQUE', 'OTRO')),
    CONSTRAINT ck_comision_montos CHECK (
        monto >= 0
        AND (monto_agente IS NULL OR monto_agente >= 0)
        AND (monto_empresa IS NULL OR monto_empresa >= 0)),
    -- Una liquidacion por contrato.
    CONSTRAINT uq_comision_contrato UNIQUE (id_contrato_alquiler),
    CONSTRAINT uq_comision_org UNIQUE (organizacion_id, id_comision_liquidacion),
    CONSTRAINT fk_comision_contrato_org FOREIGN KEY (organizacion_id, id_contrato_alquiler)
        REFERENCES contrato_alquiler (organizacion_id, id_contrato_alquiler)
);

CREATE INDEX ix_comision_estado ON comision_liquidacion (organizacion_id, estado);

-- =====================================================================
-- Seed DEMO de desarrollo (tenant de legado): una solicitud EN REVISION
-- con documentos entregados, para que la bandeja del broker y el
-- checklist "X/Y" tengan con que responder. La oportunidad DEMO de V7
-- (OP-0001) es la unica disponible, y una oportunidad admite una sola
-- solicitud.
-- =====================================================================
DO $$
DECLARE
    legado       BIGINT := (SELECT id_organizacion FROM organizacion WHERE codigo = 'BROX_LEGACY');
    rol_agente   BIGINT := (SELECT id_persona_rol FROM detalle_agente WHERE codigo_agente = 'AGE-001');
    oportunidad  BIGINT := (SELECT id_oportunidad FROM oportunidad_comercial WHERE codigo_oportunidad = 'OP-0001');
    solicitud    BIGINT;
BEGIN
    IF oportunidad IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO solicitud_alquiler (organizacion_id, codigo_solicitud, fecha_registro, monto_propuesto,
                                    plazo_tentativo, observaciones, estado, fecha_actualizacion_estado,
                                    fecha_vigencia_oferta, plazo_contrato_meses, fecha_inicio_contrato,
                                    forma_pago, meses_garantia, meses_adelanto, id_oportunidad, id_rol_agente)
    VALUES (legado, 'SOL-260715103000', DATE '2026-07-15', 9000,
            '24 meses', 'Oferta formal tras la visita al local.', 'E',
            TIMESTAMPTZ '2026-07-16 09:00:00-05', DATE '2026-08-15', 24, DATE '2026-09-01',
            'TRANSFERENCIA', 2, 1, oportunidad, rol_agente)
    RETURNING id_solicitud INTO solicitud;

    -- Cuatro de los seis tipos del checklist: la bandeja muestra 4/6.
    INSERT INTO documento_solicitud (organizacion_id, id_solicitud, id_tipo_documento_requerido,
                                     nombre_archivo, ruta_archivo, fecha_entrega, estado, resultado_revision)
    VALUES
        (legado, solicitud, 1, 'dni-mariana-delgado.pdf', 'SOL-260715103000/dni-mariana-delgado.pdf',
         TIMESTAMPTZ '2026-07-15 11:00:00-05', 'V', 'C'),
        (legado, solicitud, 2, 'ficha-ruc.pdf', 'SOL-260715103000/ficha-ruc.pdf',
         TIMESTAMPTZ '2026-07-15 11:05:00-05', 'V', 'C'),
        (legado, solicitud, 5, 'sustento-ingresos.pdf', 'SOL-260715103000/sustento-ingresos.pdf',
         TIMESTAMPTZ '2026-07-15 11:10:00-05', 'R', 'P'),
        (legado, solicitud, 6, 'carta-garantia.pdf', 'SOL-260715103000/carta-garantia.pdf',
         TIMESTAMPTZ '2026-07-15 11:15:00-05', 'R', 'P');

    -- La solicitud llego a EN REVISION porque el agente la envio; aun no
    -- hay evaluacion del broker (la bandeja de decision la espera).
END $$;
