-- =====================================================================
-- V9: F6 ALERTAS + F7 TAREAS (contrato congelado en
-- docs/ai/contrato-congelado-f6-f7-alertas-tareas.md).
--  * Van juntas porque son la misma pieza vista desde dos lados: la
--    alerta AVISA, la tarea MANDA A HACER. Las dos cuelgan siempre de un
--    AGENTE y las dos alimentan el dashboard.
--  * La regla que ordena el modulo: NO hay columna de destinatario. Una
--    alerta se ata al agente y su broker supervisor la ve a traves de la
--    supervision; quien es el destinatario lo dice el TIPO. Por eso
--    CAPTACION_CREADA (escrita para el broker) y CAPTACION_REVISADA
--    (escrita para el agente) cuelgan las dos del mismo agente.
--  * Vocabulario 100% por NOMBRE del enum, no CHAR(1): es la vertical
--    que mas rompe la convencion del proyecto. Aqui no hay ni un codigo
--    de una letra.
--  * ALERTA y TAREA estan sembradas en entidad_tipo desde V2 con
--    auditable = FALSE, y asi se quedan: NO son Transicionable. Auditar
--    cada reconcile de la bandeja inundaria historial_estado de ruido
--    operativo.
--  * reporte_propietario entra aqui aunque su REST siga pendiente: el
--    disparador 6 de la bandeja (reporte periodico al propietario)
--    necesita UNA lectura suya —el ultimo reporte por captacion— y sin
--    la tabla ese disparador no existiria, que es una divergencia
--    observable en GET /tareas (D-F7-1).
--  * Todo privado del tenant (V6): organizacion_id NOT NULL sin DEFAULT
--    y FK compuestas contra el padre para que no se cruce el tenant.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Reporte periodico al propietario. Su REST (/captaciones/{id}/
-- reportes-propietario) llega con su modulo; aqui solo se necesita la
-- tabla para poder preguntar "cuando fue el ultimo" (D-F7-1).
-- canal_envio replica el catalogo de canales de la v1 (L,W,E,P,R,T,O).
-- ---------------------------------------------------------------------
CREATE TABLE reporte_propietario (
    id_reporte_propietario BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id        BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    id_captacion           BIGINT       NOT NULL REFERENCES captacion (id_captacion) ON DELETE CASCADE,
    id_rol_agente          BIGINT       NOT NULL REFERENCES detalle_agente (id_persona_rol),
    fecha_reporte          DATE         NOT NULL,
    periodo_inicio         DATE,
    periodo_fin            DATE,
    consultas_reportadas   INT          NOT NULL,
    visitas_reportadas     INT          NOT NULL,
    objeciones_frecuentes  VARCHAR(500),
    ajustes_recomendados   VARCHAR(500),
    canal_envio            VARCHAR(1)   NOT NULL,
    fecha_creacion         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_reporte_canal CHECK (canal_envio IN ('L', 'W', 'E', 'P', 'R', 'T', 'O')),
    CONSTRAINT ck_reporte_cantidades CHECK (consultas_reportadas >= 0 AND visitas_reportadas >= 0),
    CONSTRAINT ck_reporte_periodo CHECK (
        periodo_fin IS NULL OR periodo_inicio IS NULL OR periodo_fin >= periodo_inicio),
    CONSTRAINT uq_reporte_org UNIQUE (organizacion_id, id_reporte_propietario),
    CONSTRAINT fk_reporte_captacion_org FOREIGN KEY (organizacion_id, id_captacion)
        REFERENCES captacion (organizacion_id, id_captacion),
    CONSTRAINT fk_reporte_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol)
);

-- El disparador 6 pregunta exactamente esto: ultimo reporte por captacion.
CREATE INDEX ix_reporte_captacion_fecha
    ON reporte_propietario (organizacion_id, id_captacion, fecha_reporte DESC);

-- ---------------------------------------------------------------------
-- Alerta: el aviso de la campana. Los cinco tipos SIN emisor en la v1
-- (SIN_AVANCE, OFERTA_POR_VENCER, CONTRATO_POR_VENCER, VISITA_PROXIMA,
-- CAPTACION_VENCIDA) se mantienen en el CHECK por paridad: estan en el
-- enum del cable y en el CHECK de la v1 aunque nadie los emita.
-- ---------------------------------------------------------------------
CREATE TABLE alerta (
    id_alerta        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    tipo             VARCHAR(30)  NOT NULL,
    severidad        VARCHAR(10)  NOT NULL,
    -- OJO: NO es una FK a entidad_tipo. Esa tabla es el registro de AUDITORIA
    -- (que entidades emiten historial_estado); esto es VOCABULARIO DEL CABLE, y
    -- los dos no coinciden: la v1 emite 'INMUEBLE' —la alerta de modificacion
    -- sensible de F2 y el efecto 7 de F4— donde la v2 renombro la entidad a
    -- PROPIEDAD (MEJ-12/31). Con FK esas dos emisiones se caerian. Se replica el
    -- vocabulario del cable tal cual (D-F6-4).
    entidad_tipo     VARCHAR(30)  NOT NULL,
    entidad_id       BIGINT       NOT NULL,
    id_rol_agente    BIGINT       NOT NULL REFERENCES detalle_agente (id_persona_rol),
    mensaje          VARCHAR(300) NOT NULL,
    estado           VARCHAR(15)  NOT NULL,
    fecha_generacion TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_resolucion TIMESTAMPTZ,
    CONSTRAINT ck_alerta_tipo CHECK (tipo IN (
        'SIN_RESPUESTA', 'SIN_AVANCE', 'OFERTA_POR_VENCER',
        'CONTRATO_POR_VENCER', 'VISITA_PROXIMA', 'CAPTACION_VENCIDA',
        'SOLICITUD_REENVIADA', 'SOLICITUD_EVALUADA',
        'SOLICITUD_DOCUMENTO', 'SOLICITUD_DOCUMENTO_REVISADO',
        'CAPTACION_CREADA', 'CAPTACION_REVISADA',
        'CAPTACION_CERRADA', 'OPORTUNIDAD_CERRADA',
        'COMISION_ASIGNADA', 'COMISION_COBRADA')),
    CONSTRAINT ck_alerta_severidad CHECK (severidad IN ('INFO', 'MEDIA', 'ALTA')),
    -- La v1 deja entidad_tipo libre en alerta; aqui se acota al mismo
    -- vocabulario que tarea. Es invisible en el cable (todo lo que se emite
    -- esta en la lista) y evita que un typo entre en la campana.
    CONSTRAINT ck_alerta_entidad_tipo CHECK (entidad_tipo IN (
        'PROSPECCION', 'CAPTACION', 'OPORTUNIDAD', 'INTERACCION',
        'VISITA', 'SOLICITUD_ALQUILER', 'INMUEBLE', 'PUBLICACION',
        'CONTRATO_ALQUILER', 'CLIENTE_INTERESADO', 'PROPIETARIO', 'REQUERIMIENTO')),
    CONSTRAINT ck_alerta_estado CHECK (estado IN ('ACTIVA', 'ATENDIDA', 'DESCARTADA')),
    -- Atendida/descartada SIEMPRE lleva su fecha; activa nunca la tiene.
    CONSTRAINT ck_alerta_resolucion CHECK (
        (estado = 'ACTIVA' AND fecha_resolucion IS NULL)
        OR (estado <> 'ACTIVA' AND fecha_resolucion IS NOT NULL)),
    CONSTRAINT uq_alerta_org UNIQUE (organizacion_id, id_alerta),
    CONSTRAINT fk_alerta_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol)
);

-- La campana lee "activas del agente, mas recientes primero".
CREATE INDEX ix_alerta_agente_estado
    ON alerta (organizacion_id, id_rol_agente, estado, fecha_generacion DESC);
-- El barrido de recontacto pregunta "ya hay una activa de este tipo para esta entidad?".
CREATE INDEX ix_alerta_entidad
    ON alerta (organizacion_id, entidad_tipo, entidad_id, estado);

-- ---------------------------------------------------------------------
-- Tarea: la bandeja "Acciones Pendientes" del agente. NO hay alta
-- manual — las tareas se DERIVAN del estado del flujo y se reconcilian
-- en cada lectura. El agente solo las resuelve trabajando (se
-- auto-completan) o las cancela.
--
-- entidad_codigo, ruta_resolver, dias_sin_accion y fecha_vencimiento NO
-- son columnas: se derivan al leer (§5.3 del contrato).
--
-- El unico parcial es la clave de deduplicacion del reconcile: una sola
-- tarea ABIERTA por (agente, entidad). Es la version en BD de lo que la
-- v1 hacia solo en memoria con un Set de claves.
-- ---------------------------------------------------------------------
CREATE TABLE tarea (
    id_tarea             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id      BIGINT       NOT NULL REFERENCES organizacion (id_organizacion),
    tipo                 VARCHAR(30)  NOT NULL,
    -- Vocabulario del cable, no FK a entidad_tipo (misma razon que en alerta:
    -- el efecto 7 de F4 resuelve tareas de 'INMUEBLE', que en la v2 es
    -- PROPIEDAD). Lo acota el CHECK de abajo, calcado de ck_tarea_tipo_entidad.
    entidad_tipo         VARCHAR(30)  NOT NULL,
    entidad_id           BIGINT       NOT NULL,
    id_rol_agente        BIGINT       NOT NULL REFERENCES detalle_agente (id_persona_rol),
    descripcion          VARCHAR(300) NOT NULL,
    fecha_programada     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_recordatorio   TIMESTAMPTZ,
    fecha_completada     TIMESTAMPTZ,
    estado               VARCHAR(20)  NOT NULL,
    prioridad            VARCHAR(10)  NOT NULL,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_actualizacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_tarea_tipo CHECK (tipo IN (
        'SEGUIMIENTO', 'LLAMADA', 'VISITA', 'ENVIO_INFO', 'RECONTACTO',
        'REPORTE_PROPIETARIO', 'ENVIAR_REVISION', 'SUBIR_DOCUMENTOS',
        'REGISTRAR_CAPTACION', 'REGISTRAR_INTERACCION', 'PROPONER_OPORTUNIDAD', 'OTRO')),
    CONSTRAINT ck_tarea_tipo_entidad CHECK (entidad_tipo IN (
        'PROSPECCION', 'CAPTACION', 'OPORTUNIDAD', 'INTERACCION',
        'VISITA', 'SOLICITUD_ALQUILER', 'INMUEBLE', 'PUBLICACION',
        'CONTRATO_ALQUILER', 'CLIENTE_INTERESADO', 'PROPIETARIO', 'REQUERIMIENTO')),
    CONSTRAINT ck_tarea_estado CHECK (estado IN (
        'PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'VENCIDA', 'CANCELADA')),
    CONSTRAINT ck_tarea_prioridad CHECK (prioridad IN ('ALTA', 'MEDIA', 'BAJA')),
    CONSTRAINT ck_tarea_completada CHECK (
        estado <> 'COMPLETADA' OR fecha_completada IS NOT NULL),
    CONSTRAINT uq_tarea_org UNIQUE (organizacion_id, id_tarea),
    CONSTRAINT fk_tarea_agente_org FOREIGN KEY (organizacion_id, id_rol_agente)
        REFERENCES detalle_agente (organizacion_id, id_persona_rol)
);

-- Dedup del reconcile: una sola tarea ABIERTA por (agente, entidad).
-- CANCELADA queda FUERA del parcial a proposito: no bloquea por indice,
-- lo hace el reconcile en memoria (§5.2, trampa 1). Si entrara aqui, una
-- tarea cancelada y otra pendiente de la misma entidad chocarian.
CREATE UNIQUE INDEX uq_tarea_abierta_por_entidad
    ON tarea (organizacion_id, id_rol_agente, entidad_tipo, entidad_id)
    WHERE estado IN ('PENDIENTE', 'EN_PROCESO');

-- La bandeja lee "abiertas del agente" y el reconcile "todas del agente".
CREATE INDEX ix_tarea_agente_estado ON tarea (organizacion_id, id_rol_agente, estado);
-- El efecto 7 de la cascada de F4 resuelve "las tareas de esta entidad".
CREATE INDEX ix_tarea_entidad ON tarea (organizacion_id, entidad_tipo, entidad_id, estado);

-- =====================================================================
-- Seed DEMO de desarrollo (tenant de legado): dos alertas activas para
-- que la campana tenga que mostrar, sobre la solicitud DEMO de V8.
-- Las TAREAS no se siembran a proposito: son derivadas, las produce el
-- primer GET /tareas del agente a partir del estado real del flujo.
-- =====================================================================
DO $$
DECLARE
    legado     BIGINT := (SELECT id_organizacion FROM organizacion WHERE codigo = 'BROX_LEGACY');
    rol_agente BIGINT := (SELECT id_persona_rol FROM detalle_agente WHERE codigo_agente = 'AGE-001');
    solicitud  BIGINT := (SELECT id_solicitud FROM solicitud_alquiler
                           WHERE codigo_solicitud = 'SOL-260715103000');
    captacion  BIGINT := (SELECT id_captacion FROM captacion WHERE codigo_captacion = 'CAP-0001');
BEGIN
    IF solicitud IS NULL OR rol_agente IS NULL THEN
        RETURN;
    END IF;

    INSERT INTO alerta (organizacion_id, tipo, severidad, entidad_tipo, entidad_id,
                        id_rol_agente, mensaje, estado, fecha_generacion)
    VALUES (legado, 'SOLICITUD_REENVIADA', 'MEDIA', 'SOLICITUD_ALQUILER', solicitud,
            rol_agente,
            'La solicitud SOL-260715103000 fue enviada a evaluacion del broker supervisor.',
            'ACTIVA', TIMESTAMPTZ '2026-07-16 09:00:00-05');

    IF captacion IS NOT NULL THEN
        INSERT INTO alerta (organizacion_id, tipo, severidad, entidad_tipo, entidad_id,
                            id_rol_agente, mensaje, estado, fecha_generacion)
        VALUES (legado, 'CAPTACION_CREADA', 'MEDIA', 'CAPTACION', captacion,
                rol_agente,
                'El agente registro la captacion CAP-0001 para tu revision.',
                'ACTIVA', TIMESTAMPTZ '2026-07-10 10:30:00-05');
    END IF;
END $$;
