export interface OpcionCatalogo {
  readonly valor: string;
  readonly etiqueta: string;
}

export const ESTADOS_LOCAL_FORM: readonly OpcionCatalogo[] = [
  { valor: 'D', etiqueta: 'Disponible' },
  { valor: 'N', etiqueta: 'No disponible' },
  { valor: 'I', etiqueta: 'Inactivo' },
];

export const TIPOS_INMUEBLE: readonly OpcionCatalogo[] = [
  { valor: 'L', etiqueta: 'Local' },
  { valor: 'O', etiqueta: 'Oficina' },
];

export const DISTRITOS_LIMA: readonly string[] = [
  'Ancon',
  'Ate',
  'Barranco',
  'Breña',
  'Carabayllo',
  'Chaclacayo',
  'Chorrillos',
  'Cieneguilla',
  'Comas',
  'El Agustino',
  'Independencia',
  'Jesus Maria',
  'La Molina',
  'La Victoria',
  'Lima',
  'Lince',
  'Los Olivos',
  'Lurigancho-Chosica',
  'Lurin',
  'Magdalena del Mar',
  'Miraflores',
  'Pachacamac',
  'Pucusana',
  'Pueblo Libre',
  'Puente Piedra',
  'Punta Hermosa',
  'Punta Negra',
  'Rimac',
  'San Bartolo',
  'San Borja',
  'San Isidro',
  'San Juan de Lurigancho',
  'San Juan de Miraflores',
  'San Luis',
  'San Martin de Porres',
  'San Miguel',
  'Santa Anita',
  'Santa Maria del Mar',
  'Santa Rosa',
  'Santiago de Surco',
  'Surquillo',
  'Villa El Salvador',
  'Villa Maria del Triunfo',
];

export const RUBROS_COMERCIALES: readonly string[] = [
  'Restaurante / Cafe',
  'Cafeteria / Postres',
  'Moda / Boutique',
  'Retail',
  'Minimarket / Bodega',
  'Panaderia / Pasteleria',
  'Farmacia / Botica',
  'Salud / Consultorio',
  'Belleza / Barberia',
  'Gimnasio / Fitness',
  'Educacion / Academia',
  'Oficina administrativa',
  'Servicios profesionales',
  'Ferreteria',
  'Veterinaria',
  'Tecnologia / Electronica',
  'Muebles / Decoracion',
  'Almacen / Deposito',
  'Logistica ligera',
  'Automotriz',
  'Mascotas',
  'Entretenimiento',
  'Comida rapida',
  'Dark kitchen',
  'Otro rubro comercial',
];
